bin/post_deploy
Collect statics is done in post-compile script, it is useless in post-deploy script
=> remove useless collectstatic

qfdmo/admin.py
- lvao_base is readonly because it was slow (too many option)
- display lvao_base_revision with revision_id in list and sort by revision_id
=> Improve display of LVAO revision in admin

README.md, qfdmo/views.py, static/to_compile/src/map_controller.ts
sometimes too few points are displayed, missing a distinct on query
=> query distinct points

README.md, integration_tests/qfdmo/test_reemploi_solution.py, jinja2/layout/base.html, jinja2/qfdmo/analyse.html, jinja2/qfdmo/analyse_lvao_base.html, jinja2/qfdmo/partials/action_list_by_direction.html, jinja2/qfdmo/reemploi_solution.html, qfdmo/forms.py, qfdmo/views.py, static/to_compile/entrypoints/qfdmo.css, static/to_compile/src/address_autocomplete_controller.ts, static/to_compile/src/autocomplete_controller.ts, static/to_compile/src/choose_action_controller.ts, static/to_compile/src/types.ts, static/to_compile/tests/choose_action_controller.test.ts, templates/django/forms/widgets/autocomplete.html
- “Indiquer une catégorie d’objet”
- “Autour de l’adresse”
=> re-organize search form

core/settings.py, qfdmo/admin/acteur.py
=> Limit export nb of rows without raise

bin/start
Because be rich routing limit : https://doc.scalingo.com/platform/internals/routing#requests-queue
Create more instance should reduce this impact
=> downscale gunicorn to allow using more instance but less powerful

.github/dependabot.yml
no need pip-compile enngine declaration
=> rollback pip-compile engine because it is automatically detect

jinja2/qfdmo/partials/search_solution.html
cf. audit RGAA
> [Formulaire Maps - Bouton "Rechercher"]
L'intitulé du bouton n'est pas pertinent.
Le balise button ne dépend pas du contexte. Il doit être explicite à lui seul.
=> [Accessibilité] Label du bouton rechercer plus explicite quand c'est possible

jinja2/qfdmo/partials/search_solution.html
Suite à l'audit RGAA
> [Formulaire Maps - "J'ai" - Filtres avancés ouvert]
L'odre de tabulation n'est pas cohérante.
On tabule sur la croix "fermer" puis sur le label "Label Répar'Acteurs".
Éxecuter le passage de focus du formulaire dans le bon ordre avec la touche tab
=> [Accessibilité] Passer le focus du formulaire dans le bon ordre

README.md, integration_tests/qfdmo/test_reemploi_solution.py, integration_tests/qfdmo/test_search_form.py, jinja2/qfdmo/partials/display_solutions.html, jinja2/qfdmo/partials/featureflip_inputs.html, jinja2/qfdmo/partials/search_solution.html, qfdmo/forms.py, qfdmo/models/action.py, qfdmo/views/display_solutions.py, static/to_compile/src/map_controller.ts, unit_tests/qfdmo/acteur_factory.py, unit_tests/qfdmo/action_factory.py, unit_tests/qfdmo/test_acteur.py, unit_tests/qfdmo/test_action.py
add first_dir (aka first_direction) parameter in url to display the mentioned direction first in the option list.
Available options:
* jai
* jecherche
url : http://localhost:8000/?first_dir=jecherche
url : http://localhost:8000/?fd=jai
Left to do:
=> Make the first direction displayed overridable using a parameter

core/jinja2_handler.py, package-lock.json, qfdmo/views/adresses.py
The actions are ordered un the list of action inside group following their order field :
ex : 
-> 
And display_actions is applied in form mode
=> actions ordered inside groupe and displayed action in form mode

dags/annuaire_entreprise_checks.py, dags/corepile.py, dags/create_final_actors.py, dags/ecodds.py, dags/ecologic.py, dags/ecosystem.py, dags/ingest_validated_dataset_to_db.py, dags/ocab.py, dags/pyreo.py, dags/refashion.py, dags/soren.py, dags/valdelia.py
Following deprecation documentation :
- for [schedule_interval](https://airflow.apache.org/docs/apache-airflow/2.4.0/release_notes.html#deprecation-of-schedule-interval-and-timetable-arguments-25410) 
- for [provide_context](https://airflow.apache.org/docs/apache-airflow/2.4.0/release_notes.html#airflow-operators-python-pythonoperator)
=> Manage deprecation for schedule_interval and provide_context

dags/corepile.py, dags/ecodds.py, dags/ecologic.py, dags/ecosystem.py, dags/ocab.py, dags/pyreo.py, dags/refashion.py, dags/soren.py, dags/utils/dag_eo_utils.py, dags/utils/eo_operators.py, dags/valdelia.py, unit_tests/dags/utils/dag_eo_utils_test.py
Hello @Hazelmat 
Voici une proposition de refactorisation des dags et de leurs opérateurs
Mettre la configuration dans les parametres du DAG (à terme ou pourrait déplacer cette configuration dans des fichiers si nécessaire)
```
params={
"endpoint": (
"https://data.pointsapport.ademe.fr/data-fair/api/v1/datasets/"
"donnees-eo-corepile/lines?size=10000"
)
},
```
Accès à ces paramètres dans les opérateurs : 
```
def fetch_data_from_api(**kwargs):
params = kwargs["params"]
api_url = params["endpoint"]
```
déclarer les opérateurs dans un fichier dédié `dags/utils/eo_operators.py` et appeler ces opérateurs dans le fichier du dag :
```
(
[eo_operators.fetch_data_task(dag), …]
>> …
```
Ainsi, il ne resterait dans les fichiers de DAG que la configuration du DAG via les paramètres et le graph du …
=> [Proposition] Refactoring of dags

core/jinja2_handler.py, core/settings.py, jinja2/editorial/sitemap.html, jinja2/layout/footer.html, jinja2/qfdmo/_addresses_partials/map_and_detail.html, jinja2/registration/login.html, qfdmo/urls.py, unit_tests/qfdmo/test_views.py
Ajout d'un formulaire de connexion pour permettre aux utilisateurs n'ayant pas accès à l'admin django de quand même voir le configurateur.   
Ref : https://www.notion.so/accelerateur-transition-ecologique-ademe/Acc-s-au-configurateur-Atelier-111-da47ccc49b3e42da950c630afa5cd1d3?pvs=4 
J'ai ajouté une vue : 
1. Tentative d'accès à `/iframe/configurateur`
2. Redirection vers `/connexion`
3. À la connexion : redirection vers `/iframe/configurateur`
**TODO** 
**QUESTIONS**
=> add login form

qfdmo/views/adresses.py, tailwind.config.js
Il manque des classes CSS à la safelist tailwind, je les ai ajoutées ainsi qu'un commentaire pour l'éviter plus tard.
=> Add missing classes to tailwind safelist

jinja2/qfdmo/_addresses_partials/carte_header.html, jinja2/qfdmo/_addresses_partials/map_and_detail.html
dans cette PR on modifie le point de rupture pour l'affichage de la légende comme un paneau apparaissan lors de l'appuie sur le bouton legends ou comme un ecart toujours visible : 
vs
Reste à choisir avec @LuluFreeDesign quel est le point de rupture pour ce changement de comportement :  `md` ou `lg`. Si `lg` est choisit il faudra modifier cette PR en conséquence.
=> Update the breakingpoint to display legend in slide panel or on top of the map

docker-compose.yml
La version dans le `docker-compose` n'est plus requise depuis quelques temps. 
Ça évitera le warning au lancement de la stack `version is obsolete"  Container quefairedemesobjets-postgres-1  Created`
=> remove obsolete version in docker-compose

qfdmo/forms.py
Cf https://www.notion.so/accelerateur-transition-ecologique-ademe/Rechercher-autour-d-une-adresse-manque-le-r-69faa190b6f24ca4a67843317f8ad29b?pvs=4
=> Fix typo in placeholder rechercher adresse

core/jinja2_handler.py, jinja2/qfdmo/_addresses_partials/filters/carte_filters.html
Dans le cas de l'assistant, l'id de sous catégorie est défini dans l'URL. Lorsque c'est le cas, on cache le filtre avancé objet qui n'a pas lieu d'être. 
Ref https://www.notion.so/accelerateur-transition-ecologique-ademe/Supprimer-le-filtre-objet-dans-les-filtres-pour-l-assistant-40d4925314374da69523a237758c9056?pvs=4
=> hide object filter when sous categorie id is set

jinja2/qfdmo/_addresses_partials/carte_header.html, static/to_compile/entrypoints/qfdmo.ts, static/to_compile/src/iframe.ts
Ajout d'un script qui permet de communiquer depuis l'iframe parent 
- Si le parent qui inclut l'iframe envoie un [message](https://developer.mozilla.org/fr/docs/Web/API/Window/postMessage) d'un domaine ademe.fr, alors on cache le logo 
cf https://github.com/incubateur-ademe/quefairedemesdechets/pull/93
cf https://www.notion.so/accelerateur-transition-ecologique-ademe/Ne-pas-mettre-de-logo-au-niveau-de-la-barre-de-recherche-sinon-on-doublonne-les-logos-5843aa673270465a89bca50c85be0d0a?pvs=4
=> add script to hide logo when origin is ademe.fr

qfdmo/views/adresses.py, unit_tests/qfdmo/acteur_factory.py, unit_tests/qfdmo/test_addresses_view.py
Ref https://www.notion.so/accelerateur-transition-ecologique-ademe/Acteur-avec-exclu-de-R-paration-n-appara-t-pas-sur-la-carte-m-me-quand-on-d-coche-le-filtre-be5dd348c83b48f3a76ac60e894d0e1d?pvs=4 
Le filtrage de l'exclusivité de réparation exclut des acteurs qui devraient s'afficher, notamment car on récupère mal l'action réparer choisie par l'utilisateur.   
⚠️ J'ai réalisé que cette partie du code était pas mal *emmêlée*, je propose dans cette PR une légère réorganisation. 
Notamment : 
- Utilisation de **formulaire django plutôt que d'accéder directement aux paramètres de la requête** : c'est plus stable, les données ont déjà été validées par Django. Ça évite notamment des `int(request.GET.get("an_int_parameter", "0"))`
- J'ai **refactorisé ces méthodes** pour mieux visualiser où …
=> build exclusivite reparation filter when reparer is checked

.env.template, core/jinja2_handler.py, jinja2/qfdmo/_addresses_partials/filters/_object_filter.html, jinja2/qfdmo/_addresses_partials/filters/carte_filters.html
- ajout de la variable d'environnement utile à l'API LVAO au fichier .env.template
- masquage CSS dans le DOM du champ de filtrage des objets plutôt que de l'en supprimer pour corriger une régression depuis https://github.com/incubateur-ademe/quefairedemesobjets/commit/5e87ed0b0d05763712c807ba9baad96053038bf8
=> Correctifs pour l'API LVAO 

jinja2/layout/base.html, jinja2/qfdmo/_addresses_partials/map_and_detail.html, jinja2/qfdmo/adresse/detail.html, static/to_compile/entrypoints/qfdmo.ts, static/to_compile/src/analytics.ts, static/to_compile/src/analytics_controller.ts, static/to_compile/src/map_controller.ts, static/to_compile/src/search_solution_form_controller.ts, static/to_compile/src/types.ts
[Lien Notion](https://www.notion.so/accelerateur-transition-ecologique-ademe/Cr-ation-d-v-nement-pour-suivi-dans-Posthog-du-nombre-d-interactions-avec-une-solution-68e0ac7fdecd4943b3fe2fc055fa3857?pvs=4)
**Ajout d'appels à PostHog pour tracter les interactions utilisateurs avec l'interface.** 
- Création d'un controller stimulus agissant comme une couche d'abstraction entre la solution d'analytics et les appels : ça simplifiera le changement d'outil d'analytics dans le futur 
**En local :** 
- Aller sur http://localhost:8000/?carte
- Faire une recherche
**Les interactions ci-dessous peuvent être réalisées :**
-  un clic sur un pin point sur la carte / ouverture aperçu de la fiche
-  une ouverture de la fiche détaillée en grand “ouvrir” (sur mobile)
- un clic sur le bouton “Itinéraire”
- …
=> Track product interactions in posthog

e2e_tests/iframe.spec.ts, iframe_without_js.html, static/to_compile/entrypoints/iframe_functions.ts
Carte Notion : [En mode iFrame, l’hyperlien derrière le bouton Partager ne fonctionne plus (depuis la nouvelle carte)](https://www.notion.so/accelerateur-transition-ecologique-ademe/En-mode-iFrame-l-hyperlien-derri-re-le-bouton-Partager-ne-fonctionne-plus-depuis-la-nouvelle-carte-bb97f81d482749f982e6168ebcf85b1d?pvs=4)
Manque une permission lors de l'appel de l'iframe pour permettre d'utiliser le clipboard
- Afficher le configurateur dans Chrome
- Afficher le détail d'une adresse
- Cliquer sur `partager` par `lien`
- Le lien doit être copié dans le clipboard
N/A
N/A
=> Fix issue related to share link from an iframe

qfdmo/models/acteur.py, unit_tests/qfdmo/test_acteur.py
Suite a l'implémentation de l'action principale de l'acteur, les actions n'étaient pas correctement triées
- En mode carte, les boites à livre doivent afficher l'icone `donner` au lieu de `echanger`
=> fix l'ordre des actions dans le mode carte

static/to_compile/src/analytics.ts
Carte Notion : [Passer tracking Matomo et Posthog en cookieless](https://www.notion.so/accelerateur-transition-ecologique-ademe/Passer-tracking-Matomo-et-Posthog-en-cookieless-18a72684982c42bca564b2a9fce39cfd?pvs=4)
Mettre en place le mode debug en environnement de developpement et non dans les autres environnement comme fait actuellement
En preprod :
- Vérifier la dépose de cookie en preprod
N/A
N/A
=> set posthog debug in dvelopment env

jinja2/qfdmo/_addresses_partials/filters/carte_filters.html, static/to_compile/src/search_solution_form_controller.ts
Carte Notion : [Le paramètre “direction” en mode carte est buggé](https://www.notion.so/accelerateur-transition-ecologique-ademe/Le-param-tre-direction-en-mode-carte-est-bugg-c2fd728bca1e4519ae773409bcf99ff6?pvs=4)
On garde la `direction` grâce à un input hidden
On affiche que les actions de la direction
- Afficher la carte avec une direction et afficher un acteur
N/A
N/A
=> Résoudre l'application de la direction en mode carte

core/jinja2_handler.py, jinja2/qfdmo/adresse/detail.html, qfdmo/models/acteur.py, unit_tests/qfdmo/test_acteur.py
Carte Notion : [Carte : manque l’onglet “Adresse” quand celle-ci n’est pas complète dans la BDD (même si on a bien la ville)](https://www.notion.so/accelerateur-transition-ecologique-ademe/Carte-manque-l-onglet-Adresse-quand-celle-ci-n-est-pas-compl-te-dans-la-BDD-m-me-si-on-a-bien-l-e4d102c8bea94d05bbe5e5e6ac70f485?pvs=4.)
L'adresse doit-être afficher même si il en manque une partie
- Afficher des acteurs avec une adresse incomplète
N/A
N/A
=> Afficher l'adresse et l'onglet adresse quand l'acteur n'a pas d'adresse mais a un CP et/ou une ville

core/context_processors.py, qfdmo/admin/acteur.py, qfdmo/templates/admin/displayed_acteur/change_form.html
Carte Notion : N/A
Rendre modifiable les displayedacteur en environnement de dev permet de tester l'affichage des acteurs plus simplement sans avoir a lancer le DAG de compilation des acteurs
- Editer un displayedacteur en local, ne pas pouvoir l'éditer en preprod et en prod
N/A
N/A
=> Les displayedacteurs doivent être modifiables en environnement de dev pour faciliter les tests

jinja2/qfdmo/_addresses_partials/filters/carte_filters.html, jinja2/qfdmo/_addresses_partials/map_and_detail.html
Carte Notion : [Le paramètre “direction” en mode carte est buggé](https://www.notion.so/accelerateur-transition-ecologique-ademe/Le-param-tre-direction-en-mode-carte-est-bugg-c2fd728bca1e4519ae773409bcf99ff6?pvs=4)
Regression sur la carte détaillé qui n'affichait plus les propositions de service si aucune direction n'était configurée
- Afficher une carte détaillée en mode carte les propositions de services doivent être affichées
=> [REGRESSION] afficher les propositions de services quand il n'y a pas de direction appliquée

jinja2/qfdmo/_addresses_partials/filters/_labels_filters.html, qfdmo/forms.py, tailwind.config.js
Carte Notion : [[ACCESSIBILITÉ - CARTE] - Retirer le logo “Répar’acteurs” cliquable des filtres et le remplacer par un lien](https://www.notion.so/accelerateur-transition-ecologique-ademe/ACCESSIBILIT-CARTE-Retirer-le-logo-R-par-acteurs-cliquable-des-filtres-et-le-remplacer-par-u-17cd6e9244774af6b0bb4bdce4c29a38?pvs=4)
Remplacement de l'icône Réparacteur par un lien 
- Cliquer sur les filtres avancés 
- Un lien est présent sur le mot Reparacteur et ouvre la modale
=> add link to reparacteurs modal

jinja2/qfdmo/_addresses_partials/filters/carte_filters.html
Carte Notion : [Bug : gestes pas précochés apparaissent quand on utilise un filtre ESS](https://www.notion.so/accelerateur-transition-ecologique-ademe/Bug-gestes-pas-pr-coch-s-apparaissent-quand-on-utilise-un-filtre-ESS-3de5634488d9457483df9d1e106e0b8a?pvs=4)
Les `action_displayed` ne faisaient pas partie des champ de formulaire, si bien qu'on les perdait dès la première requête. Ils font désormais partie du formulaire via un `input` de type `hidden`
- Avec le configurateur d'iFrame, créer une carte qui n'affiche pas toutes les actions
- Faire une nouvelle recherche
-> Les actions affichées doivent être celles demandées et pas plus
=> Conserver les actions à afficher lors de la recherche sur la carte

static/to_compile/src/search_solution_form_controller.ts
Carte Notion : [Désactivation des options de réparation ne fonctionne pas en mode carte](https://www.notion.so/accelerateur-transition-ecologique-ademe/D-sactivation-des-options-de-r-paration-ne-fonctionne-pas-en-mode-carte-bdca30d0375f41b48f6733cd7cbc88c8?pvs=4)
Réfacto  des fonctions d'activation des gestes
- Afficher ou pas l'option réparer 
- cocher par défaut l'option réparer 
- Cocher décocher l'option reparer
- en mode mobile et desktop
- vérifier que mes action de filtres réparer sont activer ou désactivé à propos
=> Activation des filtres qui concernent la réparation en mode carte

jinja2/qfdmo/_addresses_partials/map_and_detail.html, templates/django/forms/widgets/autocomplete.html, templates/django/forms/widgets/autocomplete_and_search.html
Carte Notion : [Message quand il n’y a pas de solution](https://www.notion.so/accelerateur-transition-ecologique-ademe/Message-quand-il-n-y-a-pas-de-solution-f4e7e2283b2246de8317c6d9659ecc27?pvs=4)
- Déplacement du layer qui ne s'affichait plus
- Permettre de modifier les filtres quand il n'y a pas de solution
- Fix d'iun pug d'affichage des dans la barre de recherche qui n'a rien à voir :)
- Chercher quelques chose qui n'a pas de solution, ex : http://localhost:8000/?carte=&r=196&adresse=Rue+Anatole+France+01100+Oyonnax&longitude=5.657282&latitude=46.259178&bounding_box=&legend_grouped_action=donner%7Cechanger&legend_grouped_action=preter%7Cemprunter%7Clouer%7Cmettreenlocation&direction=&action_ …
=> Afficher un message quand il n'y a pas de solution

qfdmo/forms.py
Carte Notion : [Changer suggestion automatique “chaussure” par “pantalon”](https://www.notion.so/accelerateur-transition-ecologique-ademe/Changer-suggestion-automatique-chaussure-par-pantalon-fff6523d57d780f6a789c8bc054d6a0b?pvs=4)
Remplacement du placeholder 
- Vérifier que `Chaussures` ne s'affiche plus dans les suggestions du champ objet
=> Remplacer chaussures par pantalon dans les suggestions en homepage

static/to_compile/entrypoints/iframe_functions.ts
Lorsque le JSON de la bounding box de l'iframe utilise des simples quotes, l'application n'arrive pas à interpréter la bounding_box
- …
- ...
- ...
=> Vérifier le format JSON de la bounding_box dans le cscript de l'iframe

core/jinja2_handler.py, integration_tests/qfdmo/test_adresse_detail.py, jinja2/qfdmo/adresse/detail.html, qfdmo/views/adresses.py, unit_tests/core/test_jinja2_handler.py
Suite à la déduplication des acteur à afficher, les acteur on maintenant plusieurs sources
Il faut donc afficher toutes les sources liée à un acteur contrairement à avant où une seule source était affichée
Ce développement dépend de la PR #781
- …
- ...
- ...
=> Afficher toutes les sources d'un acteur

dags/utils/dag_eo_utils.py, unit_tests/dags/utils/dag_eo_utils_test.py
Problème remonté par Christian, les Bonus réparation n'était plus pris en compte pour Refashion
On comparait des clés en minuscules avec des clés en majuscule
- …
- ...
- ...
=> Résolution de la prise en compte des Bonus Réparation de Refashion

dags/utils/dag_eo_utils.py, dags_unit_tests/dags/utils/test_dag_eo_utils.py
Les colonnes oui / non : `uniquement_sur_rdv et exclusivite_de_reparation ne sont pas interprété de manière robuste
- …
- ...
- ...
=> Interprétation des colonnes oui/non et transformation en booléen

.git-blame-ignore-revs
Pour que le git blame ne fasse pas ressortir la PR de reformatage 
À run en local : `git config blame.ignoreRevsFile .git-blame-ignore-revs`
=> Add pre-commit hooks run to git ignore revs

dags/aliapur.py, dags/cma.py, dags/corepile.py, dags/ecodds.py, dags/ecologic.py, dags/ecomaison.py, dags/ecosystem.py, dags/ocab.py, dags/pyreo.py, dags/refashion.py, dags/soren.py, dags/utils/dag_eo_utils.py, dags/utils/dag_ingest_validated_utils.py, dags/utils/eo_operators.py, dags/valdelia.py, dags_unit_tests/dags/utils/test_dag_eo_utils.py
Carte Notion : [Conserver la date initiale de création d’un acteur lors d’une mise à jour (EOs Koumoul, CMA RéparActeurs…)](https://www.notion.so/accelerateur-transition-ecologique-ademe/Conserver-la-date-initiale-de-cr-ation-d-un-acteur-lors-d-une-mise-jour-EOs-Koumoul-CMA-R-parAct-d77140f465a648f9b3ff5ec057158fac?pvs=4)
Correction de cette PR : 
- On utilise la table `qfdmo_acteur` à la place de `qfdmo_displayedacteur` pour comparer les acteurs à modifier et les acteurs qu'on est en train d'importer
- On garde le champ `cree_le` de `qfdmo_acteur` quand l'entité existe déjà, sinon on prend le `now()`
- Plus besoin de filtrer sur la source dans la dataframe car c'est fait en amont, lors du selecten base de données
- Suppression de logs de débug qui trainaient
RAF:
Dans une autre PR: …
=> Garder le champ `cree_le` lors de la mise à jour des acteurs des EO

jinja2/qfdmo/_addresses_partials/map_and_detail.html
Carte Notion : [Légende - Revoir le “je trie” ⇒ “je dépose en point de collecte”](https://www.notion.so/accelerateur-transition-ecologique-ademe/L-gende-Revoir-le-je-trie-je-d-pose-en-point-de-collecte-987f0f24690940db988c2be9e48a5830?pvs=4)
Réduction  du padding sur la légende 
- Aller sur https://quefairedemesobjets-preprod.osc-fr1.scalingo.io/?carte
=> Reduce horizontal padding on legend

.github/workflows/sync_databases.yml
Carte Notion : [Synchroniser la base de Prod avec Preprod 1 fois par semaine](https://www.notion.so/accelerateur-transition-ecologique-ademe/Synchroniser-la-base-de-Prod-avec-Preprod-1-fois-par-semaine-4285b5af8dc845389975f743e5c80187?pvs=4)
Comme un cron :)
- …
=> Ajout de la synchro des environnements prod vers preprod tous les WE

qfdmo/views/configurator.py
Suite au merge du configurateur collectivité (#890), on avait un soucis de déploiement. 
C'est un mystère de pourquoi ce soucis se produisait durant le `postdeploy` Scalingo et pas en local, en revanche la cause venait d'un import pandas fait dans `urls.py` qui aurait du venir de `typing`
Ça a été déployé en preprod (via la GitHub actions) et corrige le bug qui survenait jusqu'à à présent
=> fix any not being imported from the right place

dags/utils/dag_eo_utils.py, dags/utils/mapping_utils.py, dags_unit_tests/dags/utils/test_mapping_utils.py, qfdmo/management/commands/fix_tel_9_char.py
Carte Notion : [Ajouter les 0 manquants au début des numéros de téléphone si seulement 9 caractères](https://www.notion.so/accelerateur-transition-ecologique-ademe/Ajouter-les-0-manquants-au-d-but-des-num-ros-de-t-l-phone-si-seulement-9-caract-res-6e40c7b064fd405ea50aab44b9232866?pvs=4)
- …
=> Ajout de '0' devant les numéro de téléphone en France métropolitaine

sync_dags.sh
Le script bash ne fonctionne pas sur les containeurs dans Clever Cloud, je suppose que le "\" n'est pas bien intérprété par l'executeur bash
- …
=> Tester une nouvelle gestion des variables d'environnement

qfdmo/models/acteur.py, unit_tests/qfdmo/test_acteur.py
On a identifié un _scoring_ accidentel des acteurs qui résulte d'une suppression du tri aléatoire des acteurs.
Ceci corrige cela, avec l'ajout d'un test unitaire qui vérifie qu'on ne casse pas cela dans le futur. 
- aller sur `?carte`
- chercher `Paris`
- Dézommer
- cliquer sur `rechercher dans cette zone` 
- On doit avoir des points autre que "Réparer"
=> Fix issue with ordering - accidental scoring 

qfdmo/forms.py
Dernière correction suite à https://www.notion.so/accelerateur-transition-ecologique-ademe/Configurateur-simplifi-pour-les-collectivit-s-4db7e146958942bb973910d2e92e78a3?pvs=4 
> Suite à échange avec Coline : à afficher mais pas coché
> 
> ”Je dépose en point de collecte” ne doit pas être coché par défaut dans “Choisissez les actions…”. Mais il est affiché dans la carte et dans la légende comme non coché.
> 
> Quelque soit les actions disponibles choisies dans le configurateur, tous les gestes doivent être affichés sur la carte et dans la légende.
> Mais si ils ne sont pas cochés dans “choisissez les actions”, ils sont non cochés dans la légende.
=> latest feedback

integration_tests/qfdmo/test_adresses_view.py, jinja2/qfdmo/carte/_header.html, jinja2/qfdmo/carte/_map.html, qfdmo/models/acteur.py, qfdmo/views/adresses.py, static/to_compile/src/solution_map.ts, templates/forms/widgets/autocomplete.html
[Carte Notion](https://www.notion.so/accelerateur-transition-ecologique-ademe/R-gressions-d-placement-dans-la-carte-1266523d57d7804ea1eee8deb6bcb424?pvs=4)
- Actuellement lorsqu'on est dans une zone qui n'a aucun acteur, le dézoom ne se fait pas malgré le fait qu'on affiche des acteurs affiches en dehors de la bbox affiché par Leaflet. 
- l'input adresse est mal stylisé depuis qu'on a supprimé le bouton rechercher 
=> fix bbox still being set when equal None

.env.template, dags/cma.py, dags/config/db_mapping.json, dags/utils/dag_eo_utils.py, dags/utils/mapping_utils.py, dags_unit_tests/dags/utils/test_dag_eo_utils.py
Le DAG de la CMA ne fonctionne plus depuis une optimisation lors de la récupération de des acteurs en base de données
- …
=> Correction du dag CMA

dags/utils/dag_eo_utils.py, dags/utils/db_tasks.py, dags/utils/eo_operators.py, dags/utils/mapping_utils.py, dags_unit_tests/dags/utils/test_dag_eo_utils.py, dags_unit_tests/dags/utils/test_mapping_utils.py
Au lieu, de récupérer les objets dans des dataframes, transformer dès que possible en dict de (code -> id).
Modifications effectuées sur les objets:
- source
- acteur type
- acteur service
- action
- sous_categorie
- …
=> Simplification, ne pas stocker des dataframes quand ce n'est pas nécessaire

qfdmd/management/commands/import_data_ademe.py
Carte Notion : [[AST-0] 4-Synchro LVAO > Koumoul / data.ademe (admin dans Django)](https://www.notion.so/accelerateur-transition-ecologique-ademe/AST-0-4-Synchro-LVAO-Koumoul-data-ademe-admin-dans-Django-1216523d57d78031bab1d1e1bdf2b091?pvs=4)
Les double quotes dans un f-string double-quoté ne passe pas sur scalingo :)
- …
=> Fix d'un problème de guillemet dans la commande d'import des data QFDMD

jinja2/qfdmo/_address_card_partials/address_actions.html, jinja2/qfdmo/acteur/tabs/_service_tag.html, jinja2/qfdmo/partials/action_list_by_direction.html, qfdmo/models/action.py, qfdmo/views/adresses.py, qfdmo/views/configurator.py, templates/forms/widgets/groupe_action_label.html
Le déploiement est en carafe, je ne comprends pas pourquoi c'est passé hors radar. 
En plus de ça : on gère mal les couleurs de la légende dans le configurateur, je propose de renommer `border` et `background` en `primary` et `secondary` car sinon on se retrouve à utiliser la couleur `border` en `background` ce qui me semble assez fouillis. 
=> Problèmes de déploiement - f-string unmatched 

qfdmo/forms.py
Suite au merge du configurateur multi epci (#1010), on a des problèmes à l'initialisation de l'application dûs à des appels à un API externe qui sont déclenchés accidentellement
Ceci corrige cela. 
=> Prevent API calls in Configurator's EPCI field choices

qfdmo/forms.py
https://www.notion.so/accelerateur-transition-ecologique-ademe/Configurateur-Pouvoir-le-param-trer-avec-plusieurs-codes-EPCI-1226523d57d780cfa6f1cbd9c5ddf70b?pvs=4
Les groupes d'actions devraient être ordonnés comme sur la légende 
- Aller sur `/configurator` 
- Vérifier que l'ordre des groupes d'action est le même que sur `/?carte`
=> Réorganisation des groupes d'action dans le configurateur 

templates/forms/widgets/autocomplete.html, templates/forms/widgets/generic_autocomplete.html
Empêcher dashlane, l'autocomplete, l'auto correcteur etc de venir en travers de l'utilisateur lors de la saisie d'une adresse ou un objet 
https://www.notion.so/accelerateur-transition-ecologique-ademe/Carte-Champ-Adresse-Enlever-l-affichage-de-la-pr-saisie-navigateur-1376523d57d780a3b2c4db0a4cd5b267?pvs=4
Sources : 
- https://stackoverflow.com/a/69190988 
- https://dashlane.github.io/SAWF/
- …
=> Désactiver l'autocomplétion sur les champs adresse et objet

integration_tests/qfdmo/test_adresses_view.py, jinja2/qfdmo/shared/disclaimers/adresse_missing.html, jinja2/qfdmo/shared/results.html
L'utilisation d'un code EPCI ne masque pas le visuel d'accueil de la carte. 
**Se produit en prod**
- aller sur http://localhost:8000/carte?action_list=reparer%7Cdonner%7Cechanger%7Cpreter%7Cemprunter%7Clouer%7Cmettreenlocation%7Cacheter%7Crevendre&epci_codes=200055887&limit=50 
- on doit voir des acteurs sur la carte
=> Les acteurs d'un code EPCI ne s'affichent pas lorsqu'il est configuré 

.github/workflows/run_tests.yml, playwright.config.ts
**Tentative d'accélérer les tests e2e**
J'en avais un peu marre (comme Nico) du temps de run des e2e. 
**Plusieurs choses :**
- **Utilisation du [sharding](https://playwright.dev/docs/test-sharding)** de Playwright pour répartir les tests dans plusieurs process
- **Suppression de cibles de navigateurs** dans les tests playwright. Sur la base de https://gs.statcounter.com, on peut facilement considérer chromium desktop et safari mobile. Edge est basé sur webkit (et donc chrome), safari macOS est assez peu utilisé, et firefox...j'ai envie de pleurer, mais est bien bien bas, au même niveau que Samsung internet 🥲 
- **Utilisation de `matrix`** pour lancer les tests sur plusieurs runners 
- ~~Ajout de cache sur l'installation des dépendances …
=> Attempt to speed up e2e tests

dags/utils/mapping_utils.py
Vu avec Christian, les numeros type boite vocal à 5 chiffres existent pour nos partenaires
- …
=> Permettre les numéros de téléphone de 5 digits

.github/workflows/sync_databases.yml, qfdmo/management/commands/reinitialize_dagrun.py
On en a eu besoin car parfois l'intégration des DAG bloque et empèche les dagrun suivant de s'executer.
De plus, c'est utile pour ne pas avoir les dagrun qui ont été joué en prod sur la preprod.
Attention cela implique que la table dagrun sera vidé tous les week-end en preprod.
- …
=> Commande pour ré-initialiser les tables dagrun et dagrunchange

core/admin.py, qfdmd/admin.py, qfdmo/admin/acteur.py
https://www.notion.so/accelerateur-transition-ecologique-ademe/AST-0-Support-des-recherches-non-accentu-es-dans-Django-Admin-1526523d57d780daa394e9dc77981a3f?pvs=4
Ajout de la gestion des accents dans la recherche django admin : ils sont désormais ignorés 
- Faire une recherche sans accent, par exemple `Derap` http://localhost:8000/admin/qfdmo/revisionacteur/?q=derapa 
- Vérifier que des résultats comportant des accents ressortent, comme `Déparage`
- Comparer avec la prod https://lvao.ademe.fr/admin/qfdmo/revisionacteur/?q=derapa - ces résultats sont sensés être absents
=> Ignorer les accents dans les recherches dans Django admin

integration_tests/qfdmo/test_acteur_detail.py, qfdmo/models/acteur.py, qfdmo/urls.py, qfdmo/views/adresses.py, static/to_compile/js/map_controller.ts, static/to_compile/js/search_solution_form_controller.ts, static/to_compile/js/solution_map.ts, static/to_compile/js/types.ts, unit_tests/qfdmo/test_acteur.py
Pour anonymiser les fiches détaillées des acteurs
Résoud le pb : https://sentry.incubateur.net/organizations/betagouv/issues/132123/?project=115&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0
Vu avec @fabienheureux : ce serait mieux de créer un slug mais on se garde ça pour plus tard lors du retravail de la fiche detail de l'adresse
- …
=> Utiliser le uuid à la place de l'identifiant_unique dans l'url détail de l'adresse

jinja2/qfdmo/shared/main.html
https://www.notion.so/accelerateur-transition-ecologique-ademe/Posthog-Mesure-des-interactions-de-la-carte-0-depuis-20-novembre-14b6523d57d780fdb3cdc1da565a32f8?pvs=4
Lors du passage la nouvelle fiche détaillée, un event listener Stimulus écoutait un événement envoyé par le controller de la map alors qu'il était désormais envoyé par `search-form-controller`, ça avait pour conséquence de ne pas envoyer les événements d'ouverture de fiche détaillée à Posthog 
Note : devrait être couvert par des tests e2e, à voir en 2025 :) 
- cliquer sur un point de la carte, sur http://localhost:8000/carte?epci_codes=200043123 par exemple
- vérifier que ça envoie bien un événement à posthog
=> Correctif évitant de ne plus avoir d'événement posthog au clic sur la carte 

jinja2/qfdmo/carte/_digital_results.html, static/to_compile/js/search_solution_form_controller.ts
Régression, oublie d'utiliser le uuid pour afficher les acteurs digitaux, la fonction n'étant pas la même que pour les acteurs sur la carte
- …
=> Utiliser le UUID pour affiche le détails des acteurs digitaux

dags/sources/tasks/business_logic/source_data_normalize.py, dags_unit_tests/sources/tasks/business_logic/test_source_data_normalize.py
Carte Notion : [Importer les données EMPAP / OCAPEM / Citeo ](https://www.notion.so/accelerateur-transition-ecologique-ademe/Importer-les-donn-es-EMPAP-OCAPEM-Citeo-1306523d57d7804c9e0cd1a52b19269f?pvs=4)
Ne pas supprimer la colonne origin si c'est a même que la destination sinon, on n'a plus la colonne, c'est balo
- …
=> Correction des transformations quand la colonne origin et destination est la même

core/constants.py, integration_tests/qfdmo/test_acteur_detail.py, jinja2/qfdmo/acteur.html, qfdmo/forms.py
Corrige 
- https://www.notion.so/accelerateur-transition-ecologique-ademe/Homog-n-isation-des-intitul-s-de-la-modale-FILTRES-1506523d57d7804bad3ed987617c1c3a?pvs=4 
- https://www.notion.so/accelerateur-transition-ecologique-ademe/Capitalisation-du-nom-de-l-acteur-1526523d57d780d089e8cb661d131fb0?pvs=4
Homogénéisation des labels concernant le bonus réparation 
Correction des titres pour afficher le premier mot de chaque acteur en majuscule 
- aller voir un acteur avec plusieurs mots dans son nom
- Vérifier que chaque première lettre de chaque mot est en majuscule 
Ouvrir les filtres avancés de la carte 
Vérifier que le filtre bonus réparation est iso avec le screenshot ci dessous
=> Homogeneisation intitules

dags/clustering/dags/clustering_acteur.py, dags/clustering/tasks/airflow_logic/clustering_config_validate_task.py, dags/clustering/tasks/airflow_logic/clustering_db_data_read_acteurs_task.py, dags/clustering/tasks/business_logic/clustering_config_validate.py, dags/clustering/tasks/business_logic/clustering_db_data_read_acteurs.py, dags/utils/airflow_params.py, dags_unit_tests/clustering/tasks/business_logic/test_clustering_config_validate.py, dags_unit_tests/clustering/tasks/business_logic/test_clustering_db_data_read_acteurs.py, dags_unit_tests/utils/test_airflow_params_dropdown.py
Carte Notion : [CLUSTERING: création du DAG airflow pour générer les suggestions](https://www.notion.so/accelerateur-transition-ecologique-ademe/CLUSTERING-cr-ation-du-DAG-airflow-pour-g-n-rer-les-suggestions-15e6523d57d780a89d89d7da6cd1dfed)
**:green_circle: cette PR ne fait que de la lecture/affichage pour permettre à @chrischarousset de commencer à jouter avec la UI Airflow. 0 risque de casser quoi ce ce soit :green_circle:**
- **:bulb: quoi**: un `DAG` pour offrir une UI de paramètres et sélectionner/afficher les acteurs 
- **:dart: pourquoi**: permettre au métier de commencer à jouer avec la sélection
- **:thinking: comment**: voir instructions ci-dessous
_* car on a besoin de merger celle-ci pour que @chrischarousset puisse l'utiliser_
- tâche airflow associée: …
=> :rocket: CLUSTERING: DAG airflow - Sélection des acteurs

dags/sources/config/db_mapping.json
Carte Notion : [Importer le fichier v2 Citeo (incl. Fibreux)](https://www.notion.so/accelerateur-transition-ecologique-ademe/Importer-le-fichier-v2-Citeo-incl-Fibreux-1666523d57d780d1b16cffea591c3a0d?pvs=4)
Mini PR qui consiste uniquement à ajouter des produits possibles de la source CITEO dans la table de mapping des produits
-> On pourrait réfechir à rendre administrable ce mapping de produit 🤔 
- …
=> Mise à jour du mapping produit pour CITEO

qfdmd/models.py
Une 500 se produit en preprod lorsqu'une description pour une produit en mauvais état n'est pas renseignée. 
On a modifié la manière dont on récupère cette valeur récemment et du coup on a besoin d'échouer silencieusement lorsqu'on accède à la valeur bon état / mauvais état calculée, en effet on suit désormais la logique suivante :
- On tente d'accéder à la valeur sur le **synonyme**, si elle est définie on l'affiche
- On tente d'accéder à la valeur sur le **produit**, si elle est définie on l'affiche 
- On tente d'accéder à la **valeur calculée** depuis le champ description, séparé sur le tag `<b>Bon état</b>` et `<b>Mauvais état</b>`
À noter : cette approche sera dépréciée lorsque toutes les fiches produits seront contribuées. 
Les trucs à faire avant de …
=> Gestion d'une erreur en cas de description mauvais état non renseignée

Makefile
2 commandes:
- run-all : lance airflow et l'interface
- db-restore : télécharge la base de prod, la restaure en local et joue les migrations
- …
=> Ajout des commandes run-all et db-restore dans le makefile

static/to_compile/js/controllers/assistant/analytics.ts, templates/components/search/_search_result.html
Deux pour le prix d'un 
- [Correctifs sur le calcul du score PostHog](https://www.notion.so/accelerateur-transition-ecologique-ademe/AST-1-Mise-en-place-du-tracking-nouvelle-archi-assistant-sur-Posthog-et-Matomo-1266523d57d780399115d465f94dfa88?pvs=4)
- Fusion de deux événements `$set` en un seul pour alléger le billing PostHog
- Suppression d'un `target="_top"` remplacé par un `"_self"` pour éviter que le clic sur un résultat de recherche fasse sortir de l'iframe 
- Aller sur /dechet
- Vérifier dans [PostHog](https://eu.posthog.com/project/43401/activity/explore#q=%7B%22kind%22%3A%22DataTableNode%22%2C%22full%22%3Atrue%2C%22source%22%3A%7B%22kind%22%3A%22EventsQuery%22%2C%22select%22%3A%5B%22*%22%2C%22event%22%2C%22 …
=> Mise à jour calcul posthog + correctif iframe

core/context_processors.py, templates/components/sidebar/sidebar.html
https://www.notion.so/accelerateur-transition-ecologique-ademe/masquer-le-bouton-nous-contacter-en-mode-iframe-1596523d57d780fca8fbfe37ea64b878?pvs=4
Tout est dans le titre :) 
- Ajout d'une variable basée sur la requête dans le context processor 
- Suppression dans le dom du bouton 
- Charger `/dechet/?iframe`
- Vérifier que le bouton du formulaire de contact est absent
=> Masquer le bouton formulaire de contact en mode iframe 

Makefile
Mini correction car la commande db-restore ne fonctionne pas à cause d'un espace à la fin de DB_URL
- …
=> Correction de la commande make db-restore

qfdmd/models.py
Cf https://www.notion.so/accelerateur-transition-ecologique-ademe/Si-mauvais-tat-bon-tat-la-carte-n-est-pas-filtr-e-sur-la-typologie-d-objet-17b6523d57d7800e94d7c701b33e33ab?pvs=4 
Permet de passer la sous catégorie à la vue adresse 
Note : un refacto de cette vue est prévue prochainement qui permettra de passer plus proprement ces ids de catégorie 
=> Ajout de la sous catégorie d'objet aux paramètres d'url de la carte

qfdmo/admin/acteur.py
Dans l'admin / revision_acteur, quand on visualise un parent si un enfant à les caractères "_40" dans l'url, alors ils sont intérprétés et le lien est cassé, il manquait un `quote` du paramètre `identifiant_unique` comportement copié de django lui-même. cf. https://github.com/django/django/blob/6cfe00ee438111af38f1e414bd01976e23b39715/django/contrib/admin/models.py#L243
- …
=> Correction des liens affichés dans les Inline de l'administration

dags/cluster/dags/cluster_acteurs_suggestions.py, dags/cluster/tasks/airflow_logic/cluster_acteurs_config_validate_task.py, dags/cluster/tasks/airflow_logic/cluster_acteurs_db_data_read_acteurs_task.py, dags/cluster/tasks/airflow_logic/cluster_acteurs_normalize_task.py, dags/cluster/tasks/airflow_logic/cluster_acteurs_suggestions_task.py, dags/cluster/tasks/business_logic/cluster_acteurs_db_data_read_acteurs.py, dags/cluster/tasks/business_logic/cluster_acteurs_df_sort.py, dags/cluster/tasks/business_logic/cluster_acteurs_suggestions.py, dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_df_sort.py
Carte Notion : [CLUSTERING - DAG airflow - Scénarios de validation](https://www.notion.so/accelerateur-transition-ecologique-ademe/CLUSTERING-DAG-airflow-Sc-narios-de-validation-1766523d57d7801782abe91f09626b41)
- **:bulb: quoi**: bug fixes + amélioration infos Airflow
- **:dart: pourquoi**: permettre à @chrischarousset d'utiliser et mieux comprendre la pipeline
- **:thinking: comment**: 
- `bug fix exclusion clusters`: `df.empty` -> `if len(df) < 2:` , on ignore les clusters de taille inférieur à 2
- `bug fix debug`: j'avais ajouté + de debug à la fonction `cluster_acteurs_suggestions`: j'ai tout commenté, on garde le debug au fur et à mesure de la logique de clustering.
- Je vais créer une fonction/tâche séparée dans Airflow pour comprendre pourquoi certains acteurs ne sont pas …
=> :hammer: Clustering: bux fixes et amélioration logs Airflow

dags/compute_acteurs/dags/create_final_actors.py, dags/compute_acteurs/tasks/airflow_logic/__init__.py, dags/compute_acteurs/tasks/airflow_logic/compute_acteur_services_task.py, dags/compute_acteurs/tasks/airflow_logic/compute_acteur_task.py, dags/compute_acteurs/tasks/airflow_logic/compute_labels_task.py, dags/compute_acteurs/tasks/airflow_logic/db_data_write_task.py, dags/compute_acteurs/tasks/airflow_logic/deduplicate_acteur_services_task.py, dags/compute_acteurs/tasks/airflow_logic/deduplicate_acteur_sources_task.py, dags/compute_acteurs/tasks/airflow_logic/deduplicate_labels_task.py, dags/compute_acteurs/tasks/airflow_logic/deduplicate_propositionservices_task.py, dags/compute_acteurs/tasks/business_logic/__init__.py, dags/compute_acteurs/tasks/business_logic/compute_acteur.py, dags/compute_acteurs/tasks/business_logic/compute_acteur_services.py, dags/compute_acteurs/tasks/business_logic/compute_labels.py, dags/compute_acteurs/tasks/business_logic/deduplicate_acteur_services.py, dags/compute_acteurs/tasks/business_logic/deduplicate_labels.py, dags/compute_acteurs/tasks/business_logic/deduplicate_propositionservices.py, dags_unit_tests/compute_acteurs/business_logic/test_apply_correction_acteur.py, dags_unit_tests/compute_acteurs/business_logic/test_merge_acteur_services.py, dags_unit_tests/compute_acteurs/business_logic/test_merge_labels.py
Carte Notion : [[Airflow] Résoudre les Fails des sous-tâches du DAG de synchro vers DisplayedActeurs](https://www.notion.so/accelerateur-transition-ecologique-ademe/Airflow-R-soudre-les-Fails-des-sous-t-ches-du-DAG-de-synchro-vers-DisplayedActeurs-1826523d57d780f38e0cd8a8f0c65c51?pvs=4)
En attendant une résolution en profondeur, cette PR fait en sorte d'executer les taches de déduplications les unes après les autres pour éviter que le scheduler ne tombe
On en profite pour unifier les noms des tâches de ce DAG
- …
=> taches de déduplication en ligne et renommage des taches

airflow-scheduler.Dockerfile
Pourquoi ?
On a une erreur sur le cluster Airflow qui n'arrive pas à charger l'application data de django en preprod
Comment ?
Copie de l'application `data` dans le docker `airflow-scheduler`
- …
=> Ajout de l'application data dans le docker AIRFLOW - Scheduler

qfdmo/management/commands/delete_parents_without_children.py, qfdmo/migrations/0112_delete_parents_without_children.py, qfdmo/migrations/0113_delete_parents_without_children.py, qfdmo/models/acteur.py, unit_tests/qfdmo/test_acteur.py
Carte Notion : [Un parent dont l’enfant est SUPPRIMÉ ne devrait plus apparaître sur la carte](https://www.notion.so/accelerateur-transition-ecologique-ademe/Un-parent-dont-l-enfant-est-SUPPRIM-ne-devrait-plus-appara-tre-sur-la-carte-1816523d57d7807d9489f9b4b12c641f?pvs=4)
Contient : 
- …
=> Parent without children

README.md, docs/reference/902-utilisation-du-francais-et-de-l-anglais.md, docs/reference/README.md
Juste déplacer la documentation, ajouter le cas du message des exception
J'ai tester de faire cette PR à partir de l'interface github :)
- …
=> Déplacement de la documentation relative à l'utilisation du français et de l'anglais

dags/compute_acteurs/tasks/business_logic/compute_acteur.py, dags/compute_acteurs/tasks/business_logic/db_data_write.py, dags/compute_acteurs/tasks/business_logic/deduplicate_propositionservices.py, dags_unit_tests/compute_acteurs/business_logic/test_apply_correction_acteur.py
Carte Notion : [⚠️Des fiches-acteurs INACTIF (ou Clusterisés) sont indexés sur Google](https://www.notion.so/accelerateur-transition-ecologique-ademe/Des-fiches-acteurs-INACTIF-ou-Clusteris-s-sont-index-s-sur-Google-1516523d57d78022bd99cb9fc0e06ce4?pvs=4)
Lors du calcul des acteurs à afficher, on ne prend que les acteurs actifs
Ainsi les acteurs supprimé ou inactif n'ont plus de fiches, elle ne seront pas disponible pour l'indexation
Les enfants inactif ne participent plus à l'affichage de leur parent
Filtrer les acteurs non actif
Filtrer les models liés au acteur non actif
Filtrer les parents sans acteurs actif avant d'enregistrer dans displayedacteur
- …
=> Ne pas prendre en compte les acteurs non actif dans displayedacteur

dags/sources/dags/source_sinoe.py, dags/sources/tasks/business_logic/source_data_normalize.py
Pourquoi ?
le DAG SINOE finit en erreur car l'année 2024 n'est plus disponible et a été remplacé par l'année 2025
Comment ?
Remplacement de 2024 par 2025
- …
=> Correction du DAG SINOE, l'année à observé est maintenant 2025

requirements.txt
This reverts commit 9050b2a747902a6747255dc328335247fe268d62.
Quoi : Retrouver des logs sur le cluster Airflow
Pourquoi : On a pas de log sur le cluster Airflow
Comment : revert de boto3, cf. [fix: MissingContentLength in boto3 version 1.36.1 boto/boto3#4398](https://github.com/boto/boto3/issues/4398)
- …
=> Revert "Bump boto3 from 1.35.98 to 1.36.7 (#1278)"

.secrets.baseline, core/airflow_settings.py, dags/tools/dags/airflow_logs.py, dags/utils/django.py, docker-compose.yml
Carte Notion : [[Airflow] Impossible d’écrire les logs sur S3 - execution aveugle](https://www.notion.so/accelerateur-transition-ecologique-ademe/Airflow-Impossible-d-crire-les-logs-sur-S3-execution-aveugle-1866523d57d780c6947cd64089cb1b69?pvs=4)
* Désactivation du logging de Django quand l'application django est utilisé par la plateforme DATA
* Ajout d'un DAG de controle de type `dev tools`
- …
=> Résolution du problème de logs Airflow introuveable sur le stockage s3

core/settings.py, qfdmd/views.py
**Quoi** on s'assure que les vues de l'assistant ne sont visible que pour un domaine choisi 
**Pourquoi** : éviter par exemple que https://lvao.ademe.fr/dechet/chaussons ne soit utilisable à la place de https://quefairedemesdechets.ademe.fr
**Comment** lorsque la requête vers une vue de l'assistant ne provient pas d'un domaine connu, on redirige vers la home du projet.  
On applique cela à la classe parente de toutes les vues de l'assistant
=> Forcer le domaine des vues de l'assistant

templates/qfdmd/cmspage_detail.html
Il manquait une accolade dans un tmplate qui provoquait une erreur 500
cf. https://sentry.incubateur.net/organizations/betagouv/issues/146001/?alert_rule_id=74&alert_timestamp=1738177597651&alert_type=email&environment=production&notification_uuid=182c32d3-4c39-467f-8b3a-c42669c78f52&project=115&referrer=alert_email
- …
=> Typo provoquant une erreur 500 sur les pages légales

.github/workflows/cd_preprod.yml, .github/workflows/cd_prod.yml
Tout est dans le titre, c'est pour réduire le bruit car quand on a poussé des version à la main sur les environnements clevercloud, alors les mise en (pre)prod plante
Ici, on force e push to (pre)prod pour etre plus robuste
- …
=> forcer la mise en preprod et prod sur clevercloud

package.json, qfdmd/urls.py, qfdmd/views.py, static/to_compile/entrypoints/qfdmd.ts, static/to_compile/entrypoints/sw.ts
**Quoi** : forcer la désactivation des service workers tournant sur les machines des visiteurs récurrents pour le domaine quefairedemesdechets.ademe.fr
**Pourquoi** : On hérite d'un service worker dans quefairedemesdechets.ademe.fr qui est présent sur /sw.js.
Il semblerait que son absence dans la nouvelle version de l'assistant empêche sa mise à jour qui a normalement lieu toutes les 24 heures, cf https://answers.netlify.com/t/support-guide-understanding-unregistering-service-workers/145
**Comment** : le navigateur via gatbsy a pu enregistrer un service worker à l'url sur le chemin `/sw.js`. 
On charge donc un nouveau fichier .js qui permet de remplacer l'existant, normalement rafraichi par le navigateur au bout de 24h
**⚠️ tests** : j'ai déployé ce code en prod directement car c'est le …
=> Désactiver les services workers hérités de gatsby

docker-compose.yml
Carte Notion : [[Airflow] Exposer la DB interne Airflow docker localement](https://www.notion.so/accelerateur-transition-ecologique-ademe/Airflow-Exposer-la-DB-interne-Airflow-docker-localement-18b6523d57d780b48c37e81b2dae6df1?pvs=4)
- **:bulb: quoi**: exposer la DB airflow docker en local
- **:dart: pourquoi**:  pouvoir intéroger et mieux comprendre le comportement airflow
- **:thinking: comment**: en modifiant `docker-compose.yml` et en exposant/mappant les ports (on utilise `7654` car `6543` est déjà utilisé pour exposer la DB produit)
Pour voir si les `xcom` explosent
```
SELECT dag_id,
SUM(length(value))/COUNT(DISTINCT run_id)/1048576 AS avg_run_xcom_size_mb
FROM xcom
WHERE run_id IS NOT NULL
GROUP BY dag_id;
```
=> :eye: Airflow: expose DB docker

qfdmo/urls.py
Mauvais copier coller...je pense que le code est clair :  
**Quoi :** on charge le script iframe.js lorsqu'on atteint la route /static/iframe.js
**Pourquoi :** parce qu'il faut pas exagérer non plus 😄 
**Comment :** on charge la bonne vue dans le routeur django 
**En bonus :** on utilise des nom d'urls uniques pour éviter les conflits
=> Le formulaire épargnons ne charge pas le bon script

dags/compute_acteurs/tasks/business_logic/compute_acteur.py
Le rafraichissement des acteurs affichés est cassé à cause des parents qui n'ont que des enfants non actifs
- …
=> Filtrer les parents qui n'ont pas d'enfants actifs

dags/compute_acteurs/dags/create_final_actors.py
- Ne pas permettre de lancer le DAG create_display_actor plusieurs fois en parallèle
- Résoudre une dépendance entre tâches
- …
=> Amélioration du DAG de calcule des acteurs à afficher

qfdmo/views/adresses.py, unit_tests/qfdmo/test_adresse_get_object_list.py
But : éviter une erreur Sentry
Sentry : https://sentry.incubateur.net/organizations/betagouv/issues/149376/?alert_rule_id=74&alert_timestamp=1739284583204&alert_type=email&environment=production&notification_uuid=398e226e-9cc5-4a63-9b81-021aac5108b0&project=115&referrer=alert_email
- …
=> Si il n'y a pas de query lors de l'appel à get_objet_list alors on retourne une liste vide d'objet

qfdmo/models/acteur.py, unit_tests/qfdmo/test_acteur.py
Pb remonté par Christian dans le fichier de récap des problèmes rencontrés ces derniers jours
**🗺️ contexte**: Gestion des acteurs "parent" dans l'admin django
**💡 quoi**: Impossible de créer un parent pour un (revision)acteur qui a une action principale définie
**🎯 pourquoi**: Pb de clone des champs relationnels, la fonction `model_to_dict` retourne un id pour l'objet action_principale
**🤔 comment**:
- ne pas extraire action_principal dans la fonction model_to_dict et assigner cette valeur à partir de l'objet cloné
- ajout de tests plus exhaustif
=> Permettre de créer un parent même quand une action principale est définie

.env.template, core/settings.py
Carte Notion/Mattermost/Sentry : [Les opérations sur les suggestions génèrent des erreurs serveur](https://www.notion.so/accelerateur-transition-ecologique-ademe/Les-op-rations-sur-les-suggestions-g-n-rent-des-erreurs-serveur-1926523d57d7809ea214cf53ef8f8ec1?pvs=4)
**💡 quoi**: Augmenté le nombre de suggestion selectionnable
**🎯 pourquoi**: Defaut de Django est trop faible pour les opérations de gestion de data
**🤔 comment**: Modification de la valeur DATA_UPLOAD_MAX_NUMBER_FIELDS à 10000
=> Augmenter ne nombre de valeurs accepté dans la requête 1000 -> 10000

qfdmo/management/commands/enrich_revisionpropositionservice.py
Carte Notion/Mattermost/Sentry : [MÀJ de Propositions de service ne sont pas prise en compte dès que l’acteur a été Corrigé - mais devraient l’être](https://www.notion.so/accelerateur-transition-ecologique-ademe/M-J-de-Propositions-de-service-ne-sont-pas-prise-en-compte-d-s-que-l-acteur-a-t-Corrig-mais-dev-19d6523d57d78081b342c3835e364005?pvs=4)
**🗺️ contexte**: Script (command django)
**💡 quoi**: Rattrapage des propositions de service
Dès lors qu'une source avait une révision, lors de l'ingestion d'une nouvelle version, les nouvelle propositions de services n'ont pas été prise en compte car les propositions de service de la révision supplante celle de la source
Création d'un script qui va ajouter les propositions de services qui existe sur l'acteur mais …
=> script de ratrappage par source des propositions de service

dags/sources/dags/source_aliapur.py, dags/sources/dags/source_citeo.py, dags/sources/dags/source_cma.py, dags/sources/dags/source_corepile.py, dags/sources/dags/source_cyclevia.py, dags/sources/dags/source_ecodds.py, dags/sources/dags/source_ecologic.py, dags/sources/dags/source_ecomaison.py, dags/sources/dags/source_ecopae.py, dags/sources/dags/source_ecosystem.py, dags/sources/dags/source_ocab.py, dags/sources/dags/source_ocad3e.py, dags/sources/dags/source_pyreo.py, dags/sources/dags/source_refashion.py, dags/sources/dags/source_screlec.py, dags/sources/dags/source_sinoe.py, dags/sources/dags/source_soren.py, dags/sources/dags/source_valdelia.py, dags/sources/tasks/airflow_logic/config_management.py, dags/sources/tasks/business_logic/source_data_normalize.py, dags/sources/tasks/transform/transform_df.py, dags_unit_tests/sources/tasks/airflow_logic/test_config_management.py, dags_unit_tests/sources/tasks/business_logic/test_source_data_normalize.py, dags_unit_tests/sources/tasks/transform/test_transform_df.py
Carte Notion/Mattermost/Sentry : [[EOs] ignore_duplicate devrait être merge_duplicate ?](https://www.notion.so/accelerateur-transition-ecologique-ademe/EOs-ignore_duplicate-devrait-tre-merge_duplicate-1926523d57d7800087a3ccbd8b18d522?pvs=4)
**🗺️ contexte**: Ingestion de source via airflow
**💡 quoi**: Fusionner les duplicat en gardant les labels, acteur_services et proposition_services de toutes les versions de l'acteur dans le fichier source
**🎯 pourquoi**: ECODDS envoie une ligne par couple acteur/filiaire, il est aussi possible qu'il y ait plusieur ligne si un acteur répare un type d'objet et trie un autre type
- Merge des duplicats -> prendre le premier enregistrement pour chaque champ (excepté pour les objets liés)
- Labels et acteur_services -> on cumule et déduplique …
=> Fusionner les duplicats des sources

qfdmo/admin/acteur.py
Suite de la PR #1349
Sentry : https://sentry.incubateur.net/organizations/betagouv/issues/151409/?alert_rule_id=74&alert_timestamp=1740024262374&alert_type=email&environment=staging&notification_uuid=5dea7311-6cea-4471-a023-97040683674e&project=115&referrer=alert_email
**🗺️ contexte**: django admin
**💡 quoi**: le lien dupliqué est cassé
**🎯 pourquoi**: un reverse en trop
**🤔 comment**: suppression du reverse
=> Suppression d'un reverse en trop

dags/cluster/tasks/business_logic/cluster_acteurs_suggestions/contexte.py, dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_suggestions_contexte_generate.py
Carte Notion: [🔇CLUSTERING: exclure les enfants existants du contexte](https://www.notion.so/accelerateur-transition-ecologique-ademe/CLUSTERING-exclure-les-enfants-existants-du-contexte-1a06523d57d780d2a4bcf4d338d1e683)
**🗺️ contexte**: clustering des acteurs
**💡 quoi**: exclure les enfants existants du contexte
**🎯 pourquoi**: ils peuvent créer des **false-positives** au niveau des checks de suggestions parce que:
- on vérifie que toutes les données des champs `cluster_fields_exact` sont identiques
- or les enfants peuvent diverger puisque rattachés tels-quels (on a pas encore fait [CLUSTERING & DEDUP: re-clusteriser les enfants existants](https://www.notion.so/accelerateur-transition-ecologique-ademe/CLUSTERING-DEDUP-re-clusteriser-les-enfants-existants-1956523d57d7801abe3bc132ec7e33b0) …
=> 🔇CLUSTERING: exclure les enfants existants du contexte

qfdmd/admin.py
[Améliorer la liste des produits pour les liens ](https://www.notion.so/accelerateur-transition-ecologique-ademe/ADMIN-Am-liorer-la-liste-des-produits-pour-les-liens-18f6523d57d78042bf6bcc4ab78f3af4?pvs=4)
**🗺️ contexte**:
Amélioration de l'administration django 
**💡 quoi**:
Autocomplétion dans les champs produits 
Pour améliorer la vie de Camille Christian et Delphine :) 
**🤔 comment**:
En utilisant la fonctionnalité [autocomplete fields](https://docs.djangoproject.com/en/5.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.autocomplete_fields) de Django 
=> 🔍 Ajout de champs d'autocomplétion sur les produits / liens et synonymes

templates/components/footer/_standalone.html
Suppression du lien vers l'enquête en bas du footer, tout passe par le formulaire de contact pour le support usager
Carte Notion/Mattermost/Sentry : [Support - Enlever le Tally recherche du footer de l’assistant](https://www.notion.so/accelerateur-transition-ecologique-ademe/Support-Enlever-le-Tally-recherche-du-footer-de-l-assistant-1a16523d57d780bfba1ef5fccb700025?pvs=4)
**💡 quoi**: 
Un seul point de contact pour les usagers : formulaire de contact (via l'enveloppe)
=> Suppression de l'enquête dans le footer

static/to_compile/js/controllers/admin/categorie_widget_controller.ts
[Nouveau combo-select par catégorie dans Django Admin : fonctionne sur le 1er bloc mais pas le 2ème](https://www.notion.so/accelerateur-transition-ecologique-ademe/Nouveau-combo-select-par-cat-gorie-dans-Django-Admin-fonctionne-sur-le-1er-bloc-mais-pas-le-2-me-1526523d57d780cfa94bcd1b81978797?pvs=4)
Administration django
**💡 quoi**: 
Méthode de sélection des sous catégories d'une proposition de service d'un acteur corrigé
**🎯 pourquoi**:
Pour corriger un dysfonctionnement 
**🤔 comment**:
Plutôt que de cibler le `fieldset` parent on s'intéresse à la ligne du tableau. 
En effet, dans django admin on a l'arborescence suivante pour ce type de formulaires : 
```
fieldset
- table 
- - table row
- - - colonne formulaire catégories
- - - colonne formulaire sous catégories
``` …
=> 🔀 Ajouter le comportement de plusieurs sélections de catégories / sous catégories à chaque proposition de service (plutôt que la première)

Makefile, qfdmo/admin/acteur.py
Carte Notion : [[Django Admin] Régression : le menu pour sélectionner un parent propose des enfants](https://www.notion.so/accelerateur-transition-ecologique-ademe/Django-Admin-R-gression-le-menu-pour-s-lectionner-un-parent-propose-des-enfants-1a06523d57d780ee8ad4d29a046700b8?pvs=4)
**💡 quoi**: le selecteur de parent sur RévisionActeur affiche tous les RévisionActeur alors que seul les RévisionActeur qui sont déjà des parents doivent apparaitre
**🎯 pourquoi**: Régression de l'implémentation de l'interdiction de créer ou supprimer le parent à partir du selecteur
- Déplacement de la logique se selection sur l'objet PrantActeurAdmin précédemment …
=> Correction du selecteur parent das l'admin revision acteur

qfdmd/templatetags/qfdmd_tags.py
Carte Mattermost : [hello ! ptit bug sur la prod, la home n'affiche plus les illustrations 🙊](https://mattermost.incubateur.net/betagouv/pl/ymmro5zbiff85cqkogazc57axh)
**🗺️ contexte**: Page d'accueil de QFDMD
**💡 quoi**: Les picto ne s'affichent pas
**🎯 pourquoi**: il y a un `return ""` suspect
- suppression du `return ""`
- gérer si le fichier n'existe pas
=> Les Picto ne s'affichent plus sur la page d'accueil de QFDMO

qfdmo/admin/acteur.py
Carte Notion : [DjangoAdmin : Impossible d’uploader un fichier (import)](https://www.notion.so/accelerateur-transition-ecologique-ademe/DjangoAdmin-Impossible-d-uploader-un-fichier-import-1b16523d57d780258dfdcaf9fa457d94?pvs=4)
**🗺️ contexte**: Django Admin - import
**💡 quoi**: Parfois des lignes avec toutes les valeurs à nulles sont affichées après un import
**🎯 pourquoi**: je suppose que xlsx garde des colonnes nulles dans son format xml et django-import-export ne les ignore pas
**🤔 comment**: ingorer les lignes à importer quand toutes les valeurs sont nulles
=> Parfois les xlsx envoient des lignes vides, elle doivent être ignorées

qfdmd/templatetags/qfdmd_tags.py
Carte Mattermost : [hello ! ptit bug sur la prod, la home n'affiche plus les illustrations 🙊](https://mattermost.incubateur.net/betagouv/pl/ymmro5zbiff85cqkogazc57axh)
**🗺️ contexte**: Page d'accueil de QFDMD
**💡 quoi**: Les picto ne s'affichent pas
**🎯 pourquoi**: le comportement du FileField.stockage est diférent entre un stockage local et un stockage S3 via CleverCloud
- Gestion de l'existance de fichier avec un try except
=> Suite : Les Picto ne s'affichent plus sur la page d'accueil de QFDMO

airflow-scheduler.Dockerfile
**🗺️ contexte**: on a fait une session pair avec @kolok dans laquelle on a fait trop de chose en même temps (revue PR, discussion dbt, Django etc...), on a mergé https://github.com/incubateur-ademe/quefairedemesobjets/pull/1427 dans lequel on a pas bien résolu les conflit sur le dockerfile
**💡 quoi**: hotfix sur ce problème:
**🎯 pourquoi**: rendre `airflow-scheduler.Dockerfile` à nouveau fonctionnel
**🤔 comment**:
- je suis **reparti** de [la version](https://github.com/incubateur-ademe/quefairedemesobjets/blob/4a6aa90bf826396a0bc7f4bd6ae576c8a25beac4/airflow-scheduler.Dockerfile) de https://github.com/incubateur-ademe/quefairedemesobjets/pull/1219
- **ajout** de l'install unzip, requise pour https://github.com/incubateur-ademe/quefairedemesobjets/pull/1427
- **suppression** d'un `apt-get …
=> 🚨 hotfix airfow scheduler dockerfile

dbt/macros/table/macro_filtered_propositionservice.sql, dbt/macros/table/macro_propositionservice.sql, dbt/macros/table/macro_propositionservice_sous_categories.sql, dbt/models/exposure/carte/schema.yml, qfdmo/admin/acteur.py
**🗺️ contexte**: DBT
**💡 quoi**: DBT plante en preprod car il n'arrive pas à créer un index
```
Database Error in model marts_carte_propositionservice_sous_categories (models/marts/carte/marts_carte_propositionservice_sous_categories.sql)
could not create unique index "9450cbf251279cdd02bec3eca2da2b31"
DETAIL:  Key (propositionservice_id, souscategorieobjet_id)=(RPS_369655, 107) is duplicated.
CONTEXT:  parallel worker
compiled code at target/run/qfdmo/models/marts/carte/marts_carte_propositionservice_sous_categories.sql
```
**🎯 pourquoi**: mauvaise déduplication après un JOIN
* grouper les propositionservice_sous_categories par propositionservice_id, souscategorieobjet_id pour …
=> Correction de DBT et affichage de proposition de service dans django admin

dags/shared/config/__init__.py, dags/shared/config/catchups.py, dags/shared/config/schedules.py, dags/shared/config/start_dates.py, dags/tools/dags/airflow_cleanup_db.py
Carte Notion/Mattermost/Sentry : [Airflow XCOM: solution durable de nettoyage](https://www.notion.so/accelerateur-transition-ecologique-ademe/Airflow-XCOM-solution-durable-de-nettoyage-1a76523d57d7800aba7be56a495f1a34)
**🗺️ contexte**: on utilise les xcom pour échanger de la donnée (ce qu'on devrait éviter de faire, airflow étant un orchestrateur, pas un compute)
**💡 quoi**: DAG Airflow pour nettoyer la base Airflow
**🎯 pourquoi**: la DB Airflow se remplit et crash périodiquement
**🤔 comment**:
- J'ai repris https://www.astronomer.io/docs/learn/cleanup-dag-tutorial avec très peux de modifs:
- fix de `clean_before_timestamp` qui avait besoin d’un `str`
- renommage à notre sauce
- ajout d'explications en français
- **introduction de `shared/config`**: j'ai une autre PR de stabilisation à …
=> 🧹 DAG Airflow pour nettoyer Airflow

dags/acteurs/dags/compute_acteur_views.py, dags/acteurs/dags/export_opendata.py, dags/clone/dags/clone_ae_annuaire_entreprise.py, dags/cluster/dags/cluster_acteur_suggestions.py, dags/compute_acteurs/dags/create_final_actors.py, dags/crawl/dags/crawl_urls.py, dags/sources/tasks/airflow_logic/operators.py, dags/suggestions/dags/apply_suggestions.py, dags/tools/dags/airflow_logs.py, dags/views/view_acteur_tous.py, dags_unit_tests/e2e/utils.py, data/admin.py
**💡 quoi**: généralisé le la date de début du DAG à hier
**🎯 pourquoi**: Uniformisation du du code
**🤔 comment**: remplacement des date de début arbitrairepar la fonction utilitaire `days_ago`
=> par défaut, le start_date des dag est hier : cela évite les rattrapages inutiles

integration_tests/qfdmo/test_acteur_detail.py, qfdmo/views/adresses.py
Pour faire suite à notre séminaire
- la route `/adresse` redirige vers `/adresse-details` si l'acteur affiché existe
- la route `/adresse` redirige vers `/adresse-details` vers le parent si l'acteur affiché n'existe car il a un parent
- la route `/adresse-details` retourne 404 si l'acteur n'existe pas
- la route `/adresse-details` affiche la fiche acteur sinon
**🗺️ contexte**: fiche acteur detail
**💡 quoi**: Rediriger correctement le cas echéant
**🎯 pourquoi**: perdre le moins de SEO possible
- la route `/adresse` redirige vers `/adresse-details` si l'acteur affiché existe
- la route `/adresse` redirige vers `/adresse-details` vers le parent si l'acteur affiché n'existe car il …
=> Réponse redirect et non trouvé sur les routes adresse et adresse-details

data/models/suggestion.py, templates/data/_partials/contexte_details.html
Carte Notion: [[Clustering - Suggestions] Petites améliorations post v1](https://www.notion.so/accelerateur-transition-ecologique-ademe/Clustering-Suggestions-Petites-am-liorations-post-v1-1a66523d57d780679b48e2084590efb1)
**🗺️ contexte**: on génère des suggestions de changement, par défaut le `<details>` du contexte est toujours fermé
**💡 quoi**: permettre d'ouvrir le `<details>` par défaut pour certaines suggestions
**🎯 pourquoi**: réduire les cliques / faire économiser du temps au métier
**🤔 comment**:
- `templates/data/_partials/contexte_details.html`: ajout du paramètre `details_open`
- `data/models/suggestion.py`: gestion de ce paramètre pour les différents cas d'usage
Avec le changement: ouverture par défaut sur les suggestions de clustering:
=> 📖 Suggestions: ouvrir détails par défaut

poetry.lock, pyproject.toml
Carte Notion/Mattermost/Sentry : [je viens d'avoir la même erreur en préprod (sur de l'import d'acteurs) que j'ai eu hier en prod](https://mattermost.incubateur.net/betagouv/pl/j86k66wuy3f15cq81oca5s5yce)
**🗺️ contexte**: import export
**💡 quoi**: regression à cause de django en 5.1.7 (cf. https://github.com/django/django/pull/19233)
**🎯 pourquoi**: pour que ça marche
**🤔 comment**: edition de pyproject pour fixer en 5.1.6
=> downgrade django pour django-import-export en attendant la 5.2

dags/sources/dags/source_s3.py, dags/sources/tasks/transform/transform_df.py, dags_unit_tests/sources/tasks/transform/test_transform_df.py
Forcer l'idenifiant externe en string
**💡 quoi**: forcer l'id externe en string
**🎯 pourquoi**: eviter les erreurs, permettre une colonne d'entier
**🤔 comment**: caster en str
=> Forcer l'identifiant exterieur en string

dags/sources/config/shared_constants.py, dags/sources/tasks/transform/transform_column.py, dags_unit_tests/sources/tasks/transform/test_transform_column.py
Encore une adaptation
**🗺️ contexte**: Airflow source
**💡 quoi**: public_accueilli et reprise ne sont pas null et sont vide par defaut
**🎯 pourquoi**: simplification du modele de données
**🤔 comment**: mettre la valeur vide par défaut
=> public_accueilli et reprise ne sont pas null par defaut

dags/crawl/config/cohorts.py, dags/crawl/config/tasks.py, dags/crawl/config/xcoms.py, dags/crawl/dags/crawl_urls.py, dags/crawl/tasks/airflow_logic/crawl_urls_check_crawl_task.py, dags/crawl/tasks/airflow_logic/crawl_urls_suggest_crawl_diff_standard_task.py, dags/crawl/tasks/business_logic/crawl_urls_check_crawl.py, dags/crawl/tasks/business_logic/crawl_urls_check_syntax.py, dags_unit_tests/crawl/tasks/business_logic/test_crawl_urls_check_crawl.py, dags_unit_tests/crawl/tasks/business_logic/test_crawl_urls_check_syntax.py
Carte Notion: [Revue des URL cassées dans notre bdd](https://www.notion.so/accelerateur-transition-ecologique-ademe/Revue-des-URL-cass-es-dans-notre-bdd-1bb6523d57d78014a144fc517da8e4cf) de @chrischarousset 
**🗺️ contexte**: @chrischarousset a fait tourné le DAG de crawl, et a identifié des améliorations
**💡 quoi**: divers changements de nettoyage de syntaxe + changement d'1 cohorte
**🎯 pourquoi**: améliorer le taux de correction, réduire les faux positifs
**🤔 comment**:
- **cohorte HTTP -> HTTPS** devient **standard** et regroupe les changements considérés comme normaux et a approuvé avec confiance, à savoir on **tolère les changements de**
- `casse`
- `www`
- `http -> https`
- `/ en fin `
- …
=> 🔗 Crawl URLs: améliorations syntaxe + cohorte "standard"

jinja2/qfdmo/carte/header.html, jinja2/qfdmo/carte/panels/legend.html, static/to_compile/js/iframe.ts
https://www.notion.so/accelerateur-transition-ecologique-ademe/Carte-Supprimer-le-bouton-Infos-A-propos-au-niveau-de-la-carte-quand-dans-l-assistant-15e6523d57d7802485bcfd05eaadeb0d?pvs=4
**🗺️ contexte**: carte dans l'assistant
**💡 quoi**: Masquer le bouton infos dans le cas où l'intégrateur est l'ADEME
**🎯 pourquoi**: Car c'est bizarre dans le "Infos" de parler de la carte, alors qu'on est sur l'assistant. Et c'est déjà le cas dans la version existante.
- ajout d'un sélecteur sur le logo (qu'on supprime déjà) et les éléments à supprimer
- mise à jour du script pour cibler ce sélecteur
=> 🙈 Masquer le bouton infos dans le cas où l'intégrateur est l'ADEME

core/constants.py, core/templatetags/seo_tags.py, qfdmd/views.py, unit_tests/core/test_seo_tags.py
https://www.notion.so/accelerateur-transition-ecologique-ademe/Fiche-acteur-L-acteur-est-mal-renseign-lors-du-partage-1536523d57d7802098c5fc89c42827ea?pvs=4
**🗺️ contexte**: Assistant v2 / partage
**💡 quoi**: l'acteur est mal renseigné lors du partage
**🎯 pourquoi**: car j'ai mutualisé du code sans réfléchir...
**🤔 comment**:
- définition d'un dictionnaire pour la carte et l'assistant permettant de définir un template différent pour l'assistant et la carte
- vérification dans la requête de si on est sur l'assitant ou la carte
- J'en ai profité pour corriger le problème de copie de l'url, et ajouter un test 
=> 🤯 L'acteur est mal renseigné lors du partage

core/api.py, qfdmo/admin/acteur.py, qfdmo/api.py, qfdmo/models/acteur.py
Cf https://www.notion.so/accelerateur-transition-ecologique-ademe/API-J-Agis-Ajout-paternit-et-filtre-objet-15a6523d57d780e48655f56ce0443400?pvs=4 
**🗺️ contexte**: API Rest - J'agis
**💡 quoi**: exposition des sources dans l'API Rest
**🎯 pourquoi**: pour afficher la paternité sur J'agis
- Isolement de la méthode `get_sources` dans un mixin pour la rendre plus facilement exploitable 
- Ajout d'un endpoint listant les sources
- Ajout d'une property récupérant l'url absolue du logo d'une source
- Ajout du champ sources sur le schema acteurs
```sh
Curl
curl -X 'GET' \
'http://localhost:8000/api/qfdmo/sources' \
-H 'accept: application/json'
```
```json
[
{
"logo": "http://localhost:8000/media/logos/Sans_titre_22.jpg",
"id": 92,
"code": "ecodds",
"libelle": "ECODDS",
"url": …
```
=> 🦦 Ajout des sources dans l'API Rest 

jinja2/qfdmo/shared/results.html
https://www.notion.so/accelerateur-transition-ecologique-ademe/Le-bouton-Proposer-une-adresse-appara-t-sous-la-carte-sur-mobile-1a16523d57d780ccbf8bda34e09cd8c7?pvs=4
**🗺️ contexte**: Carte
**💡 quoi**: Le bouton “Proposer une adresse” apparaît sous la carte sur mobile
**🎯 pourquoi**:
- La div étant dans le conteneur leaflet, qui applique des z-index à droite à gauche, le bouton se retrouve recouvert
- on déplace le bouton en dehors du conteneur de la carte, _et voilà_
- pas besoin d'utiliser de z-index a priori
=> 🔍 Afficher le bouton *Proposer une adresse*

dags/clone/config/sql/validation/ae_etablissement/validate_join_acteurs_count_siret.sql, dags/clone/config/sql/validation/ae_etablissement/validate_rows_count.sql, dags/clone/config/sql/validation/ae_unite_legale/validate_join_acteurs_count_siren.sql, dags/clone/config/sql/validation/ae_unite_legale/validate_rows_count.sql, dags/clone/config/sql/validation/ban_adresses/validate_rows_count.sql, dags/clone/config/sql/validation/ban_lieux_dits/validate_rows_count.sql
**🗺️ contexte**: commencé à tester le clonage en PREPROD
**💡 quoi**: relaxation des règles de validation post-import (et avant switch)
**🎯 pourquoi**: trop strictes actuellement, par exemple:
- **la BAN avait > 26M d'adresses**: ils sont fait du nettoyage et en on plus que 25.9M
- **on avait 150K acteurs avec SIRET matchés**: on en a plus que 115K
**🤔 comment**:
- **Compteur les lignes BAN/AE**:  relaxé **d'1 ordre de magnitue** (e.g. 27M -> 26M) car **pas de raison que le volume baisse drastiquement** s'agissant de table de cumul
- **Compteur SIRET chez nous**: relaxé de 1/2 car on a bcp de fluctuations chez nous
Les adresses de la BAN avait >= 26M de lignes avant, et 25.9M maintenant ([voir run](https://app-d3c229bf-be85-4dbd-aca2-c8df1c6166de.cleverapps.io/dags/clone_ban_adresses/grid?d …
=> 📉 CLONAGE: relaxer la validation

dags/clone/config/model.py, dags/clone/dags/clone_ae_etablissement.py, dags/clone/dags/clone_ae_unite_legale.py, dags/clone/dags/clone_ban_adresses.py, dags/clone/dags/clone_ban_lieux_dits.py, dags/clone/tasks/airflow_logic/chain_tasks.py, dags/clone/tasks/airflow_logic/clone_config_create_task.py, dags/shared/tasks/airflow_logic/dbt_command_task.py, dags_unit_tests/clone/test_config_model.py
Carte Notion: [📦 DBT build en fin de DAGs de clonage](https://www.notion.so/accelerateur-transition-ecologique-ademe/DBT-build-en-fin-de-DAGs-de-clonage-1c76523d57d7809d8f17cb0beacba093)
**🗺️ contexte**: [on s'est accordé sur la façon de gérer les builds dbt dans Airflow](https://mattermost.incubateur.net/betagouv/pl/chpefw7bb3gs5mwnmw6ohm3n5a)
**💡 quoi**: intégration `dbt` aux DAG de clonage
**🎯 pourquoi**: rafraichir les modèles dbt dont certains sont compilés
**🤔 comment**:
- `dags/shared/tasks/airflow_logic/dbt_command_task.py`: tâche partagée pour lancer une commande dbt
- `dags/clone/config/model.py` & `dags/clone/dags/clone_*.py`: ajout de `dbt_command`
Bien que la **BAN n'ait pas encore de modèles DBT**, j'ai **déjà intégré dbt à la BAN dans cette PR** car en cas de **modèles …
=> 📦 DBT build en fin de DAGs de clonage

dags/compute_acteurs/tasks/business_logic/compute_acteur.py, dags_unit_tests/compute_acteurs/business_logic/test_compute_acteur.py
Mattermost : [Nom vide pour pas mal de displayed acteur](https://mattermost.incubateur.net/betagouv/pl/w8zeuajritbm7xyyp6ybjeikfr)
**💡 quoi**: certain nom d'acteur sont vides après les avoir corrigé
**🎯 pourquoi**: Les valeurs vide dans la correction de l'acteur écrase les valeur des acteurs importé
**🤔 comment**: remplacer les valeurs vide par NA dans les correction lors avant de mettre à jour les acteurs
=> Résoudre le pb de surdéfinition vide qui écrase les valeur non corrigées

dags/clone/config/model.py, dags/clone/config/tasks.py, dags/clone/dags/clone_ae_etablissement.py, dags/clone/dags/clone_ae_unite_legale.py, dags/clone/dags/clone_ban_adresses.py, dags/clone/dags/clone_ban_lieux_dits.py, dags/clone/tasks/airflow_logic/chain_tasks.py, dags/clone/tasks/airflow_logic/clone_dbt_build.py, dags/clone/tasks/airflow_logic/clone_table_create_task.py, dags/clone/tasks/business_logic/clone_table_create.py, dags_unit_tests/clone/tasks/business_logic/test_clone_table_create.py, dags_unit_tests/clone/test_config_model.py
**🗺️ contexte**:
- **streaming**: dans la PR initiale Annuaire Entreprise (https://github.com/incubateur-ademe/quefairedemesobjets/pull/1408) j'avais testé du streaming, mais ne fonctionnant pas pour AE Etablissement, je l'avais enlevé, entre temps j'ai fait la BAN qui a rendu les DAGs paramètrables (https://github.com/incubateur-ademe/quefairedemesobjets/pull/1451), donc je peux remettre du streaming là où il fonctionne
- **build dbt**: on s'est rendu compte la semaine dernière des gros problèmes de perf DB
**💡 quoi**:
- **streaming**: ré-introduction via un paramètre, tout en streaming sauf AE Etablissement
- **build dbt**: paramètre de config rendant le build optionnel
**🎯 pourquoi**:
- **streaming**: pour éviter de toucher le disque/IO quand c'est pas nécessaire
- **build dbt**: …
=> 👯‍♀️ Cloner: streaming & build dbt optionnel

dags/cluster/dags/cluster_acteur_suggestions.py, dags/cluster/tasks/airflow_logic/cluster_acteurs_suggestions_to_db_task.py, dags/crawl/tasks/airflow_logic/crawl_urls_suggest_crawl_diff_other_task.py, dags/crawl/tasks/airflow_logic/crawl_urls_suggest_crawl_diff_standard_task.py, dags/crawl/tasks/airflow_logic/crawl_urls_suggest_dns_fail_task.py, dags/crawl/tasks/airflow_logic/crawl_urls_suggest_syntax_fail_task.py, dags/crawl/tasks/business_logic/crawl_urls_suggest.py, dags/sources/tasks/business_logic/db_write_type_action_suggestions.py, dags_unit_tests/crawl/tasks/business_logic/test_crawl_urls_suggest.py, data/admin.py, data/models/suggestion.py
Carte Notion/Mattermost/Sentry : [DjangoAdmin : La vue des suggestions/cohortes devient trop polluée](https://www.notion.so/accelerateur-transition-ecologique-ademe/DjangoAdmin-La-vue-des-suggestions-cohortes-devient-trop-pollu-e-1ca6523d57d78004b823d148be62af40?pvs=4)
**💡 quoi**: simplifier le nom des cohortes
**🎯 pourquoi**: elles sont difficilement lisibles
**🤔 comment**: Modification du __str__ de SuggestionCohorte
=> Simplifier le nom des Cohortes

dbt/dbt_project.yml
**🗺️ contexte**: en débuggant dbt (--debug) j'ai constaté qu'on était tracké (dbt semble utiliser https://snowplow.io/ pour ce faire):
```bash
dbt run --debug
08:54:26  Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c61ba704740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c61b8140b60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c61bae94fb0>]}
```
```bash
tcpdump -i any 'tcp[tcpflags] & (tcp-syn|tcp-fin) != 0 and not port 6543 and not port 5432'
10:58:51.768880 wlp5s0 Out IP me > ec2-184-72-188-7.compute-1.amazonaws.com.https: Flags [S], seq 1680824202, win 64240, options [mss 1460,sackOK,TS val 3939850066 ecr 0,nop,wscale …
```
=> 🛑 🕵 dbt: désactiver le tracking

dbt/models/exposure/acteurs/opendata/schema.yml
J'ai oublié de mettre à jour le test du nombre de colonne après avoir ajouté des colonnes au jeu de données opendata
Du coup, le jeux de donnée est à jour mais le DAG airflow fini en erreur
**🗺️ contexte**: Airflow DBT
**💡 quoi**: Test DBT du jeux de données opendata
**🎯 pourquoi**: Oubli du mise à jour du tests après avoir ajouté des colonnes
**🤔 comment**: Modification du nombre de colonne attendu
=> J'ai oublié de mettre à jour le test du nombre de colonne 

static/to_compile/js/iframe.ts
Suit https://www.notion.so/accelerateur-transition-ecologique-ademe/Carte-Supprimer-le-bouton-Infos-A-propos-au-niveau-de-la-carte-quand-dans-l-assistant-15e6523d57d7802485bcfd05eaadeb0d?pvs=4 
**🗺️ contexte**: Assistant v2
**💡 quoi**: bien gérer les personnalisations de la carte pour l'Ademe sur la staging
La carte dispose de certaines personnalisations réservées aux réutilisateurs Ademe (dont on fait partie). 
Ici ce code n'est pas testable en l'état, car il hardcode les URLs, notamment un domaine de preprod qui n'est plus utilisé. 
- on applique une modification sur tous les sous-domaines .ademe.dev
=> 🔗 Hardcoder les hostnames de l'assistant

.github/workflows/release.yml
Cf #1543 
Ajout de la branche `main` dans les cibles de l'action qui ne se déclenche pas 🤔
=> Mise à jour de l'action GitHub de release

dbt/dbt_project.yml
Carte Notion: [⏩ DBT: modèles unlogged / désactiver le WAL](https://www.notion.so/accelerateur-transition-ecologique-ademe/DBT-mod-les-unlogged-d-sactiver-le-WAL-1dc6523d57d780a8bac6cc65949ca4f5)
**🗺️ contexte**: on utilise `dbt` pour compiler de la donnée, par défault le [WAL](https://www.postgresql.org/docs/current/wal-intro.html) de postresql est activé alors qu'on en a **pas besoin pour des modèles recompilés / reconstruit de zero à chaque fois**
**💡 quoi**: rendre les modèles `unlogged`
**🎯 pourquoi**: **désactiver le WAL** et **améliorer les performances**, cf https://www.postgresql.org/docs/current/sql-createtable.html#SQL-CREATETABLE-UNLOGGED
> If specified, the table is created as an unlogged table. Data written to unlogged tables is **⏩ not written to the write-ahead log** (see …
=> ⏩ [PERF] DBT: modèles unlogged / désactiver le WAL

.secrets.baseline, jinja2/layout/base.html, jinja2/qfdmo/carte/header.html, jinja2/qfdmo/carte/panels/legend.html, static/to_compile/entrypoints/qfdmo.css
https://www.notion.so/accelerateur-transition-ecologique-ademe/Masquer-toute-la-l-gende-pour-Cyclevia-1dd6523d57d7802bbbd0d0a7bd52edca?pvs=4
Suit #1554 
**🗺️ contexte**: Cartes sur mesure
**💡 quoi**: En mobile on masque pas uniquement le bouton mais toutes la "légende" (boutons infos et filtres y compris)
**🎯 pourquoi**: pour coller à la demande initiale :)
- On wrap plus de choses dans la conditionnelle dans le template
=>  😶‍🌫️ Totalement masquer la légende en mobile

static/to_compile/entrypoints/qfdmo.css
Cf #1558 j'ai introduit une régression, j'avais testé uniquement en mobile ma modification. 
**🗺️ contexte**: Suit #1558 
**💡 quoi**: Correction d'une régression
- récupération de la hauteur du header qu'on hardcode 
- entourage dans une media query
=> 📏 Correction d'une régression sur la hauteur de la fiche acteur sur une carte sur mesure

dags/enrich/config/__init__.py, dags/enrich/config/models.py, dags/enrich/dags/enrich_dbt_models_refresh.py, dags/shared/config/models.py, dags_unit_tests/shared/config/test_shared_config_models.py
**🗺️ contexte**: on a plusieurs DAG d'enrichissement qui se reposent sur des modèles `dbt` de **marts**, ces DAG **rafraichissent uniquement les modèles de marts** pour avoir des suggestions fraiches **🔴 mais pas les modèles sous-jacents (ex: `int_`) car ceci prendrait trop de temps**.
**💡 quoi**: un DAG pour rafraichir les modèles dbt
**🎯 pourquoi**: mettre à jours les modèles sous-jacents continuellement pour **avoir au pire 1 jour de retard au niveau des marts** quand la data ou le code des modèles < marts changent.
**🤔 comment**:
- le DAG prend une liste de commandes DBT et les exécutent
- 🔮 **J'ai déja spécifié les modèles à venir** pour PR https://github.com/incubateur-ademe/quefairedemesobjets/pull/1534 (pour l'instant = pas de modèle trouvé MAIS pas d'erreur, une fois PR mergée …
=> 🔄 [ENRICH] - DAG de rafraichissment DBT

dags/sources/tasks/business_logic/keep_acteur_changed.py, dags_unit_tests/sources/tasks/business_logic/test_keep_acteur_changed.py, qfdmo/admin/acteur.py, qfdmo/management/commands/update_external_ids.py
Suite #1521
Notion : [Importer le fichier v3 Valdelia (EA, PMCB) dans LVAO - avec table de pivot vers nouvel ID](https://www.notion.so/Importer-le-fichier-v3-Valdelia-EA-PMCB-dans-LVAO-avec-table-de-pivot-vers-nouvel-ID-1c86523d57d7805db04cf33e891ffea7?pvs=8&n=github_linkback)
**🗺️ contexte**: Airflow Source
**💡 quoi**: lors de la migration des identifiant_externe, il faut s'assurer de ne pas créer des duplicats d'identifiant_externe pour la même source
**🎯 pourquoi**: Après le mapping est impossible entre ca qu'on a en DB et ce qu'on a dans la source
* On cherche si un acteur avec la même source et le même identifiant_unique 'exte pas déjà, si oui, on index l'identifiant …
=> Ajouter un index lors de la résolution de mapping

dags/enrich/tasks/business_logic/enrich_dbt_model_read.py, dags/utils/dataframes.py, dags_unit_tests/enrich/tasks/test_enrich_suggestions_cities.py, dbt/models/marts/enrich/marts_enrich_acteurs_villes_candidates.sql
**🗺️ contexte**: je teste les DAGs en PREPROD
**💡 quoi**: bug fix
**🎯 pourquoi**: le champ `acteur_statut` est manquant sur les modèles de suggestions BAN
**🤔 comment**:
- **df_filter**: nouvelle fonction pour pouvoir l'utiliser dans les tests
- **tests** améliorés
- en utilisant les [DBT artifacts](https://docs.getdbt.com/reference/artifacts/dbt-artifacts) post-dbt-build via Python
- en utilisant **[on-run-end](https://docs.getdbt.com/reference/project-configs/on-run-start-on-run-end) + des macros** via le [graph](https://docs.getdbt.com/reference/dbt-jinja-functions/graph#accessing-models)
=> ⚒️ BAN: fix acteur_statut manquant

jinja2/qfdmo/carte/panels/legend_mobile.html, qfdmo/views/adresses.py
**🗺️ contexte**: Ajout de carte sur mesure pour un éco organisme
**💡 quoi**: Correction de plusieurs régression suite à #1464 
**🎯 pourquoi**: pour mettre en prod pardi !
Le HTML de légende mobile n'était pas rendu dans le DOM, et c'est celle ci qui hydrate le formulaire côté python  lors de la soumission d'une adresse. 
Comme on hydrate pas le formulaire, on ne tient pas compte des cases cochées / décochées 
Cela venait d'une logique mal implémentée qui masquait le html de la légende en mobile. 
J'ai adapté la logique 🤯 
- si pas de carte config
- OU si pas de carte_config.hide_legend #1023 
ALORS on masque la légende 
=> Permettre de décocher la case d'un groupe d'action + afficher la légende en mobile

dags/sources/dags/source_sinoe.py, dags/sources/tasks/business_logic/db_read_acteur.py, dags/sources/tasks/business_logic/keep_acteur_changed.py, dags/sources/tasks/transform/transform_df.py, dags/utils/django.py, dags_unit_tests/conftest.py, dags_unit_tests/sources/tasks/business_logic/test_keep_acteur_changed.py, dags_unit_tests/utils/test_django.py, data/models/suggestion.py
Carte Notion/Mattermost/Sentry : [DAG SINOE bloqué - problème avec la colonne ANNÉE](https://www.notion.so/accelerateur-transition-ecologique-ademe/DAG-SINOE-bloqu-probl-me-avec-la-colonne-ANN-E-1ac6523d57d780d0ba7ef7ba1323ede3?pvs=4)
**🗺️ contexte**: Airflow - Source
**💡 quoi**: Le DAG d'ingestion des source SINOE ne fonctionne plus
**🎯 pourquoi**: La colonne ANNEE n'est pas ignoré lors de la récupération des acteurs en DB et de la comparaison des source SINOE avec la base de données
- ajout de la colonne statut nécessaire à l'execution de l'ingestion
- limiter la récupération en base de données au champs disponible en DB
- limiter la comparaison aux champs de la base + les …
=> Fix un pb de colonne lors de l'ingestion de SINOE

.github/workflows/ci.yml, e2e_tests/accessibility.spec.ts
Depuis #1540, les tests e2e se lance avec la carte au lieu de l'assistant pour les tests d'accessibilité. 
**🗺️ contexte**: CI/CD
**💡 quoi**: correction d'une regression qui empêche de lancer les tests e2e
**🎯 pourquoi**: car l'environnement défini dans la github action était mal fait :) 
=> Correction des tests e2e

qfdmd/models.py, qfdmo/models/action.py, qfdmo/views/adresses.py, templates/forms/widgets/groupe_action_label.html
Régression suite à #1464 
**🗺️ contexte**: carte sur mesure
**💡 quoi**: les actions affichées ne respectent pas la configuration souhaitée
**🎯 pourquoi**:
- Dans les carte sur mesure, on affiche la légende en réutilisant un composant utilisant les formulaires django plutôt que réimplémenter la logique manuellement
- Cependant, ce n'est pas 100% possible car le champ ChoiceField utilisé tient compte du contexte pour afficher les libelle
- Ici je propose de permettre d'overrider la variable rendue par le template dans ce cas précis, afin de garder de la flexibilité
=> Correction du libelle dans les groupes d'action affichées dans la carte de l'assistant

dags/sources/config/airflow_params.py, dags/sources/dags/source_soren.py, dags/sources/tasks/business_logic/source_data_normalize.py, dags/sources/tasks/transform/opening_hours.py, dags/sources/tasks/transform/transform_column.py, dags_unit_tests/sources/tasks/transform/test_transform_column.py, jinja2/qfdmo/acteur/tabs/sections/horaires.html
Carte Notion/Mattermost/Sentry : [SOREN](https://www.notion.so/accelerateur-transition-ecologique-ademe/Importer-le-fichier-Soren-v8-14-04-25-1bb6523d57d780e0af01dcae7cbd1a18?pvs=4)
**🗺️ contexte**: Airflow - Source
**💡 quoi**: Les horaires sous forme opening_hours de OSM ne sont pas bien interprété
**🎯 pourquoi**: Nouveau cas de SOREN : il y a maintenant plusieurs plages horaires
Implémentation correct de l'interprétation des opening_hours de OSM
transformation en horaires par jour
implémentation dans le DAG Soren
=> SOREN et OpeningHours : interpreter les opening_hours

dags/utils/django.py, dbt/models/base/ae_annuaire_entreprises/base_ae_unite_legale.sql, dbt/models/base/ae_annuaire_entreprises/schema.yml, dbt/models/base/ban/schema.yml, scripts/dbt/conf/columns.py, scripts/dbt/conf/schemas.py, scripts/dbt/schemas_generate_validate.py, scripts/dbt/tests/test_schemas.py
Carte Notion: [dbt: ré-écrire les schemas](https://www.notion.so/accelerateur-transition-ecologique-ademe/dbt-r-crire-les-schemas-1e46523d57d780a688d3c35fd4ed6922)
**🗺️ contexte**: on utilise dbt pour compiler des modèles, :red_circle: la gestion des **fichiers schema.yml** est **manuelle** et **chronophage**
**💡 quoi**: un script pour générer les schemas automatiquement
**🎯 pourquoi**: gagner en temps et consistence
**🤔 comment**:
1. **modèles**: lit le fichier `dbt/target/manifest.json` pour la liste des modèles compilés
2. **filtre** utilisateur (regex) sur des modèles en particulier (optionnel)
3. **inspection db**: pour voir les champs réels compilés
4. **merge recursif** avec le schema d'origine (pour pas perdre l'existant)
5. **mise à jour du `schema.yaml`** correspondant aux …
=> 🤖 DBT: script de gestion de schemas

dbt/macros/table/macro_acteur_acteur_services.sql, dbt/macros/table/macro_acteur_labels.sql
Un raté qui fait que le calcule des acteurs via DBT est cassé car in se base sur des tables finales plutôt que sur les tables qu'il vient de construire
**🗺️ contexte**: Airflow DBT Source
**💡 quoi**: DBT acteur carte cassé
**🎯 pourquoi**: les tables référencées dans les macros sont les tables cibles : donc on ne peut pas grantir qu'elle existent et en plus la données rique d'être fausse
**🤔 comment**: changement des tables utilisées par les macro
=> fix DBT acteur qui fait appelle à des tables vueacteur plutôt qu'à int_acteur

dags/sources/dags/source_valdelia.py, dags/sources/tasks/airflow_logic/db_data_prepare_task.py, dags/sources/tasks/airflow_logic/db_write_type_action_suggestions_task.py, dags/sources/tasks/business_logic/db_data_prepare.py, dags/sources/tasks/business_logic/source_data_normalize.py
Mattermost : retour de christian -> «nb acteurs filtrés car proffessionnels»
**🗺️ contexte**: Django Admin - Cohorte
**💡 quoi**: metadata sur le nombre de pro filtrés caduque
**🎯 pourquoi**: car il ne sont plus filtrés lors de l'ingestion de source mais plus tard
**🤔 comment**: suppression des metadata sur les nb d'acteurs filtrés car pro
=> Supression de la metadata des pro filtrés et ajout du nombre d'acteurs impactés

core/jinja2_handler.py, core/templatetags/custom_filters.py, jinja2/qfdmo/acteur/tabs/sections/description.html, jinja2/qfdmo/acteur/tabs/sections/horaires.html
Gestion des retours à la ligne.
Quand on édit le paragraphe description dans django admin, les retours à la ligne ne sont pas appliqués dans la fiche acteur.
En solution temporaire en attendant une meilleur gestion (rich text), on remplace les \n par des <br>
même comportement que horaires_description pour débloquer Christian
**🗺️ contexte**: Django - Fiche acteur
**💡 quoi**: Affichage, retour à la ligne dans la description
**🎯 pourquoi**: meilleur mise en page même si c'est pas top
**🤔 comment**: remplacer les \n par de <br> lors de l'affichage de la description
=> Gestion des retour à la ligne de la descriptiion : solution temporaire

pyproject.toml
Vu ensemble pour permettre d'executer `pytest` sans options et sans planter
**🗺️ contexte**: Test
**💡 quoi**: `pytest` sans options et sans planter
**🎯 pourquoi**: ça plante car des lib sont chargée dans scripts mais pas nécessaire dans les tests et as besoin au quotidien
**🤔 comment**: ajout de l'option `--ignore` dans `pyproject.toml` 
=> Ignorer le dossier script lors de la collecte des tests par pytest

dags/sources/dags/source_ocab.py, dags/sources/tasks/airflow_logic/config_management.py, dags/sources/tasks/business_logic/source_data_normalize.py, dags_unit_tests/sources/tasks/business_logic/test_source_data_normalize.py
Notion !
**🗺️ contexte**: Airflow Source
**💡 quoi**: OCAB est en conflig avec les source fournit aussi par ses adhérents : Valdelia, Ecomaison
**🎯 pourquoi**: Identifier les Acteur qui ont été fournit par l'OCAB et ceux fournit directement par les adhérents. Supprimer les interférence des acteurs du même EO mais qui ont plusieurs source : Valdelia, Ecomaison fournissent leur prore point mais OCAB fournissent des acteurs pour ces 2 EO aussi
- On Crée des nouvelles sources prefixées par le cod de l'OCA (ici : ocab) pour qu'il n'y ait pas d'interférence avec les acteurs fournit par l'EcoOrganisame directement
- On gère les acteur qui sont données pour plusieurs Eco-organisame : …
=> Dédupliquer les lignes qui ont plusieurs EO et prefixé ocab

dags/enrich/tasks/business_logic/enrich_dbt_model_to_suggestions.py, dags_unit_tests/enrich/tasks/test_enrich_suggestions_closed.py
Mattermost : demande de @chrischarousset -> https://mattermost.incubateur.net/fabnum-mte/pl/e8me3e3w5389jj4jd4ed4gpyko
**🗺️ contexte**: Admin - Suggestion
**💡 quoi**: Ajouter le nom de l'acteur et quelques informations lors de la proposition de fermeture d'acteur
**🎯 pourquoi**: aider à la prise de décision
**🤔 comment**: Ajout d'information dans la colonne "données initiales"
=> Ajout de context pour les suggestions d'acteur fermé

scripts/restore_prod_to_preprod.sh
Sentry : [RevisionActeur.MultipleObjectsReturned](https://sentry.incubateur.net/organizations/betagouv/issues/174682/?environment=staging&project=115&query=is%3Aunresolved&referrer=issue-stream&stream_index=0)
**🗺️ contexte**: Github action
**💡 quoi**: Correction synchro de la base de prod vers la preprod
**🎯 pourquoi**: c'est cassé
**🤔 comment**: suppression de toutes les tables du schema `public` au lieu de supprimer le schema car on a pas le droit
=> Correction de la synchro de la base de données

dbt/models/exposure/acteurs/carte/schema.yml, dbt/models/exposure/acteurs/opendata/schema.yml
Les seuils appliqués aux tests des tables de la carte et de l'opendata étaient ceux de la table exhaustive, du coup, ça plante
**🗺️ contexte**: Airflow DBT
**💡 quoi**: Seuils de controle mal adapté
**🎯 pourquoi**: la table exhaustive est prise comme référence
**🤔 comment**: Adaptation des seuils
=> Mise à jour des seuils de contrôle des tables DBT générées

dags/sources/tasks/transform/transform_df.py, dags/tests/sources/tasks/transform/test_transform_df.py
Mattermost : [Peux-tu gérer ce formating d'adresses OCAB dans une future PR, @nicoo stp ?](https://mattermost.incubateur.net/betagouv/pl/13obtzq8fp8j7ymusrfej6upea)
**🗺️ contexte**: Airflow Source
**💡 quoi**: Permettre d'utiliser le tiret `-` comme séparateur dans l'adresse BAN
**🎯 pourquoi**: OCAB l'utilise
- Ajout du tiret
- Strip les chaines de caractères adresse, CP, ville avec la liste des séparateurs
=> Ajouter le tiret comme separateur possible dans une adresse BAN

dags/.env.template, dags/airflow_local_settings.py
Erreur :
Préconisation Airflow : 
https://airflow.apache.org/docs/apache-airflow/stable/howto/set-up-database.html
https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html cf. AIRFLOW__DATABASE__SQL_ALCHEMY_CONNECT_ARGS
Chargement de la configuration dans les logs : 
```
airflow-scheduler-1  | [2025-05-27T07:07:15.104+0000] {settings.py:771} INFO - Loaded airflow_local_settings from /opt/airflow/dags/airflow_local_settings.py .
```
On espère que ça va résoudre le problème 🤞 
**💡 quoi**: Erreur SSL en fin de tache lors de la connexion à la DB
**🎯 pourquoi**: la connexion n'est pas restée ouverte
**🤔 comment**: Ajout de configuration pour garder la connexion ouverte
=> Résolution des erreur SSL quand une tache dure trop longtemps

static/to_compile/js/solution_map.ts
Pour éviter ce type de carte quand on explorer avec "Rechercher dans cette zone"
je propose de ne pas prendre en compte le point de localisation lors du centrage de la carte
Effet de bord possible (mais à mon avis rarisime), le point de localisation peut e pas être présent sur la partie visible de la carte si toute les propositions faites à l'utilisateur sont du même coté 
**🗺️ contexte**: Carte
**💡 quoi**: Ne pas prendre en compte le point de localisation pour centrer la carte
**🎯 pourquoi**: Lors de l'exploration grace au bouton "Rechercher dans cette zone", l'affichage du point de localisation est parfois très ditant et n'apporte pas grand chose puisse que l'utilisateur est en train de parcourir la carte (en tout cas moi ça m'irrite :) )
**🤔 comment**: Suppression du point de …
=> Ne pas prendre en compte le point de localisation pour centrer la carte

qfdmd/templatetags/qfdmd_tags.py
Alert Search console
**🗺️ contexte**: SEO
**💡 quoi**: forcer l'URL canonique
**🎯 pourquoi**: petite embrouille lors du passage en prod qui fait qu'on est indexé à moité sur quefairedemesdechets et quefairedemesobjets
**🤔 comment**: toujours définir une url canonique
=> Toujours définir l'url canonique, même si c'est la même url

.github/dependabot.yml
Tenter une configuration de dependabot pour grouper les mise à jour des librairies parcel
**🗺️ contexte**: Github Action - Dependabot
**💡 quoi**: Grouper les mises à jour de la ligrairie parcel par dependabot
**🎯 pourquoi**: Eviter les PR dependabot qui sont en erreur à cause des mise à jour Parcel
**🤔 comment**: ajout du paramètre `groups` dans a config npm de dependabot
cf. https://docs.github.com/fr/code-security/dependabot/working-with-dependabot/dependabot-options-reference#groups--
=> Grouper les mises à jour de la ligrairie parcel par dependabot

dags/cluster/config/model.py, dags/cluster/dags/cluster_acteur_suggestions.py, dags/cluster/tasks/airflow_logic/cluster_acteurs_parents_choose_data_task.py, dags/cluster/tasks/business_logic/cluster_acteurs_parents_choose_data.py, dags/tests/cluster/config/test_model.py, dags/tests/cluster/tasks/business_logic/test_cluster_acteurs_parents_choose_data.py
Carte Notion 👇 
**🗺️ contexte**: Airflow - Clustering
**💡 quoi**: L’algo de clustering ne devrait pas venir agglomérer du contenu dans des champs DÉJÀ remplis quand il s’agit juste d’ajouter des enfants à un parent EXISTANT
**🎯 pourquoi**: Perte des données corrigé au niveau parent
**🤔 comment**: Ajout d'une option "Converser les données du parent"
keep parent by default : vrai
keep empty value : faux
[-5 j](https://mattermost.incubateur.net/betagouv/pl/43sx66bz6byjmeihcmcib4c8ga)
Keep parent = vrai
keep empty = vrai
=> Option permettant de garder les données du parent lors d'un clustering avec parent existant

static/to_compile/controllers/assistant/state.ts, static/to_compile/controllers/carte/search_solution_form_controller.ts
Carte Notion : https://www.notion.so/accelerateur-transition-ecologique-ademe/2016523d57d780ac8d16cf8cf568d89d?v=2016523d57d78068b32e000c9f5316fb&source=copy_link
**🗺️ contexte**: Carte
**💡 quoi**: Gestion de la Bbox lors de la recherche d'adresse
**🎯 pourquoi**: sinon, la Bbox est conservée
**🤔 comment**: Reset de la Bbox dans le controleur state avant la mise à jour des données de localisation
=> Remise à zero des bbox lorsqu'on mets à jour les données de localisation

static/to_compile/styles/dsfr-overrides.css, templates/components/produit/produit.html
Pas de carte, l'objectif est de coller aux maquettes
**🗺️ contexte**: Assistant v2
**💡 quoi**: on réduit les marges appliquées aux onglets affichés dans l'assistant
**🎯 pourquoi**: pour coller aux créas
- on réplique fr-tabs--noborder qui avait déjà été écrite, en appliquant la logique uniquement sur mobile
=>  ↔ Réduction des marges en mobile dans les onglets de l'assistant

jinja2/qfdmo/carte.html, jinja2/qfdmo/formulaire.html
https://www.notion.so/accelerateur-transition-ecologique-ademe/Mobile-La-fen-tre-pour-le-partage-de-la-fiche-est-pas-visible-compl-tement-21d6523d57d780d6aa87dd4cb6003cf6?source=copy_link
**🗺️ contexte**: Assistant v2
**💡 quoi**: résolution d'un bug qui empêche de voir la tooltip de partage dans une fiche acteur
**🎯 pourquoi**: pour pouvoir partager un acteur 
- Suppression de l'overflow auto en mobile, on utilise overflow visible 
=> 🐛 Retours sur le maintien de la géoloc dans l'assistant

qfdmd/admin.py
https://www.notion.so/accelerateur-transition-ecologique-ademe/Admin-Django-Pas-d-acc-s-au-d-tail-des-fiches-produits-21e6523d57d780749603e0a1bc4f86b1?source=copy_link
**🗺️ contexte**: django admin
**💡 quoi**: correction d'une erreur serveur dans django admin 
**🎯 pourquoi**: empêcher l'admin de crasher quand on visionne un produit 
- un champ id était précédemment défini sur le modèle, il l'est désormais dans un modèle parent 
- On y a donc plus accès, ce qui provoque une erreur dans django admin 
Comme il n'est pas prévu de modifier ces IDs, on peut sans soucis ne pas l'afficher et le supprimer de la liste ici qui servait à la placer en première position dans le formulaire django 
=> 💣 Empêcher l'admin de crasher quand on visionne un produit

core/constants.py, jinja2/qfdmo/acteur/_actions.html, jinja2/qfdmo/acteur/tabs/sections/meta.html, jinja2/qfdmo/carte/panels/legend.html, jinja2/qfdmo/shared/_search_in_zone.html, qfdmo/models/acteur.py, unit_tests/qfdmo/acteur_factory.py, unit_tests/qfdmo/test_acteur.py
Carte Notion/Mattermost/Sentry : https://www.notion.so/accelerateur-transition-ecologique-ademe/Rendre-plus-visible-la-contribution-usager-sur-la-carte-ajout-et-modification-1ea6523d57d780e4a68fdd36dc55f824?source=copy_link
**🗺️ contexte**: Assistant v2
**💡 quoi**: Mise en oeuvre d'améliorations de la UI 
**🎯 pourquoi**: pour inciter les usagers à contribuer des modifications des données affichées
- Ajout d'une icône sur le bouton rechercher dans cette zone 
- Renommage du bouton filtres avancées : On en profite pour stocker ça dans une variable globale 
- Ajout d'un bouton Modifier avec un crayon sur les fiches acteurs, qui reprend le lien vers le tally 
À noter : on ne …
=> 🖊️ Meilleure incitation aux contributions utilisateurs

templates/components/footer/_standalone.html
Changement texte pour bouton Intégrer qui n'est plus à droite
**💡 quoi**: 
=> 🖊️ Changement texte pour bouton Intégrer qui n'est plus à droite

templates/qfdmd/produit_page.html
Correction d'un bug où le titre arrivait sous le contenu en mobile, dû au mauvais copier-coller d'une clase CSS.
=> Le titre arrivait sous le contenu en mobile 

templates/qfdmd/base.html, templates/tests/iframe.html
Ajout d'une bordure autour de l'assitant en iframe https://www.notion.so/accelerateur-transition-ecologique-ademe/Assistant-iFrame-Ajouter-un-contour-pour-les-r-utilisations-21f6523d57d78005a3c0ecfcc917d591?source=copy_link
=> ⎯ Ajout d'une bordure autour des iframes de l'assistant

templates/components/header/header_menu.html, templates/components/search/view.html, templates/pages/home.html
Correction de deux bugs sur l'assistant 
- La recherche de la page d'accueil ouvrait la recherche dans le header
- L'item de menu courant dans la navigation principale n'était pas décoré d'une bordure bleue
=> Ajout des liens de menu pour l'item courant + bug sur la recherche

e2e_tests/assistant.spec.ts, qfdmd/templatetags/qfdmd_tags.py, templates/blocks/reusable.html, templates/components/produit/_infotri.html, templates/qfdmd/produit_page.html
Régression sur le lien vers l'infotri. 
Celui-ci exploitait une variable globale dont une variable locale a été introduite avec le même nom dans le template. 
Au passage, ajout de la fondation permettant de dynamiser les contenus réutilisables dans la future mouture du CMS
=> ♻️ Correction d'un bug sur le lien de l'infotri qui ne redirige plus vers ecologie.gouv.fr

qfdmd/templatetags/qfdmd_tags.py
Permettre d'afficher le nom d'un objet lorsque le texte est `<objet>` dans un contenu réutilisable
=> Rendu dynamique des produits via le tag `<objet>` dans Wagtail

core/context_processors.py, e2e_tests/assistant.spec.ts, infrastructure/environments/prod/main.tf, package-lock.json, package.json, qfdmd/forms.py, qfdmd/views.py, static/to_compile/controllers/assistant/search.ts, templates/components/search/view.html, templates/pages/home.html
https://www.notion.so/accelerateur-transition-ecologique-ademe/Assistant-Probl-me-sur-la-double-recherche-en-page-d-accueil-22a6523d57d78057981df59c74704cf9?source=copy_link
**🗺️ contexte**: assistant v2, recherche page d'accueil
On a désormais deux recherches en page d'accueil : celle du header et celle principale. 
On a donc besoin de namespacer nos turbo frames pour éviter les conflits. 
On utilise une combinaison entre un champ `id` passé dans nos turbo frame avec un champ prefix qui va être utile pour namespacer nos champs de formulaires 
=> Corrige un problème sur la recherche en page d'accueil qui entre en conflit avec la recherche dans le menu

.github/workflows/review.yml, docs/reference/db/prerequis.md, package-lock.json, package.json
Correction de la CI/CD, le script `review.yml` faisait appel à un fichier qui n'exitait plus
J'ai pris le parti de ne pas appeler le script de deploiement lors de review… On pourra revenir là dessus si on veut garder cette option
**🗺️ contexte**: CI/CD
**💡 quoi**: Erreur car appel à un fichier inexistant
**🎯 pourquoi**: erreur de manip
**🤔 comment**: suppression de l'appel au fichier
=> Pas d'option pour déployer lors de review

dags/cluster/dags/cluster_acteur_suggestions.py, dags/cluster/tasks/business_logic/cluster_acteurs_parents_choose_data.py, dags/tests/cluster/tasks/business_logic/test_cluster_acteurs_parents_choose_data.py
Carte Notion/Mattermost/Sentry : [Le clustering ne devrait pas créer des parents vides (notamment “Nom” vide)](https://www.notion.so/accelerateur-transition-ecologique-ademe/Le-clustering-ne-devrait-pas-cr-er-des-parents-vides-notamment-Nom-vide-2386523d57d780749127d53bfeff39a0)
**🗺️ contexte**: Airflow - clustering
**💡 quoi**: Appliquer l'option keep_empty_data seulement pour les parents à mettre à jour mais pas pour la création de parent
**🎯 pourquoi**: sinon, il y a des cas de parents vides
- Forcer l'option `keep_empty` à False quand il n'existe pas de parent au sein du cluster au moment de choisir les données à attribuer au parent
- Modification du help text des options du dag de clustering
=> L'option keep_empty n'est applicable que pour la modification de parent

scripts/infrastructure/backup-db.sh
Ajout d'une expiration à une semaine lors de la création d'un backup via le script `backup-db.sh`
permet de ne pas se trainer 2000 backup
**🗺️ contexte**: Makefile / script
**💡 quoi**: expiration des backup
**🎯 pourquoi**: limiter le nombre de backup stocké
**🤔 comment**: ajout du paramètre expire-at lors de la création du backup en ligne de commande
=> Ajout d'un expiration lors de la cération du backup

data/admin.py
Permettre de chercher les suggestions par metadata
Amélioration de la recherche des cohortes dans l'admin
**🗺️ contexte**: Django Admin - data
**💡 quoi**: Meilleur recherche
**🎯 pourquoi**: simplifier la recherche pour Christian
- Ajout du champ `metadata` dans la recherche des suggestion
- Ajout de la recherche pour les cohortes sur les champs `metadata`,  `identifiant_action`, `identifiant_execution`
- Ajout des filtres `statut` et `action_type` pour les cohortes
=> Recherche des suggestions selon le texte de metadata

dags/cluster/tasks/business_logic/cluster_acteurs_read/orphans.py
Mattermost : Pb quand include_only_if_regex_matches_nom = "Mat'ild", les majuscules et caractères spéciaux semblent casser el matching
**🗺️ contexte**: Airflow - Clustering
**💡 quoi**: include_only_if_regex_matches_nom = "Mat'ild" ne marche pas
**🎯 pourquoi**: le champ `nom` est normalisé mais pas le paramètre `include_only_if_regex_matches_nom`
**🤔 comment**: nomaliser le paramètre `include_only_if_regex_matches_nom`
=> [Cluster] Normaliser aussi le paramètre de recherche par le nom

.github/workflows/ci.yml
Migration concernant la connexion Warehouse impossible à appliquer
**🗺️ contexte**: CI
**💡 quoi**: Fix
**🎯 pourquoi**: Ignorer la migration problématique
**🤔 comment**: Définir la variable d'env PYTEST_CURRENT_TEST en CI lors de la migration, ceci ignore la migration qui utilise le connecteur
=> Résolution d'une régresseion dans la CI : test de bout en bout

dags/cluster/tasks/business_logic/cluster_acteurs_clusters.py, dags/cluster/tasks/business_logic/cluster_acteurs_read/for_clustering.py, dags/cluster/tasks/business_logic/cluster_acteurs_read/orphans.py, dags/cluster/tasks/business_logic/cluster_acteurs_read/parents.py, dags/cluster/tasks/business_logic/misc/cluster_exclude_intra_source.py, dags/cluster/tasks/business_logic/misc/df_sort.py, dags/tests/cluster/tasks/business_logic/test_cluster_acteurs_clusters.py, dags/tests/cluster/tasks/business_logic/test_cluster_acteurs_clusters_prepare.py, dags/tests/cluster/tasks/business_logic/test_cluster_acteurs_exclude_intra_source.py, dags/tests/cluster/tasks/business_logic/test_cluster_acteurs_read_parents.py
Carte Notion : [[Clustering] L’interdiction de clustering intra-source devrait s’appliquer AUSSI à l’éventuelle update de clusters (pas juste à la création)](https://www.notion.so/accelerateur-transition-ecologique-ademe/Clustering-L-interdiction-de-clustering-intra-source-devrait-s-appliquer-AUSSI-l-ventuelle-updat-2416523d57d780ba9306e4e591baf29b?source=copy_link)
**🗺️ contexte**: Airflow Clustering
**💡 quoi**: L'option `cluster_intra_source_is_allowed = False` doit aussi prend en compte les sources des parents
**🎯 pourquoi**: Sinon, l'option est buggé dès qu'il y a un parent existant
- Ajout d'une colonne `source_codes` qui liste les sources des acteurs à rapprocher dans les clusters. Dans le cas des acteurs sans parent, la liste `source_codes` est de longueur 1, pour …
=> L'option exclusivité de source doit prendre en compte les sources des parents

jinja2/qfdmo/acteur/tabs/about_panel.html, jinja2/qfdmo/acteur/tabs/sections/consignes_dacces.html, qfdmo/management/commands/fill_consignes_dacces.py
Carte Notion/Mattermost/Sentry : [Déchèteries : ajouter warning : besoin (possible) de présenter un badge pour accéder](https://www.notion.so/accelerateur-transition-ecologique-ademe/D-ch-teries-ajouter-warning-besoin-possible-de-pr-senter-un-badge-pour-acc-der-1fb6523d57d78091911fcc996f7892f2?source=copy_link)
**🗺️ contexte**: Webapp
**💡 quoi**: Afficher les consignes d'accès + mettre à jour les consignes d'accès pour les déchetteries
**🎯 pourquoi**: Besoin d'afficher les consignes d'accès
**🤔 comment**: Affichage sous la description + script pour populer les consignes d'accès des déchèteries
=> Affichage des consignes d'accès et initialisation pour les déchèteries

dags/acteurs/dags/export_opendata.py
Mattermost : [Le run hebdomadaire pour exporter les acteurs en open data a échoué à nouveau](https://mattermost.incubateur.net/betagouv/pl/ia9pfoe5ctfsxgyyip49wkdaio)
**🗺️ contexte**: Airflow - Export Opendata
**💡 quoi**: Résolution du lancement hedbomadaire qui ne marche pas
**🎯 pourquoi**: Start date dynamique -> pas une bonne pratique
**🤔 comment**: Mise à jour d'une start date fixe pour ce DAG
cf. https://github.com/apache/airflow/discussions/54369
=> Correction du lancement du Dag export_opendata une fois par semaine

.github/workflows/_deploy-airflow.yml, .github/workflows/_scaleway_container_deploy.yml
On essaye d'accéder aux variable de l'environnement alors qu'l n'est pas encore définit, du coup on utilise le nom de la variable à passer au job qui lui connait l'environnement
**🗺️ contexte**: CD - Airflow - Scaleway
**💡 quoi**: Correction du deploiement sur Scaleway
**🎯 pourquoi**: Car ça ne marchait pas
**🤔 comment**: On passe le nom de la variable plutôt que la variable car elle n'est pas encore accessible
=> Le déploiement du docker ne connait pas le conatiner_id avant de définir l'environnement

poetry.lock, pyproject.toml
Tout est dans le titre, cette librairie ne semble pas etre utilisé
**🗺️ contexte**: Dependance AirFlow
**💡 quoi**: Suppressin de pyproj pas utilisé
**🎯 pourquoi**: entretien de code
**🤔 comment**: suppression de pyproj dans pyproject.toml
=> suppression de la librairie pyproj qui ne semble pas être utilisée

package-lock.json, package.json
Dans la PR #1910 , la dépendance `lodash` est supprimée, cependant, on l'utilise dans notre code TS
**🗺️ contexte**: Build Parcel
**💡 quoi**: Ajout d'une dépendance manquante
**🎯 pourquoi**: suppression de cette dépendance par une autre dépendance
=> Ajout de lodash dans les dépendances

qfdmo/migrations/0001_initial_squashed_0158_alter_carteconfig_slug.py, qfdmo/migrations/0167_serviceadomicile.py
Pb de migration lors de la mise en preprod
**🗺️ contexte**: Migrations
**💡 quoi**: pb suite au changement de management des tables VueModel
**🎯 pourquoi**: champ consignes_dacces déjà existant
**🤔 comment**: déplacement de la création de la colonne dans la migration initiale
=> Corrige un problème de migration sur la table vueacteur

static/to_compile/controllers/carte/address_autocomplete_controller.ts, static/to_compile/controllers/carte/autocomplete_controller.ts, static/to_compile/controllers/carte/ss_cat_object_autocomplete_controller.ts, templates/forms/widgets/autocomplete.html
Quand on cherche une ville, on n'a pas de précision quand à la région ou au département. je propose d'ajouter le contexte aux résultats de recherche dans ce cas uniquement : ville == label
**🗺️ contexte**: Carte
**💡 quoi**: Ajout du context dans les réponses quand on cherche une ville
**🎯 pourquoi**: Savoir quelle ville on sélectionne
- Ajout du context à coté du résultat
- Simplification : la fonction "AddOption" est désormais la même pour sousCat et BAN
- Suppression du target AllAvailableOption : je n'ai pas trouvé à quoi il sert, c'est surement du legacy
=> Ajout du context dans les réponses quand on cherche une ville

dags/cluster/tasks/business_logic/cluster_acteurs_suggestions/context.py
Carte Notion/Mattermost/Sentry : [[Suggestions] Le template pour Clustering n’affiche plus correctement le code postal](https://www.notion.so/accelerateur-transition-ecologique-ademe/Suggestions-Le-template-pour-Clustering-n-affiche-plus-correctement-le-code-postal-2376523d57d7809e9ba7f953ad0ced35?source=copy_link)
**🗺️ contexte**: Clustering
**💡 quoi**:  le code postal ne n'affiche pas bien
**🎯 pourquoi**: pb de tuble vs string
**🤔 comment**: forcer le type tuple quand 1 seule entrée
=> Résolution de l'affichage du detail exact match quand il n'y a qu'un champ

dags/cluster/tasks/business_logic/cluster_acteurs_parents_choose_data.py, dags/tests/cluster/tasks/business_logic/test_cluster_acteurs_parents_choose_data.py, dags/tests/cluster/tasks/business_logic/test_cluster_acteurs_read_children.py
Carte Notion/Mattermost/Sentry : [[Clustering] Les parents devraient être enrichis avec les données (fraiches) de DisplayedActeurs pas de la table Importé](https://www.notion.so/accelerateur-transition-ecologique-ademe/Clustering-Les-parents-devraient-tre-enrichis-avec-les-donn-es-fraiches-de-DisplayedActeurs-pas--1fb6523d57d780afbe39f832c644e51e?source=copy_link)
**🗺️ contexte**: Airflow Cluster
**💡 quoi**: pb de priorité des sources sélectionnées
Plus d'info sur le ticket notion
=> Les données des révisions sont prioritaires pour choisir les données du parent

static/to_compile/embed/assistant.ts, static/to_compile/js/iframe_functions.ts
https://www.notion.so/accelerateur-transition-ecologique-ademe/Les-iFrames-ne-poss-dent-pas-d-identifiant-ce-qui-emp-che-leur-redimensionnement-21b6523d57d78012b238f26ee33ba028?source=copy_link
**🗺️ contexte**: iframe 
**💡 quoi**: ajout d'un id sur l'iframe de l'assistant pour éviter des conflits avec d'autres iframes
- Les iFrame n’ont pas d’ID par défaut, alors que iframe-resizer, dépendance utilisé pour redimensionner automatiquement les iframes en ajoute un par défaut
- Cela peut entrer en conflit si une autre iframe est présente sur la page, et qui n’a pas non plus d’id, et qui utilise également iframe resizer
**🤔 comment**:
- utilisation des options de iframe resizer pour ajouter un `id` à l'initialisation 
=> Ajouter un id sur l'iframe de l'assistant pour éviter des conflits avec iframe resizer

core/templatetags/share_tags.py, integration_tests/assistant/home.py, integration_tests/core/test_sharer.py, templates/modals/base.html
https://www.notion.so/accelerateur-transition-ecologique-ademe/AST-2-Mobile-Les-boutons-partager-et-int-grer-doivent-tre-l-un-en-dessous-de-l-autre-libell-s-lo-2256523d57d78039a241d38b3e77db86?source=copy_link
**🗺️ contexte**: Régressions sur le partage
**💡 quoi**: on affiche un `None` dans le template
**🎯 pourquoi**: en basculant sur de jinja à DTL il y a eu un raté
**🤔 comment**:
- on retourne une string vide dans les templates tags plutot que none. C'est une convention pas forcément écrite mais souvent retrouvée dans les templates tags built in de django 
=> Corrige les boutons de partage : Plus de None, meilleur alignement sur la home de l'assistant

dbt/models/exposure/acteurs/carte/exposure_carte_acteur.sql
Mattermost: [Uniquement à domicile : Est-ce qu'on a un risque qu'ils apparaissent sur la carte](https://mattermost.incubateur.net/betagouv/pl/ye7ozxfso7ytzb5xueazd9nm3c)
En attendant la fonctionnalité, on les filtre
**🗺️ contexte**: DBT
**💡 quoi**: Ne pas afficher les services à domicile uniquement
**🎯 pourquoi**: Car la fonctionnalité n'est pas prète
**🤔 comment**: Filtré sur la couche exposure
=> Ne pas afficher les Acteurs qui ne font que du service à domicile

data/models/suggestion.py, unit_tests/qfdmd/test_synonyme.py
Mattermost @chrischarousset  : [ah zut, nouvelle erreur](https://mattermost.incubateur.net/betagouv/pl/wejpbxfuk7ybufu1uxga6io6sc)
**🗺️ contexte**: Airflow Source S3
**💡 quoi**: tombe en erreur quand la colonne perimetre_adomicile_codes n'existe pas
**🎯 pourquoi**: On ne teste pas la présence de la colonne avant de la traitée
- Vérifier que les clés `_codes` existent avant de les traiter
- correction d'un test qui tombait en erreur aléatoirement
=> L'import s3 est cassé depuis l'intégration des service à domicile

.github/workflows/_deploy-airflow.yml
Suite au déploiement des containers Airflow sur Scaleway en preprod puis prod, désactive le déploiement d'Airflow sur Clever Cloud en `preprod`. Seule la `prod` est conservée pour le moment, avant suppression et passage à Scaleway.
=> CD : déploiement de Airflow sur Clever en prod uniquement

static/to_compile/embed/helpers.ts
Vu en pair : on désactive la fonctionnalité qui génère des erreurs CORS en front
=> Désactiver le backlink temporairement
