- .github/workflows/build_and_test.yml
- .pre-commit-config.yaml
- README.md
- core/settings.py
- dev-requirements.in
- dev-requirements.txt
- pyproject.toml
Ajout des scripts de pre-commit suivant:
- trailing-whitespace
- check-yaml
- check-added-large-files
- black
- ruff
- mypy
- djhtml
> add pre-commit hooks

- .env.template
- core/settings.py
- core/urls.py
- requirements.in
- requirements.txt
Add [django-sql-explorer](https://django-sql-explorer.readthedocs.io/en/latest/) to allow query and analyse DB
> Add django-sql-explorer application

- Aptfile
- README.md
- bin/post_compile
- qfdmo/management/commands/populate_reemploi_acteur.py
following instruction in the README:
> we need to install GDAL as explain in doc : [https://techilearned.com/configure-geodjango-in-scalingo/](https://techilearned.com/configure-geodjango-in-scalingo/) form [https://doc.scalingo.com/platform/app/app-with-gdal](https://doc.scalingo.com/platform/app/app-with-gdal) and mattermost discussion in beta.gouv.fr community
> Config gdal in scalingo : final version

- README.md
- qfdmo/management/commands/populate_reemploi_acteur.py
We need to order queryset else we can't warranty that all records are queried while paginate it
> Order paginated queryset

- qfdmo/management/commands/populate_economie_circulaire_acteur.py
often, the sous categories list become empty after executing some command.
Here we fix it !
> avoid remove sous_categories from this command

- jinja2/qfdmo/reemploi_solution.html
- qfdmo/forms.py
- qfdmo/views.py
First dirty solution waiting autocomplete on addresses
> Geoloc user by default if adresse is not set

- jinja2/qfdmo/reemploi_solution.html
- qfdmo/forms.py
- static/to_compile/src/autocomplete_controller.ts
- templates/autocomplete.html
> First version about search an address using BAN API from client side

- README.md
- iframe.html
- jinja2/layout/base.html
Using this library : https://github.com/davidjbradshaw/iframe-resizer
> Manage ifarme resize with iframe resize library

- jinja2/qfdmo/partials/action_list_by_direction.html
- jinja2/qfdmo/reemploi_solution.html
- static/to_compile/src/address_autocomplete_controller.ts
- static/to_compile/src/solution_map.ts
- templates/django/forms/widgets/autocomplete.html
Display an error when the geoloc is not availabe (ex: not allowed by te user)
Do not submit after select « Autour de moi »
Less margin around actions
Do not display home popup by default
Display smaller map in iframe mode when no address
> Display error when geoloc is not shared

- jinja2/qfdmo/reemploi_solution.html
- tailwind.config.js
- templates/django/forms/label.html
be able to customize it with classes
Display it smaller
> customize the label of the field

- static/to_compile/src/address_autocomplete_controller.ts
- static/to_compile/src/autocomplete_controller.ts
- templates/django/forms/widgets/autocomplete.html
> better management of autocomplete conponent on limit

- static/to_compile/src/solution_map.ts
> hide zoom when display popup

- jinja2/qfdmo/acteur_as_card.html
- jinja2/qfdmo/partials/display_solutions.html
- jinja2/qfdmo/partials/feedback.html
- jinja2/qfdmo/reemploi_solution.html
- static/to_compile/entrypoints/qfdmo.css
- unit_tests/qfdmo/test_acteur.py
Add links to Tally foms to get user feedback
- propose a solution
- propose an update (correction)
- contact us
> Tally links

- integration_tests/qfdmo/test_reemploi_solution.py
- jinja2/qfdmo/partials/search_solution.html
- qfdmo/forms.py
- qfdmo/views/display_solutions.py
- static/to_compile/entrypoints/qfdmo.ts
- static/to_compile/src/address_autocomplete_controller.ts
- static/to_compile/src/autocomplete_controller.ts
- static/to_compile/src/ss_cat_object_autocomplete_controller.ts
- static/to_compile/src/types.ts
- static/to_compile/tests/choose_action_controller.test.ts
- tailwind.config.js
> display sub-cat iso

- qfdmo/models/acteur.py
- unit_tests/qfdmo/test_acteur.py
remove space and accent from source name
> clean identifiant_unique automatically created

- .github/workflows/push_version_tags.yml
- README.md
Using the package https://github.com/marketplace/actions/automatic-releases
> Add a github action step to create GH release when push production tag

- .github/workflows/run_tests.yml
Trying to solve issue when installing gdal in CI
> add an apt-get update in CI

- core/urls.py
cf. https://sentry.incubateur.net/organizations/betagouv/issues/74602/?alert_rule_id=74&alert_timestamp=1700834563787&alert_type=email&environment=production&project=115&referrer=alert_email
> Remove accounts path which are useless and finish as 500 error

- jinja2/qfdmo/partials/display_solutions.html
- static/to_compile/src/display_solutions_controller.ts
Remove layout over the map to do not display 2 message with partial opacity
> Do not display 2 overlay when searching

- README.md
> Fix(309): categories display on README.md 

- qfdmo/views/display_solutions.py
- templates/admin/base_site.html
Avoid security issue : https://github.com/incubateur-ademe/quefairedemesobjets/security/code-scanning/1
> redirect to admin in new window after refreshing view

- .eslintrc.js
- .vscode/settings.json
- package-lock.json
- package.json
- tailwind.config.js
following @stephane-ruhlmann advice !
Thank you Stéphane
Configuration to be compared to : https://github.com/incubateur-ademe/benefriches/blob/main/apps/web/.eslintrc.cjs
> Install and configure eslint as ts linter

- static/to_compile/src/autocomplete_controller.ts
- templates/django/forms/widgets/autocomplete.html
> Manage to close the option list of autocomplete select

- .env.template
- jinja2/layout/base.html
- package-lock.json
- package.json
- qfdmo/views/display_solutions.py
- requirements.txt
- static/to_compile/src/analytics.ts
- static/to_compile/src/ss_cat_object_autocomplete_controller.ts
doesn't work yet
In debug mode we well see the event sent :
```
11:05:50 web.1      | DEBUG:posthog:enqueued sous_categorie_objet_input.
11:05:50 web.1      | DEBUG:posthog:making request: {"batch": [{"properties": {"object_requested": "meuble tv", "object_list": [{"label": "Meuble TV", "sub_label": "Meuble", "identifier": 100}, {"label": "Accessoire pour meuble (taquet, \u00e9querre, patte, charni\u00e8re, vis sp\u00e9cifiquement d\u00e9di\u00e9es)", "sub_label": "Meuble", "identifier": 100}, {"label": "Meuble", "sub_label": "Meuble", "identifier": 100}, {"label": "Meuble de tri", "sub_label": "Meuble", "identifier": 100}, {"label": "Meuble de bar", "sub_label": "Meuble", "identifier": 100}, {"label": "Meuble colonne", "sub_label": "Meuble", "identifier": 100}, {"label": "Meuble …
```
> Send custom event to posthog on server side

- qfdmo/views/display_solutions.py
Trying to solve : https://sentry.incubateur.net/organizations/betagouv/issues/75643/events/88683aa1afce41f98288b215a8e1ea75/?project=115
> Do not cast digital default value to avoid software issue

- README.md
- Indicate listening port for django webserver
> Update Readme to add webserver port

- static/to_compile/entrypoints/qfdmo.css
> move the option div on top of search in zone button

- static/to_compile/src/ss_cat_object_autocomplete_controller.ts
Fine tuning of posthog metrics
> Posthog event refactoring to clarify usage (#356)

- static/to_compile/src/ss_cat_object_autocomplete_controller.ts
> resolve number type for identifier_selected parameter

- jinja2/qfdmo/partials/display_solutions.html
Issue when user display for the first time the iframe version of the app and click 'en ligne' option, the display solution div is not well resized.
Before 
After
> display 400 px height screen for digital POI

- jinja2/qfdmo/partials/action_list_by_direction.html
> display small checkbox

- jinja2/editorial/accessibility.html
- jinja2/editorial/cgu.html
- jinja2/editorial/cookies.html
- jinja2/editorial/legal_notices.html
- jinja2/editorial/personal_data.html
- jinja2/editorial/sitemap.html
- jinja2/layout/footer.html
- qfdmo/urls.py
All legales mentions like it is describe here : https://www.notion.so/accelerateur-transition-ecologique-ademe/Footer-Mentions-L-gales-Accessibilit-protection-des-donn-s-CGU-4d87485fb6834d6399408e62f23b5ba7
> Create footer pages

- jinja2/layout/footer.html
> reorder the footer page links

- jinja2/editorial/cookies.html
- jinja2/editorial/personal_data.html
About table:
and resolve a typo «Longue viea ux objets» to «Longue vie aux objets»
> Better table presentation and fix typo

- jinja2/qfdmo/partials/display_solutions.html
This reverts commit 23fc322cff129090f2534e018ce0e8a706eaf9aa.
Because it has a bad side effect : map is no more displayed on mobile
> Revert "display 400 px height screen for digital POI (#370)"

- bin/post_deploy
- bin/start
iframe.js should be copied on every nodes
> fix iframe.js access

- core/jinja2_handler.py
- core/utils.py
- dev-requirements.in
- dev-requirements.txt
- integration_tests/qfdmo/test_search_form.py
- qfdmo/views/display_solutions.py
- unit_tests/core/test_jinja2_handler.py
Manage default `direction` and `first_dir` even when the parameter isn't well set !
cf. https://sentry.incubateur.net/organizations/betagouv/issues/86883/?alert_rule_id=74&alert_timestamp=1708072966803&alert_type=email&environment=staging&project=115&referrer=alert_email
> Manage default direction and first_dir

- jinja2/layout/base.html
- package-lock.json
- package.json
- static/to_compile/entrypoints/qfdmo.ts
- static/to_compile/src/browser_check.ts
Browser version should be adjusted
```
// declare browsers and versions you want to support
// 2017
chrome: ">60",
// 2017
firefox: ">55",
// 2017
safari: ">10",
// 2019
opera: ">50",
edge: ">15",
ie: "none",
```
To be discussed, the message can be displayed on top of everything
> Display an alert notification when JS is deactivated

- static/to_compile/src/search_solution_form_controller.ts
Do not scroll to form when the ifrrame is loaded
> deactivate scroll onload iframe

- .gitignore
- qfdmo/forms.py
-Changed the width value for the segmented control component from 250px to auto so that it fit the new naming "Je recherche un objet" / "J'ai un objet" on the research part
> modified "250px" to "auto" value for segmented control width

- core/jinja2_handler.py
- jinja2/qfdmo/adresse/detail.html
display tab only with content, display distance, don't display itinerary for digital acteur
> display enhancement on address details panel

- core/jinja2_handler.py
rounded by 10 m below 1 km
rounded by 100 m above 1 km
without space inside the parenthesis
numbers with comma instead of dot
> display rounded distance

- dags/create_final_actors.py
> fix writing labels by create_final actor

- jinja2/qfdmo/adresse/detail.html
Using https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/carte#
> display bonus mention in the tab "A propos" too

- .github/workflows/run_tests.yml
following issue with Microsoft ubuntu repo, try to use ubuntu-latest again
> use ubuntu-latest

- .eslintrc.js
- package-lock.json
- package.json
- qfdmo/urls.py
- static/to_compile/src/browser_check.ts
- static/to_compile/src/search_solution_form_controller.ts
- static/to_compile/tests/choose_action_controller.test.ts
- tsconfig.json
- "eslint-config-love" in place of "eslint-config-standard-with-typescript"
- adding "eslint-plugin-prettier"
- update config
- update static/to_compile/src/browser_check.ts
> update eslint suite of package

- jinja2/qfdmo/iframe_configurator.html
- jinja2/qfdmo/partials/featureflip_inputs.html
- qfdmo/forms.py
- qfdmo/views/adresses.py
Be able to choose the address placeholder while configuring iframe
> Add address_placeholder parameter to configure iframe

- e2e_tests/iframe/action_list.spec.ts
- static/to_compile/src/search_solution_form_controller.ts
- static/to_compile/src/ss_cat_object_autocomplete_controller.ts
Missing the condition to test if the action is checked
Adding tests
> Selection of `jecherche` actions is not well set

- integration_tests/qfdmo/test_reemploi_solution.py
- jinja2/qfdmo/_addresses_partials/carte_header.html
- jinja2/qfdmo/_addresses_partials/filters/carte_filters.html
- jinja2/qfdmo/_addresses_partials/filters/carte_legend.html
- jinja2/qfdmo/_addresses_partials/filters/iframe_advanced_filters.html
- jinja2/qfdmo/_addresses_partials/filters/panel_filters.html
- jinja2/qfdmo/_addresses_partials/map_and_detail.html
- qfdmo/forms.py
- qfdmo/views/adresses.py
- static/to_compile/src/search_solution_form_controller.ts
following figma : 
https://www.figma.com/design/5JebAm7BkWvC6lMMkOu6nN/%F0%9F%AA%91-LVAO---Espace-de-travail?node-id=265-3415&m=dev
Add the legend always visible in desktop, on clique the checkbox, the selection is applied
> Desktop : always display legend and apply submit on (un)check

- static/to_compile/entrypoints/carte.ts
> the default width of La Carte should be 100 %

- jinja2/qfdmo/_addresses_partials/map_and_detail.html
> Add a 2w x padding on card when displayed on mobile

- jinja2/qfdmo/_addresses_partials/filters/_labels_filters.html
- jinja2/qfdmo/_addresses_partials/filters/panel_filters.html
- jinja2/qfdmo/_addresses_partials/map_and_detail.html
- jinja2/qfdmo/partials/action_list_by_direction.html
- jinja2/registration/login.html
- qfdmo/forms.py
- static/to_compile/entrypoints/qfdmo.css
- static/to_compile/src/autocomplete_controller.ts
- templates/django/forms/widgets/checkbox_option.html
- templates/django/forms/widgets/checkbox_select.html
following feedback here : https://www.notion.so/accelerateur-transition-ecologique-ademe/Test-Lucas-avant-MEP-Carte-ad7158b6805a42368d243c9c360adbd8?pvs=4 and here https://www.notion.so/accelerateur-transition-ecologique-ademe/Acc-s-au-configurateur-Atelier-111-da47ccc49b3e42da950c630afa5cd1d3
> small fix following feedback of te RC v1.33.0

- qfdmo/forms.py
Cf https://github.com/incubateur-ademe/quefairedemesobjets/commit/984bb4635340f29410471cb00194f8edefa5f8f3 
Il manquait le bon label
> Update configurator max width label to match recent update

- integration_tests/qfdmo/test_adresse_detail.py
- jinja2/qfdmo/adresse/detail.html
Ajout de la mention uniquement sur rendez-vous dans les fiches détaillées
> add uniquement sur rdv paragraph in adresse detailed view

- qfdmo/models/categorie_objet.py
Ref https://www.notion.so/accelerateur-transition-ecologique-ademe/Afficher-uniquement-les-gestes-relatifs-la-direction-j-ai-dans-la-l-gende-et-sur-la-carte-47a540f1735840afb2a1a5515f74081d?pvs=4 
Prise en compte de la direction (j'ai) pour la carte affichée dans Que Faire
> add direction in carte url

- qfdmd/admin.py
- qfdmd/management/commands/import_data_ademe.py
Pour peupler la base de produits Ademe, on interroge la base de données Ademe via une commande Django
> Add command to get data ademe products

- static/to_compile/entrypoints/carte.ts
- static/to_compile/entrypoints/iframe.ts
- static/to_compile/entrypoints/iframe_functions.ts
related to [notion ticket](https://www.notion.so/accelerateur-transition-ecologique-ademe/Les-2-versions-de-l-iFrame-s-affichent-sur-le-configurateur-de-Prod-4a22f401946a43de8c3dbc837b6b8d84?pvs=4)
> Extract functions to don't call the iframe builder twice

- .github/workflows/run_tests.yml
> Remove e2e tests timeout

- qfdmd/api.py
- qfdmo/models/categorie_objet.py
- Meilleure gestion des 404 lorsque le produit QFDMD n'a pas été configuré côté Django
> Better handle 404 on qfdmd products

- dags/cma.py
> Remove cma_utils dependance

- static/to_compile/src/analytics.ts
following the Posthog doc : 
* https://posthog.com/tutorials/cookieless-tracking
> deactivate posthog cookie and localhost

- unit_tests/dags/utils/dag_eo_utils_test.py
Better tests about create_labels
> Refactorize and complete create_labels function tests

- qfdmo/models/acteur.py
- qfdmo/models/action.py
- qfdmo/models/categorie_objet.py
- unit_tests/qfdmo/test_acteur.py
- unit_tests/qfdmo/test_acteur_service.py
- unit_tests/qfdmo/test_acteur_type.py
- unit_tests/qfdmo/test_action.py
- unit_tests/qfdmo/test_categorie.py
- unit_tests/qfdmo/test_proposition_service.py
- unit_tests/qfdmo/test_source.py
- unit_tests/qfdmo/test_sous_categorie.py
Carte Notion : N/A
Les fonctions `serialize` n'étant plus utilisée, je vous propose de les supprimer
N/A
N/A
N/A
> Suppression des fonction  et des tests associés

- README.md
Carte Notion : N/A
- Ajout d'une section convention de code dans notre README
N/A
N/A
N/A
> Ajout de documetation à propos de l'utilisation du francais et de l'anglais

- static/to_compile/entrypoints/qfdmo.css
Tout est dans le titre...
- Focus quelque chose, il n'y a pas de cadre rouge autour...
> Suppression d'un cadre rouge de debug mergé accidentellement

- jinja2/qfdmo/_addresses_partials/carte_header.html
- jinja2/qfdmo/_addresses_partials/iframe_form.html
Carte Notion : N/A
J'ai remarqué que les champs de recherche sur le mode formulaire n'étaitent pas parfaitement alignés
- Visualiser le formulaire
> Alignement des champs du formulaire en mode formulaire

- .github/workflows/run_tests.yml
- .gitignore
- core/settings.py
- e2e_tests/iframe.spec.ts
- jinja2/qfdmo/_addresses_partials/map_and_detail.html
- jinja2/tests/iframe.html
- package-lock.json
- package.json
- static/to_compile/entrypoints/iframe_functions.ts
- static/to_compile/src/analytics.ts
- static/to_compile/src/map_controller.ts
- static/to_compile/src/solution_map.ts
Carte Notion : [Problème au 1er chargement de la carte sur sites intégrés - reproduit suite à MEP](https://www.notion.so/accelerateur-transition-ecologique-ademe/Probl-me-au-chargement-de-la-carte-sur-sites-int-gr-s-retester-suite-MEP-a252d6e3f6cc418fa28347edd9618c1a?pvs=4)
> ce qui est probable c'est qu'au premier chargement le html soit pas 100% prêt, et que du coup l'execution du script plante (sans erreur, c'est pas un vrai plantage mais un calcul qui se fait trop tôt) 
> 
> https://codepen.io/fabienheureux/pen/RwzeVVJ
> 
> j'ai reproduit ici, si tu cliques dans la zone violette on a le soucis de loiret.fr
> 
> et du coup dans les autres cas, au deuxieme chargement, ce qui peut se produire c'est qu'une partie de la page soit issue du cache navigateur > ca va plus vite > le calcul …
> Permet à la carte de recalculer ses limites lorsque la largeur du conteneur change

- unit_tests/qfdmo/acteur_factory.py
- unit_tests/qfdmo/test_acteur.py
Dans les test on s'assure que le code est unique avec un get_or_create dans la factory ActeurServiceFactory
> Dans les tests, on doit s'assurer que le code de l'acteurservice est unique

- qfdmd/management/commands/import_data_ademe.py
Le script avait été supprimé dans #753 mais il est requis pour créer de nouveaux produits. 
> Ajout du script d'import des données data ademe

- qfdmo/admin/acteur.py
Mini fix d'une regression lors de la dernière mise en prod
- Créer un RevisionActeur
> Résolution de la créaton d'acteur dans l'admin

- core/settings.py
- requirements.in
- requirements.txt
Régression du à la monté de version de la lib django-import-export
- …
- ...
- ...
> Permettre l'import et export en excel

- integration_tests/qfdmo/test_adresse_detail.py
- qfdmo/views/adresses.py
Petite regression qu'on a laissé passé
- …
- ...
- ...
> Afficher les tabs de la fiche détaillée de l'acteur que si il y a quelque chose à afficher

- .github/workflows/sync_databases.yml
Carte Notion : [Synchroniser la base de Prod avec Preprod 1 fois par semaine](https://www.notion.so/accelerateur-transition-ecologique-ademe/Synchroniser-la-base-de-Prod-avec-Preprod-1-fois-par-semaine-4285b5af8dc845389975f743e5c80187?pvs=4)
2 actions en plus:
- Après copie des bases de données de preprod vers prod, on doit lancer les migrations en preprod
- Copie du repo s3 de prod vers preprod
Attention, les variables d'environnement pour Github action doivent être configurer :
- S3_HOST
- S3_PREPROD_BUCKET
- S3_PRODUCTION_BUCKET
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- …
- …
> Lancement des migrations et copy de s3

- core/jinja2_handler.py
- core/settings.py
- core/test_settings.py
- core/utils.py
- integration_tests/core/test_display_as_iframe.py
- integration_tests/qfdmo/test_reemploi_solution.py
- integration_tests/qfdmo/test_search_form.py
- pyproject.toml
- qfdmo/forms.py
- qfdmo/models/acteur.py
- qfdmo/models/action.py
- qfdmo/views/adresses.py
- unit_tests/core/test_jinja2_handler.py
- unit_tests/core/test_utils.py
- unit_tests/qfdmo/test_acteur.py
- unit_tests/qfdmo/test_action.py
- unit_tests/qfdmo/test_addresses_view.py
Utilisation du cache Django plutôt que de ré-inventer la roue :)
- …
- ...
- ...
> Optimize DB calls on main page using cache

- dags/config/db_mapping.json
- dags/utils/dag_eo_utils.py
Carte notion : [LVAO : Re-mapper les points d’apport OCAB - manque une sous-cat’ (Membranes Bitumineuses)](https://www.notion.so/accelerateur-transition-ecologique-ademe/LVAO-Re-mapper-les-points-d-apport-OCAB-manque-une-sous-cat-Membranes-Bitumineuses-1066523d57d780429ac7c8919e50c0e0?pvs=4)
Lorsqu'on fait tourner le DAG d'intégration des acteur de l'OCAB, il manque les `membranes bitumineuse` et les produits vides ` ` sont interprété, cela lève une erreur (ce qui est bien pour éviter les erreurs silencieuses)
Cette PR corrige l'erreur de l'OCAB
- …
- Réinstaller les dépendances Python …
> Résolution des problèmes de manque de produit pour l'OCAB

- dags/aliapur.py
- dags/cma.py
- dags/corepile.py
- dags/create_final_actors.py
- dags/ecodds.py
- dags/ecologic.py
- dags/ecomaison.py
- dags/ecosystem.py
- dags/ocab.py
- dags/pyreo.py
- dags/refashion.py
- dags/soren.py
- dags/utils/dag_eo_utils.py
- dags/utils/db_tasks.py
- dags/utils/eo_operators.py
- dags/valdelia.py
- dags_unit_tests/dags/utils/test_dag_eo_utils.py
Refacto et réorganisation des taches de l'ingestion des Eco-Organisme
Pas mal de code mutualisé, 
`+` une optimisation : On ne va charger en DB que les acteurs affichés des sources concernées (nécessaire pour distinguer les acteurs qui ont été supprimé)
- …
- ...
- ...
> Refacto dags eo

- dags/aliapur.py
- dags/cma.py
- dags/corepile.py
- dags/create_final_actors.py
- dags/ecodds.py
- dags/ecologic.py
- dags/ecomaison.py
- dags/ecosystem.py
- dags/ocab.py
- dags/pyreo.py
- dags/refashion.py
- dags/soren.py
- dags/utils/dag_eo_utils.py
- dags/utils/db_tasks.py
- dags/utils/eo_operators.py
- dags/valdelia.py
- dags_unit_tests/dags/utils/test_dag_eo_utils.py
Quelques refacto, 1 par commit :)
- …
- ...
- ...
> Refactorisation des dags, renommages et simplifications

- dags/create_final_actors.py
Juste un peu de texte pour decrire le dag create_final_actors
- …
- ...
- ...
> Juste un peu de texte pour decrire le dag create_final_actors

- notebooks/__init__.py
- notebooks/depuplicate_from_xlsx.ipynb
Carte Notion : [merger des clusters d’acteurs validés - 2 datasets pour commencer](https://www.notion.so/accelerateur-transition-ecologique-ademe/merger-des-clusters-d-acteurs-valid-s-2-datasets-pour-commencer-c3cae5935cb84e2dadb20e152aeb7a77?pvs=4)
Dans cette PR, on écrit un notebook qui servira de base à l'intégration de cohorte de déduplication de manière automatisée.
On part d'un CSV dont l'information essentil et exploité est le cluster_id associé à un ensemble d'acteurs référencés par leur `identifiant_unique`
Le process de déduplication:
1. Création et enrichissement des clusters
* On récupère les acteurs de chaque cluster
* On récupère leur parent (si ils sont déjà dédupliqué)
* On récupère les enfants des parents (si il y a des enfants qui ne font pas parti des cohorte)
2. …
> Creation d'un notebook pour dédupliquer les acteur à partir d'un fichier xlsx

- qfdmo/forms.py
erreur de merge, on appelait une fonction asynchrone dans la définition d'un formulaire...pas ouf ouf. 
Le code est interprété à l'initialisation de l'app et ça génère des erreurs dans tous les sens
> Fix preprod issue

- .github/pull_request_template.md
Proposition de simplifiction du template de PR
- …
- ...
- ...
> Mise à jour du Template de PR : simplification

- sync_dags.sh
Le script de synchro des dags ne marche pas en preprod et enprod, alors qu'il marche en local.
donc on ajoute des logs pour compredre ce qui ce passe
- …
- ...
- ...
> Ajoute de log (echo) por comprendre pourquoi le script ne marche pas

- Makefile
> Mis à jour du makefile, ajout commande et corrction de typo

- .secrets.baseline
- core/logging.py
- core/settings.py
- qfdmo/forms.py
- qfdmo/models/acteur.py
- qfdmo/views/adresses.py
- qfdmo/views/configurator.py
Suite à la mise en staging du configurateur collectivité, une régression est à corriger 
- Une fois la carte affichée, le décochage d'un groupe d'actions en desktop se rafraîchit avec l'action toujours cochée
- Le _cochage_ d'actions possibles par l'utilisateur n'était pas reflété dans la carte
Deux soucis ici : 
- Une régression dans la PR des codes EPCI : on mixait à la fois la récupération de valeur dans la requête et dans le formulaire. Je suis allé un peu trop loin dans la précédente refacto
- Le nom du champ utilisé dans le configurateur ne correspondait pas à celui utilisé dans le formulaire adresse. Un simple renommage suffit pour corriger le soucis 
J'ai du débuguer du code python et ai revu le fonctionnement du logger 
- Ajout d'un filtre qui exclut les fichiers statiques des …
> Fix epci legend grouped action regression

- notebooks/depuplicate_from_xlsx.ipynb
Carte Notion : [merger des clusters d’acteurs validés - 2 datasets pour commencer](https://www.notion.so/accelerateur-transition-ecologique-ademe/merger-des-clusters-d-acteurs-valid-s-2-datasets-pour-commencer-c3cae5935cb84e2dadb20e152aeb7a77?pvs=4)
Pour que le parent ne change pas de uuid à chaque fois qu'il est recalculé
- …
> Calcul du uuid selon les identifiants unique des enfants

- static/to_compile/src/address_autocomplete_controller.ts
J'ai identifié une régression potentielle issue de #890. 
Ceci corrige cela...
> Fix potential issue in autocomplete controller

- qfdmo/views/adresses.py
Rollback de la lecture de la r-direction depuis la requete
- …
> get direction from request

- qfdmo/forms.py
Correction d'un texte dupliqué
> Correction d'un texte dupliqué dans le configurateur

- Makefile
- jinja2/qfdmo/iframe_configurator/base.html
- qfdmo/forms.py
- qfdmo/widgets.py
- tailwind.config.js
- templates/forms/widgets/autocomplete.html
- templates/forms/widgets/epci_codes_additionnal_info.html
- templates/forms/widgets/generic_autocomplete.html
- templates/forms/widgets/plain_text.html
Carte Notion : [Feedbacks configurateur](https://www.notion.so/accelerateur-transition-ecologique-ademe/Configurateur-simplifi-pour-les-collectivit-s-4db7e146958942bb973910d2e92e78a3?pvs=4)
- Actions disponibles par défaut, “je dépose en point de collecte” ne doit pas être coché par défaut mais affiché sur la prévisualisation (non coché)
- Revoir le nombre de résultats maximum par défaut (20), min (0) et max (100) ➕1️⃣
- “Résultat” au singulier
- Il manque le message bleu d’info sous le choix du code EPCI : un seul EPCI + lien vers le site de l’INSEE
- Typo : Ajouter un point à la fin de la phrase sous “choisissez les actions disponibles de vos usagers”
> Configurateur feedbacks batch 2

- jinja2/qfdmo/_addresses_partials/map_and_detail.html
Tout est dans le titre...comme quoi ça sert les code reviews.
> Remove accidental data-tested attribute added in legend

- static/to_compile/src/analytics.ts
Article : https://posthog.com/tutorials/fewer-unwanted-events
Carte Notion : [Diminution facturation Posthog ](https://www.notion.so/accelerateur-transition-ecologique-ademe/Facturation-Posthog-1276523d57d780f6a74ac20c2991747e?pvs=4)
Suppression du tracking des évènements de type autocapture : [https://posthog.com/tutorials/fewer-unwanted-events](https://posthog.com/tutorials/fewer-unwanted-events)
- …
> Suppression event autocapture Posthog

- .github/workflows/airflow_cd_prod.yml
- .github/workflows/airflow_deploy_dags.yml
- .github/workflows/airflow_tests.yml
- .github/workflows/ci.yml
- .github/workflows/lvao_cd_preprod.yml
- .github/workflows/lvao_cd_prod.yml
- .github/workflows/lvao_tests.yml
- .secrets.baseline
> refactor gh actions

- qfdmo/views/configurator.py
Tout est dans le titre (cf remontée Coline sur Mattermost)
> Remove login in front of configurateur view

- qfdmo/admin/acteur.py
Carte Notion : [Premier export des acteurs affichés pour une mise à disposition en open source sur data.ademe.fr](https://www.notion.so/accelerateur-transition-ecologique-ademe/Premier-export-des-acteurs-affich-s-pour-une-mise-disposition-en-open-source-sur-data-ademe-fr-1196523d57d780a28b18d2235110b20d?pvs=4)
La CMA a donné son autorisation, on peut maintenant partager les acteur réparacteur
- …
> La CMA accepte qu'on redistribue leur adresse labelisé réparacteur

- jinja2/layout/header.html
Changement header avec nouvelle raison d'être LVAO
Carte Notion : [Changement header et footer raison d’être LVAO](https://www.notion.so/accelerateur-transition-ecologique-ademe/Changement-header-et-footer-LVAO-1346523d57d780d5af8fe732728fe353?pvs=4)
- …
> Mise à jour header raison d'être LVAO

- README.md
> Ajout d'une section Sécurité dans le README.md

- jinja2/layout/base.html
Carte Notion : [Changement header et footer raison d’être LVAO](https://www.notion.so/accelerateur-transition-ecologique-ademe/Changement-header-et-footer-LVAO-1346523d57d780d5af8fe732728fe353?pvs=4)
- …
> Mise à jour base.html mission LVAO

- dags/utils/dag_eo_utils.py
- dags/utils/eo_operators.py
- dags_unit_tests/dags/utils/test_dag_eo_utils.py
Isolation dan sa propre tache des acteurs à supprimer + tests de cette tache
- …
> isoler la collecte des acteurs à supprimer

- e2e_tests/iframe.spec.ts
- jinja2/tests/iframe.html
J'aurais p-e du attendre que la CI termine avant de merger...
> fix e2e tests failing

- jinja2/qfdmo/acteur/tabs/labels_panel.html
Cf retours de Delphine, il manque des bordures autours des labels 
Ceci corrige cela 
> Ajout bordure autour des labels

- dags/sources/source_aliapur.py
- dags/sources/source_corepile.py
- dags/sources/source_ecodds.py
- dags/sources/source_ecologic.py
- dags/sources/source_ecomaison.py
- dags/sources/source_ecosystem.py
- dags/sources/source_ocab.py
- dags/sources/source_ocad3e.py
- dags/sources/source_pyreo.py
- dags/sources/source_refashion.py
- dags/sources/source_soren.py
- dags/sources/source_valdelia.py
- dags/utils/base_utils.py
- dags_unit_tests/dags/utils/test_base_utils.py
Carte Notion : [Intégrer base déchetteries SINOE dans la BD](https://www.notion.so/accelerateur-transition-ecologique-ademe/Int-grer-base-d-chetteries-SINOE-dans-la-BD-12e6523d57d7804394cad6e7bdcf95c6?pvs=4)
- Gestion de l'adresse au format BAN
- Renommage de OCAD3E
- Amélioration et test de la fonction d'interprétation de l'adresse au format BAN
- …
> Following sinoe

- qfdmd/admin.py
Ajout du mécanisme d'import / export pour les synonymes 
- …
> Add export in django admin for synonymes

- dags/utils/base_utils.py
- dags_unit_tests/dags/utils/test_base_utils.py
> Suppression de l'asterix sur le nom de la ville

- integration_tests/core/test_redirects.py
- qfdmo/views/adresses.py
On s'est loupé sur la redirection
- …
> Rediriger vers La Carte sur longuevieauxobjets.ademe.fr

- APPLICATION.md
Dans le but de centraliser la liste des applications maintenues par l'équipe
> référencement des applications maintenues par l'équipe LVAO

- qfdmo/management/commands/populate_sous_cat.py
Un détail mais qui a son importance lors de l'execution du script si on veut que ce soit lisible :)
- …
> typo min vs max

- qfdmo/fixtures/acteur_services.json
- qfdmo/fixtures/acteur_types.json
- qfdmo/models/acteur.py
- unit_tests/core/test_jinja2_handler.py
- unit_tests/qfdmo/test_acteur.py
Lors du renommage du code de l'acteur type `acteur digital` -> `acteur_digital`, il y avait des loupés dans le code.
On a donc eu des erreurs comme relevé par Christian ici : https://mattermost.incubateur.net/betagouv/pl/7439jpy6r7bq8kitt1mqw9kt7e
- …
> Modification des codes des acteurtypes dans le code

- Makefile
- e2e_tests/advanced_filters.spec.ts
- jinja2/qfdmo/_addresses_partials/filters/panel_filters.html
- jinja2/qfdmo/carte/_digital_results.html
- jinja2/qfdmo/carte/header.html
- jinja2/qfdmo/carte/panels/legend.html
- jinja2/qfdmo/formulaire.html
- jinja2/qfdmo/formulaire/search_form.html
- jinja2/qfdmo/formulaire/update_search.html
- jinja2/qfdmo/shared/main.html
- jinja2/qfdmo/shared/results.html
- qfdmo/fixtures/acteur_types.json
- qfdmo/fixtures/acteurs.json
- qfdmo/fixtures/categories.json
- qfdmo/models/lvao.py
- static/to_compile/css/base.css
- static/to_compile/js/helpers.ts
- static/to_compile/js/map_controller.ts
- static/to_compile/js/search_solution_form_controller.ts
- static/to_compile/js/solution_map.ts
- static/to_compile/tests/choose_action_controller.test.ts
Corrige plusieurs retours sur la nouvelle fiche détaillée 
- [La touche “Echap” ne devrait pas ouvrir la modale des filtres](https://www.notion.so/accelerateur-transition-ecologique-ademe/La-touche-Echap-ne-devrait-pas-ouvrir-la-modale-des-filtres-13d6523d57d780cb822dca4b3bebb73d?pvs=4)
- [[Liste acteurs en ligne] - Sur mobile, impossible de faire défiler les acteurs en ligne](https://www.notion.so/accelerateur-transition-ecologique-ademe/Liste-acteurs-en-ligne-Sur-mobile-impossible-de-faire-d-filer-les-acteurs-en-ligne-1436523d57d7801ab30cf5a74391ba5b?pvs=4)
- [[Formulaire] Le bouton “Proposer une adresse” ne doit apparaître que sur les résultats / carte](https://www.notion.so/accelerateur-transition-ecologique-ademe/Formulaire-Le-bouton-Proposer-une-adresse-ne-doit-appara-tre-que-sur-les …
> Fiche détaillée - 2ème vague de retours 

- dags/sources/config/airflow_params.py
- dags/sources/dags/source_soren.py
- dags/sources/tasks/airflow_logic/config_management.py
- dags/sources/tasks/airflow_logic/source_data_normalize_task.py
- dags/sources/tasks/business_logic/source_config_validate.py
- dags/sources/tasks/business_logic/source_data_normalize.py
- dags/sources/tasks/transform/__init__.py
- dags/sources/tasks/transform/transform_column.py
- dags_unit_tests/sources/tasks/airflow_logic/test_config_management.py
- dags_unit_tests/sources/tasks/business_logic/test_source_config_validate.py
- dags_unit_tests/sources/tasks/business_logic/test_source_data_normalize.py
Carte Notion : [Importer le fichier v4 Soren](https://www.notion.so/accelerateur-transition-ecologique-ademe/Importer-le-fichier-v4-Soren-1426523d57d780638e06f4b4679470d6?pvs=4)
- …
> Transformation de la colonne horaire pour SOREN

- core/constants.py
- qfdmo/fixtures/acteur_types.json
- qfdmo/models/acteur.py
- unit_tests/core/test_jinja2_handler.py
- unit_tests/qfdmo/test_acteur.py
Cf erreur Sentry https://sentry.incubateur.net/organizations/betagouv/issues/133052/events/2f32354a9e204644839d13ede8596722/?project=115 
**Problème :** on se base sur l'id de l'acteur en ligne, qui est hardcodé à 0 dans le code et vaut 5 en prod. 
Je propose de se baser sur le champ `code` qui est supposé immutable. 
J'essaye de comprendre ce qui n'allait pas, j'ai ouvert une autre PR en draft pour isoler le problème : https://github.com/incubateur-ademe/quefairedemesobjets/pull/1076/files 
De ce que je comprends quand je décompose :
```py
@classmethod
def get_digital_acteur_type_id(cls) -> int:
if not cls._digital_acteur_type_id:
(digital_acteur_type, _) = cls.objects.get_or_create(code="acteur_digital")
cls._digital_acteur_type_id = digital_acteur_type.id
return …
```
> Ne plus utiliser d'ID hardcodé pour déterminer les acteurs en ligne

- core/settings.py
utiliser une nouvelle connection à la base de données toutes les minutes pour éviter que les requête idle qui ne ferment pas les connexions
- …
> Gestion des nb de connections à la base de données

- core/urls.py
- integration_tests/qfdmo/test_acteur_detail.py
- integration_tests/qfdmo/test_adresses_view.py
- qfdmo/views/adresses.py
https://www.notion.so/accelerateur-transition-ecologique-ademe/Des-fiches-acteurs-INACTIF-et-SUPPRIM-sont-index-s-sur-Google-1516523d57d78022bd99cb9fc0e06ce4?pvs=4
Émission de redirections pour tous les acteurs inactifs précédemment référencés dans Google 
Au passage...on les vire du sitemap 
> Suppression des acteurs inactifs des index de moteurs de recherche 

- core/settings.py
- qfdmo/urls.py
- qfdmo/views/__init__.py
Pour https://www.notion.so/accelerateur-transition-ecologique-ademe/Des-fiches-acteurs-INACTIF-et-SUPPRIM-sont-index-s-sur-Google-1516523d57d78022bd99cb9fc0e06ce4?pvs=4 
On a besoin d'ajouter la Google Search Console, la validation peut se faire par plusieurs méthodes, j'ai choisi le fichier HTML. 
Cf https://support.google.com/webmasters/answer/9008080#html_verification&zippy=%2Chtml-file-upload 
> Ajout de la Google Search Console sur LVAO

- qfdmo/management/commands/export_displayedacteur.py
Carte Notion : [Faire un nouvel export open data en excluant les sources sans accord (licence ouverte)](https://www.notion.so/accelerateur-transition-ecologique-ademe/Faire-un-nouvel-export-open-data-en-excluant-les-sources-sans-accord-licence-ouverte-14b6523d57d780278ad4ec12505d2065?pvs=4)
A la fin de l'export on enrgistre le fichier sur le repo s3
- …
> Enregistrement de l'export sur le repo s3

- dags/ingest_validated_dataset_to_db.py
- dags/sources/config/shared_constants.py
- dags/sources/dags/source_aliapur.py
- dags/sources/dags/source_cma.py
- dags/sources/dags/source_corepile.py
- dags/sources/dags/source_ecodds.py
- dags/sources/dags/source_ecologic.py
- dags/sources/dags/source_ecomaison.py
- dags/sources/dags/source_ecosystem.py
- dags/sources/dags/source_ocab.py
- dags/sources/dags/source_ocad3e.py
- dags/sources/dags/source_pyreo.py
- dags/sources/dags/source_refashion.py
- dags/sources/dags/source_soren.py
- dags/sources/dags/source_valdelia.py
- dags/sources/tasks/business_logic/propose_acteur_to_delete.py
- dags/sources/tasks/business_logic/source_data_normalize.py
- dags/utils/dag_eo_utils.py
- dags/utils/dag_ingest_validated_utils.py
- dags/utils/mapping_utils.py
- dags/utils/shared_constants.py
- dags/utils/siret_control_utils.py
- qfdmo/models/acteur.py
- qfdmo/models/data.py
Déclaration de constantes partagées et déplacement du fichiers
- …
> Ajout de constantes partagées

- static/to_compile/entrypoints/qfdmd.css
- templates/components/produit/_detail.html
- templates/qfdmd/synonyme_detail.html
Nouvelle vague de retours sur le responsive (remontés ou non par l'équipe)
- Amélioration du rendu des icônes sur la homepage 
- Amélioration du responsive de la carte sur les produits 
> Assistant V2 - Responsive - Nouvelle vague

- jinja2/qfdmo/carte/panels/legend.html
problem with "à propos", in responsive, it doesn't fit
- …
> updated "à propos" to "infos"

- qfdmd/admin.py
Carte : https://www.notion.so/accelerateur-transition-ecologique-ademe/AST-0-4-Synchro-LVAO-Koumoul-data-ademe-admin-dans-Django-1216523d57d78031bab1d1e1bdf2b091?pvs=4 
**Modification de l'export django** pour ajouter des fonctionnalités liées à **Koumoul** : 
- Ajout d'un **mapping** `{ "nom_champ_django": "nom_champ_koumoul" }`
- Modification de la génération des champs pour garantir qu'ils n'intègrent **que les champs Koumoul** présents dans le mapping (cela génère sinon des erreurs) 
- Ajout d'une option pour choisir l'un ou l'autre des exports 
- testé avec Christian sur Koumoul : export depuis mon local. import sur Koumoul. C'est bien passé 🎉
> Ajout d'un export spécifique à Koumoul

- docs/comment-faire/201-production-rollback.md
- docs/comment-faire/README.md
Suite à un soucis de production, nous avons dû réstaurer la version précédente.
Nous en avons donc profité pour écrire a procédure de restauration
- …
> Ajout du processus de rollback dans les docs

- qfdmo/models/acteur.py
La PR précédente a été auto-mergé trop tôt !
commentaire : https://github.com/incubateur-ademe/quefairedemesobjets/pull/1185#discussion_r1907416682
- …
> Prise en compte du commentaire de Fabien

- dags/sources/config/db_mapping.json
- dags/sources/dags/source_ecopae.py
Carte Notion : [Importer le fichier v1 ECOPAE (PCHIM) dans LVAO](https://www.notion.so/accelerateur-transition-ecologique-ademe/Importer-le-fichier-v1-ECOPAE-PCHIM-dans-LVAO-1726523d57d78001bb72cc55ed2aa016?pvs=4)
Attention, à la dépendance à la PR #1174 qui gère la colonne location dans la liste des transformations
- …
> Ajout de la source ECOPAE

- dags/sources/config/db_mapping.json
- dags/sources/dags/source_cyclevia.py
Carte Notion : [Importer le fichier v1 Cyclevia (LUB) dans LVAO](https://www.notion.so/accelerateur-transition-ecologique-ademe/Importer-le-fichier-v1-Cyclevia-LUB-dans-LVAO-1756523d57d78030841bcc7540ea4f74?pvs=4)
Ajout de la source Cyclevia
- …
> Ajout de la source Cyclevia

- .github/workflows/run_tests.yml
- Makefile
- e2e_tests/accessibility.spec.ts
- jinja2/qfdmo/shared/main.html
- qfdmd/fixtures/produits.json
- qfdmd/fixtures/synonymes.json
- static/to_compile/entrypoints/assistant/script-to-iframe.ts
- templates/components/footer/_standalone.html
- templates/components/header/header.html
- templates/components/logo/_base.html
- templates/components/produit/_detail.html
- templates/components/search/view.html
- templates/components/sidebar/action.html
https://www.notion.so/accelerateur-transition-ecologique-ademe/AST-1-Correction-accessibilit-Assistant-au-tri-11b6523d57d780dc83f6f44fcba872cc?pvs=4
- Dé-commenter les tests d'intégration
- Corriger soucis d'accessibilité détectés
- Ajouter fixtures pour les déchets
>  Accessibilite

- templates/components/header/header.html
> remove url_extra

- qfdmd/views.py
Carte Notion : [[Titre de la carte](https://notion.so/...)](https://www.notion.so/accelerateur-transition-ecologique-ademe/typo-URL-pour-les-pros-Ya-un-point-en-trop-la-fin-1826523d57d78096b34cf022fde94dba?pvs=4)
- …
> Suppression . à la fin de l'URL pour les pros

- .clever.json
- .github/workflows/cd_preprod.yml
- .github/workflows/cd_prod.yml
Remplace le déploiement des DAGs via s3 qui ne fonctionne pas
RAF : 
Tests : 
- ❌ Github action : https://github.com/incubateur-ademe/quefairedemesobjets/actions/runs/12862573483
- …
> Deploiement du cluster airflow sur clevercloud

- templates/components/footer/_standalone.html
Ajout dans la description pied de page
Carte Notion : [[Titre de la carte](https://notion.so/...)](https://www.notion.so/accelerateur-transition-ecologique-ademe/Existe-aussi-en-prod-Changer-quand-m-me-dans-footer-Que-faire-de-mes-d-chets-1826523d57d78094aaa4f8435aa42528)
- …
> Suppression qui sommes-nous

- .env.template
- .secrets.baseline
- core/settings.py
- core/views.py
- docker-compose.yml
- integration_tests/core/test_redirects.py
- qfdmd/views.py
- qfdmo/models/categorie_objet.py
- templates/components/search/view.html
**Dernières petites choses suite à la MEP de l'assistant :**
- nouvelle variable d'env pour définir l'url de l'assistant dans l'interface 
- on rend - pour le moment - la redirection non permanente afin d'éviter de la cacher côté navigateur si on détecte de nouveaux soucis de routing (déployé en prod en hotfix)
- mini bugfix de css
> Derniers ajustements après mise en prod assistant v2

- templates/components/footer/_standalone.html
Un "." placé un peu tôt et le lien Github n'est plus bon
- …
> Correction point dans Footer et lien Github

- dags/sources/config/db_mapping.json
Nous mappons, à tort, le matériel informatique au PAM (my bad). Je le bouge au GEM hors froid.
- …
> Remapping du "materiel informatique" de "PAM" vers "gem hors froid"

- qfdmo/models/acteur.py
> Debug erreur post compile clever cloud

- dags/sources/tasks/business_logic/db_data_prepare.py
Permettre la mise à jour des acteurs avec latitude et longitude vide
- Correction de la jsonification des valeur NaN : transformation e None avant de jsonifier
- …
> remplacer les valeurs NaN en None pour la jsonification

- dags/sources/dags/source_ecopae.py
- dags/sources/dags/source_ocad3e.py
- dags/sources/dags/source_refashion.py
- dags/sources/tasks/business_logic/source_data_normalize.py
- dags_unit_tests/sources/tasks/business_logic/test_source_data_normalize.py
Pour être plus robuste lors de l'ingestion de source, convertir les données qui décrivent des valeurs vides en chaine vide
- …
> Suppression des valeurs explicitement nulles

- .pre-commit-config.yaml
> Mise à jour des versions de packages de precommit

- .github/workflows/cd_preprod.yml
> Correction d'une typo dans le webhook mattermost

- dags/.env.template
- dags/cluster/tasks/business_logic/cluster_acteurs_suggestions/contexte.py
- dags/utils/django.py
Clean up avec Max
**🗺️ contexte**: Airflow DAGs
**💡 quoi**: amélioration, config, suppression fonction morte, suppression des warning
**🎯 pourquoi**: moins de bruit
- réorganisation du template .env.template par block
- suppression de la fonction django_launch_partial ou quelques chose comme ça qui n'est pas utilisé
- chargement des librairies dans les fonctions
- suppression de typing pour les type Django
> Suppression des warnings du DAG et organisation de .env.template

- data/admin.py
- qfdmo/admin/acteur.py
* Ajout de l'encodage de la Pk sur les liens vers l'admin
* Gestion de la depreciation de l'utilisation de format_html
- …
> Ajout de l'encodage de la Pk sur les liens vers l'admin + gestion de la depreciation de l'utilisation de format_html

- dags/views/view_acteur_tous.py
Carte Notion : [Vue Metabase n’update plus le nombre d’acteurs parent (is_parent)](https://www.notion.so/accelerateur-transition-ecologique-ademe/Vue-Metabase-n-update-plus-le-nombre-d-acteurs-parent-is_parent-19f6523d57d780109848ebbc6eb3565f?d=1a06523d57d7805ea518001c6a087f3e)
**🗺️ contexte**: en attendant DBT, on gère des vues acteurs via Airflow
**💡 quoi**: quelques modifs pour améliorer la stabilité de la vue
**🎯 pourquoi**: elle échouait de manière sporadique avec:
https://stackoverflow.com/questions/54351783/duplicate-key-value-violates-unique-constraint-postgres-error-when-trying-to-c
**🤔 comment**: ajout de la solution de l'article ci-dessus + délai supplémentaire entre suppression et création. **Je ne perds pas trop de temps là dessus sachant que DBT arrive**
- petite modif: …
> :eye: Vue acteurs: améliorer stabilité

- dags/cluster/tasks/business_logic/misc/df_metadata_get.py
clarification wording
**💡 quoi**: 
> clarification des mentions dans les metadata des cohortes du clustering

- dbt/models/source/source_acteur.yml
**🗺️ contexte**: DBT - suite des tests en preprod
**💡 quoi**: impossible de lire les sources
**🎯 pourquoi**: on cherche dnas la base de données nommé `qfdmo`
**🤔 comment**: supprimer la mention de la base de donnée, il cherchera dans la DB par défaut
> La DB ne doit pas être précisée car différente selon les environnement

- docs/reference/data/clustering_deduplication.md
Carte Notion: [doc / specs : expliquer clustering & déduplication ](https://www.notion.so/accelerateur-transition-ecologique-ademe/doc-specs-expliquer-clustering-d-duplication-1926523d57d78053826ec7109cf24c21)
**🗺️ contexte**: on a livré https://github.com/incubateur-ademe/quefairedemesobjets/pull/1359
**💡 quoi**: on met à jour la doc conformément
**🎯 pourquoi**: améliorer la maintenabilité du projet
**🤔 comment**:
- nouveau fichier dans `docs/reference/data`
- la doc a des liens vers les modèles de changement
Cliquer sur <a href="/incubateur-ademe/quefairedemesobjets/blob/main/data/models/changes/acteur_create_as_parent.py">acteur_create_as_parent</a>
<table><thead>
<tr>
<th>modèle de changement</th>
<th>Etat avant</th>
<th>Etat après</th>
<th>Scénario</th>
<th>Conséquences dans …
> :books: Docs sur clustering & déduplication

- dags/sources/config/airflow_params.py
- dags/sources/dags/source_s3.py
- dags/sources/tasks/airflow_logic/config_management.py
- dags/sources/tasks/airflow_logic/source_data_download_task.py
- dags/sources/tasks/business_logic/db_read_acteur.py
- dags/sources/tasks/business_logic/keep_acteur_changed.py
- dags/sources/tasks/business_logic/source_config_validate.py
- dags/sources/tasks/business_logic/source_data_download.py
- dags/sources/tasks/business_logic/source_data_normalize.py
- dags/sources/tasks/transform/transform_column.py
- dags_unit_tests/sources/tasks/airflow_logic/test_config_management.py
- dags_unit_tests/sources/tasks/business_logic/test_source_data_normalize.py
- dags_unit_tests/sources/tasks/transform/test_transform_column.py
Carte Notion/Mattermost/Sentry : [DjangoAdmin : Impossible d’uploader un fichier (import) → Possibilité d’importer via Scaleway+Airflow](https://www.notion.so/accelerateur-transition-ecologique-ademe/DjangoAdmin-Impossible-d-uploader-un-fichier-import-Possibilit-d-importer-via-Scaleway-Airflo-1b16523d57d780258dfdcaf9fa457d94?pvs=4)
**💡 quoi**: Permettre à Christian d'importer une nouvelle source à partir d'un bucket s3
**🎯 pourquoi**: L'import Django admin ne marche plus et est compliqué à utilisé
- Création et déclaration d'un nouveau repo s3
- Nouveau DAG source-s3
- Fonction clean_code_list
- Récupération de la liste des sous-cat depuis la DB pour la …
> Ingestion d'une source à partir d'un fichier xlsx sur s3

- dags/cluster/tasks/business_logic/cluster_acteurs_clusters.py
- dags_unit_tests/cluster/tasks/business_logic/test_cluster_acteurs_clusters.py
Tache tech car cette fonction n'est pas utilisée
**🗺️ contexte**: cluster
**💡 quoi**: suppression de la fonction cluster_strings : code mort
**🎯 pourquoi**: cleanup
**🤔 comment**: suppression du code : fonction et test
> Suppression de la fonction cluster_strings car elle n'est pas utilisée

- .slugignore
Correction du slugignore
**🗺️ contexte**: Scalingo/deploiement
**💡 quoi**: Suppression des fichiers inutils après le build
**🎯 pourquoi**: Limiter la taille du container
**🤔 comment**: correction du slugignore
> Suppression de static du slugignore

- core/constants.py
Diminution balsie title trop longue
Carte Notion/Mattermost/Sentry : [SEO] Changement balise title trop longue](https://www.notion.so/accelerateur-transition-ecologique-ademe/SEO-Changement-balise-title-trop-longue-1c26523d57d780eda304ee6e6a27bb07?pvs=4)
**💡 quoi**: 
> [SEO] Changement balise title trop longue

- .slugignore
- integration_tests/qfdmo/test_acteur_detail.py
- qfdmo/views/adresses.py
> Résolution d'une erreur Sentry causée par les acteurs non trouvés

- templates/404.html
- templates/500.html
Sentry : [KeyError](https://sentry.incubateur.net/organizations/betagouv/issues/161168/?environment=production&project=115&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0)
**🗺️ contexte**: Routage
**💡 quoi**: erreur lors du routage
**🎯 pourquoi**: On soupsonne le footer construit avec wagtail de casser sur les pages d'erreur 404 et 500
**🤔 comment**: Suppression du footer sur les pages 404 et 500
> suppression du footer pour les pages 500 et 404

- qfdmd/views.py
Carte Notion/Mattermost/Sentry : [KeyError](https://sentry.incubateur.net/organizations/betagouv/issues/160038/?environment=staging&project=115&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0)
**🗺️ contexte**: routage
**💡 quoi**: l'erreur 404 génére une 500
**🎯 pourquoi**: on cherche le resolver_match de la requete mais elle n'en a pas en 404
**🤔 comment**: ajout d'une condition
> fix page 404 qui génère une 500 car la requete n'a pas de resolver_match

- data/admin.py
Carte Notion/Mattermost/Sentry : [Les opérations sur les suggestions / cohortes génèrent des erreurs serveur - impossible de supprimer une grosse cohorte](https://www.notion.so/accelerateur-transition-ecologique-ademe/Les-op-rations-sur-les-suggestions-cohortes-g-n-rent-des-erreurs-serveur-impossible-de-supprimer-1926523d57d7809ea214cf53ef8f8ec1?pvs=4)
Ne pas afficher l'ensemble des suggestions qui seront supprimées
**💡 quoi**: Permettre la suppression de grosse cohorte
**🎯 pourquoi**: Par ce que aujourd'hui ce n'est pas possible, trop de suggestions sont affichées
**🤔 comment**: Surdéfinition de la fonction `get_deleted_objects` qui collecte les objets qui seront supprimés
> N'afficher qu'un échantillon des Suggestions à supprimer lors de la suppression de cohortes

- dags/sources/tasks/airflow_logic/db_data_prepare_task.py
- dags/sources/tasks/airflow_logic/db_write_type_action_suggestions_task.py
- dags/sources/tasks/airflow_logic/keep_acteur_changed_task.py
- dags/sources/tasks/airflow_logic/source_data_normalize_task.py
- dags/sources/tasks/business_logic/db_write_type_action_suggestions.py
- dags/sources/tasks/business_logic/keep_acteur_changed.py
- dags/sources/tasks/business_logic/source_data_normalize.py
- dags_unit_tests/sources/tasks/business_logic/test_keep_acteur_changed.py
- dags_unit_tests/sources/tasks/business_logic/test_source_data_normalize.py
- data/admin.py
Carte Notion : [[Suggestions] Vue Diff : améliorations v2](https://www.notion.so/accelerateur-transition-ecologique-ademe/Suggestions-Vue-Diff-am-liorations-v2-1986523d57d7809e80bdd3bfe08af59f?pvs=4)
**🗺️ contexte**: Django admin - Suggestion
**💡 quoi**: Affichage de metadata sur la cohorte
**🎯 pourquoi**: Données des indicateurs pou aider Christian dans son quotidien
**🤔 comment**: Cumule des metadonnées, comparaison des données mises à jour, enregistrement des métadonnées en DB sur l'objet suggestion
> Ajout de metadata aux cohortes de type Source

- docs/reference/README.md
- docs/reference/data/clustering-deduplication.md
**🗺️ contexte**: clustering & dédup
**💡 quoi**: amélioration doc
**🎯 pourquoi**: faciliter le transfert
**🤔 comment**:
- **correction liens cassés dans la doc**
- **ajout lien manquant dans l'index**
- **ajout d'info sur l'algo et les perfs**
- **renommage fichier**: `clustering_deduplication.md -> clustering-deduplication.md`
> # 📚 Clustering & dédup: amélioration doc

- .github/release-config.yml
- .github/workflows/release.yml
> Ajout "release drafter"

- core/views.py
- integration_tests/core/test_redirects.py
https://sentry.incubateur.net/organizations/betagouv/issues/170144/?alert_rule_id=74&alert_timestamp=1745474690263&alert_type=email&environment=staging&notification_uuid=48a333c1-e455-4177-a7ef-44072e15c221&project=115&referrer=alert_email
**🗺️ contexte**: Correction d'une régression introduite par #1321 
**💡 quoi**: rajout d'une redirection qui avait été supprimée par erreur 
**🎯 pourquoi**: je ne me souviens plus la raison qui avait motivé la suppression de la redirection dans la pr initiale, mais elle était manifestement infondée 
- rétablissement du code d'origine 
- rajout d'un test unitaire 
> 🐛 Correction d'une regression sur la redirection vers le CMS

- .github/workflows/ci.yml
- .github/workflows/publish-docs.yml
**🗺️ contexte**: CI/CD
**💡 quoi**:  Re-correction de l'action GH de déploiement de la doc + tentative de correction de l'action de CD
**🎯 pourquoi**: car c'est down.....
**🤔 comment**:
- suppression d'un attribut dupliqué dans l'action de docs (ma branche locale n'était pas à jour) 
- correction d'une conditionnelle pour un workflow qui ne tourne pas sur `main` (probablement lié à une variable undefined, on a pas de logs sur la `main`
> Re-correction de l'action GH de déploiement de la doc + tentative de correction de l'action de CD

- .github/workflows/cd.yml
Cf https://github.com/actions/runner/issues/1182 
On a un soucis de syntaxe sur cd.yml
> Supprimer les "yaml anchor" de cd.yml

- .github/workflows/ci.yml
> Suppression du run de la CI au push sur la main

- .github/workflows/cd.yml
correction d'une erreur de syntaxe dans cd.yml
> correction d'une erreur de syntaxe dans cd.yml

- .github/workflows/cd.yml
nouvelle erreur de syntaxe sur la CI/CD
Suite #1569 #1568 #1567 #1566
> Correction d'une nouvelle erreur de syntaxe sur la CI/CD

- .github/workflows/cd.yml
> Encore une correction de syntaxe dans la config CI/CD

- .github/workflows/ci.yml
temporarily kill e2e tests on main branch
> Désactiver les tests e2e sur la main temporairement 

- dags/sources/dags/source_soren.py
Quelques erreurs car le fichier a évolué
**🗺️ contexte**: Airflow source
**💡 quoi**: correction de la configuration pour l'ingestion d'une nouvelle version de Soren
**🎯 pourquoi**: Car c'est cassé
**🤔 comment**: Modification des paramètres par défaut pour l'ingestion de Soren
> Résolution de la configuration SOREN

- jinja2/qfdmo/acteur/tabs/sections/bonus.html
Ticket Notion : https://www.notion.so/accelerateur-transition-ecologique-ademe/Carte-Mettre-jour-le-lien-Bonus-R-paration-maintenant-que-la-page-est-live-1e56523d57d780849507f78744938662
**💡 quoi**: 
> Mise à jour du lien bonus réparation

- qfdmo/forms.py
Ticket Notion : https://www.notion.so/accelerateur-transition-ecologique-ademe/Carte-Mettre-jour-le-lien-Bonus-R-paration-maintenant-que-la-page-est-live-1e56523d57d780849507f78744938662
**💡 quoi**: 
> Mise à jour du lien bonus réparation légende

- dbt/models/marts/enrich/schema.yml
**🗺️ contexte**: pour gagner du temps et itérer, souvent je skip le rafraichissment dans Airflow, donc de temps à autre je manque des bugs
**💡 quoi**: correctif de schema
**🎯 pourquoi**: pour que DBT fonctionne bien au niveau des marts d'acteurs fermés
- `siret` -> `acteur_siret`
- `suggest_cohorte` -> n'existe que dans les modèles de suggestions
- **Purement syntaxe** `--empty` (https://docs.getdbt.com/docs/build/empty-flag) qui accélère le dev, mais reset à 0 les tables, et après il faut reconstuire AE/BAN de zero de toute façon
- :orange_circle: **limitation**: 0 donnée, tests ne tournent pas
- **Syntaxe + un peut de données**: j'ai commencé à en mettre (cf [DBT_SAMPLING](https://github.com/search?q=repo%3Aincubateur-ademe%2Fquefairedemesobjets%20DBT_SAMPLING&type=code)) …
> 💊 DBT: correctif schema marts closed

- .gitignore
- dbt/macros/table/macro_acteur.sql
- dbt/models/base/acteurs/schema.yml
- dbt/models/exposure/acteurs/carte/schema.yml
- dbt/models/exposure/acteurs/exhaustive/schema.yml
- dbt/models/intermediate/acteurs/int_acteur.sql
- dbt/models/intermediate/acteurs/schema.yml
- dbt/models/marts/acteurs/carte/schema.yml
- dbt/models/marts/acteurs/exhaustive/schema.yml
Ajout du champ ajouté récemment
**🗺️ contexte**: Airflow - DBT
**💡 quoi**: Ajout d'un champ
**🎯 pourquoi**: sinon ça plante
**🤔 comment**: ajout du champ dans les fichier SQL et les schema en yml
> ajout de siret_is_closed dans DBT

- dbt/models/marts/enrich/marts_enrich_acteurs_closed_candidates.sql
- dbt/models/marts/enrich/marts_enrich_acteurs_rgpd_suggest.sql
- dbt/models/marts/enrich/marts_enrich_acteurs_villes_candidates.sql
Carte Notion : 👇 
**🗺️ contexte**: Airflow RGPD
**💡 quoi**: Faire marcher le DAG des acteurs sous le coup de RGPD
**🎯 pourquoi**: application de la loi
**🤔 comment**: correction du modèle DBT qui ne fonctionnait pas
> Correction pour la gestion des acteurs à anonymiser pour des raisons RGPD

- dags/.airflowignore
- dags/clone/dags/clone_ae_etablissement.py
- dags/clone/dags/clone_ae_unite_legale.py
- dags/clone/dags/clone_ban_adresses.py
- dags/clone/dags/clone_ban_lieux_dits.py
- dags/cluster/dags/cluster_acteur_suggestions.py
- dags/enrich/dags/enrich_acteurs_closed.py
- dags/enrich/dags/enrich_acteurs_rgpd.py
- dags/enrich/dags/enrich_acteurs_villes.py
- dags/enrich/dags/enrich_dbt_models_refresh.py
- dags/tools/dags/airflow_cleanup_db.py
correction rapide car ça ne marchait pas
> Petit soucis d'import

- .github/workflows/publish-docs.yml
Erreur github : https://github.com/incubateur-ademe/quefairedemesobjets/actions/runs/15144437187/job/42613325839
**🗺️ contexte**: Déploiement
**💡 quoi**: Correction de github
**🎯 pourquoi**: car ça ne marche pas
**🤔 comment**: correction de .github
> Correction de la publication de la documentation

- .github/workflows/publish-docs.yml
Encore un petit loupé de publication
**🗺️ contexte**: Github Action - Documentation
**💡 quoi**: Résolution de pb
> Encore un fix de plublication de doc

- qfdmo/forms.py
Changement de adresse par lieu dans les filtres avancés
Carte Notion/Mattermost/Sentry : [Changement adresse par lieu](https://www.notion.so/accelerateur-transition-ecologique-ademe/Faire-PR-changement-adresse-lieu-2066523d57d7807e947ae2bc619f826d)
**💡 quoi**: 
> Changement de adresse par lieu dans les filtres avancés

- core/admin.py
- data/admin.py
Notion : 👇 
Correction de la mise à jour du statut de la cohorte lors de la validation ou rejet des suggestions
**🗺️ contexte**: Admin
**💡 quoi**: Correction de la mise à jour du statut de la cohorte
**🎯 pourquoi**: ça fonctionnait partiellement
**🤔 comment**: récupération de la liste des cohortes à mettre à jour plus explicite, interdire la suppression de suggestion
> Correction de la mise à jour du statut des cohortes

- package-lock.json
- package.json
This reverts commit 9e3a3835740b2e9df2f48f636fc3b074f24d77ae.
**💡 quoi**: 
> Revert "Bump @playwright/test from 1.49.1 to 1.52.0 (#1661)"

- .github/dependabot.yml
- docs/reference/infrastructure/provisioning.md
- docs/reference/infrastructure/scaleway.md
- infrastructure/.gitignore
- infrastructure/environments/backend/.terraform.lock.hcl
- infrastructure/environments/backend/main.tf
- infrastructure/environments/backend/variables.tf
- infrastructure/environments/preprod/.terraform.lock.hcl
- infrastructure/environments/preprod/backend.tf
- infrastructure/environments/preprod/main.tf
- infrastructure/environments/preprod/terraform.tfvars.example
- infrastructure/environments/preprod/variables.tf
- infrastructure/environments/preview/.terraform.lock.hcl
- infrastructure/environments/preview/backend.tf
- infrastructure/environments/preview/main.tf
- infrastructure/environments/preview/terraform.tfvars.example
- infrastructure/environments/preview/variables.tf
- infrastructure/environments/prod/.terraform.lock.hcl
- infrastructure/environments/prod/backend.tf
- infrastructure/environments/prod/main.tf
- infrastructure/environments/prod/terraform.tfvars.example
- infrastructure/environments/prod/variables.tf
- infrastructure/modules/backend/main.tf
- infrastructure/modules/backend/variables.tf
- infrastructure/modules/database/main.tf
- infrastructure/modules/database/variables.tf
Nous souhaitons maintenir la configuration de notre infrastructure en code (IaC : Infrastructure as Code) en utilisant l'hébergeur souverain Scaleway et le framework OpenTofu.
Cette première itération à pour objectif de :
* Créer l'architecture IaC dans le dossier `infrastructure` nous permettant de maintenir cette configuration
* Provisionner les base de données utilisées par nos applications (DB déjà existante)
Notion : [Refactorisation de l’architecture DB + Service](https://www.notion.so/accelerateur-transition-ecologique-ademe/Refactorisation-de-l-architecture-DB-Service-1ff6523d57d7808aab4dece8a3c856b9?source=copy_link)
**🗺️ contexte**: infrastructure
**💡 quoi**: Maintenir l'infrastructure Scaleway par du code
**🎯 pourquoi**: reproductibilité de l'infrastructure
**🤔 comment**: …
> Provisioning des bases de données avec OpenTofu

- dags/sources/config/db_mapping.json
- dags/sources/dags/source_ecologic.py
- dags/sources/tasks/transform/transform_df.py
Notion : 👇 
**🗺️ contexte**: Airflow - Source - Ecologic
**💡 quoi**: Nouvelle version de fichier Ecologic
**🎯 pourquoi**: Mise à jour
* Mise à jour des paramètres selon les colonnes
* Mise à jour de la table de mapping des produits
* Mini correction du décompte des lignes dupliquées
> adaptation de la confguration Ecologic

- templates/components/footer/_standalone.html
Changement texte intégration : cliquez sur le bouton à droite “</>”
Carte Notion/Mattermost/Sentry : [Bouton “Intégrer” sur QFDMOD ](https://www.notion.so/accelerateur-transition-ecologique-ademe/Bouton-Int-grer-sur-QFDMOD-2166523d57d7808c86d7f315a6e08e1e)
**💡 quoi**: 
> Changement texte intégration : cliquez sur le bouton à droite “</>”

- docs/reference/README.md
- docs/tutoriels/README.md
- docs/tutoriels/infrastructure/scaleway.md
- docs/tutoriels/infrastructure/scaleway_create_db.md
- docs/tutoriels/infrastructure/scaleway_monitoring.md
- scripts/sql/create_schema.sql
Notion : 👇 
**🗺️ contexte**: DB
**💡 quoi**: Migration de la base de données de Scalingoo vers Scaleway
**🎯 pourquoi**: Car on atteint les limites des base de données sur Scalingo
**🤔 comment**: Documentation de la procédure exécutée
> Documentation de la création de la base de données sur Scaleway

- dags/clone/tasks/business_logic/clone_table_create.py
- dags/utils/cmd.py
- qfdmo/management/commands/titlize_acteur_addresses.py
- qfdmo/migrations/0159_connect_public_to_warehouse.py
Quelques mini fix car ça ne marche pas exactement comme attendu en preprod
**💡 quoi**: Correction dsn et schema
**🎯 pourquoi**: car ça ne marche pas
**🤔 comment**: ajout de quote au dsn de la DB et correction de la migration pour utiliser le bon schema
> fix relattif à l'utilisation de la DB

- qfdmo/widgets.py
- templates/components/produit/_detail.html
- templates/components/produit/_infotri.html
- https://www.notion.so/accelerateur-transition-ecologique-ademe/iFrame-Hauteur-de-cadre-tr-s-grande-21d6523d57d7806cb2d9c62956ce46a9?source=copy_link
- https://www.notion.so/accelerateur-transition-ecologique-ademe/Lien-vers-l-info-tri-cass-21d6523d57d780f5beb5dcadcc025d8d?source=copy_link
- https://www.notion.so/accelerateur-transition-ecologique-ademe/Impossible-de-d-cocher-une-action-de-la-carte-bon-tat-a-d-coche-une-action-de-la-carte-mauva-21d6523d57d780798d13c09662c3e0ff?source=copy_link
**🗺️ contexte**: assistant v2
**💡 quoi**: derniers retours des équipes produit 
> Assistant geoloc feedbacks 3

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- package.json
- static/to_compile/admin-map-widget.ts
- static/to_compile/controllers/assistant/blink.ts
- static/to_compile/controllers/assistant/search.ts
- static/to_compile/controllers/carte/acteur_details.ts
- static/to_compile/controllers/carte/address_autocomplete_controller.ts
- static/to_compile/controllers/carte/autocomplete_controller.ts
- static/to_compile/controllers/carte/map_controller.ts
- static/to_compile/controllers/carte/ss_cat_object_autocomplete_controller.ts
- static/to_compile/controllers/shared/analytics.ts
- static/to_compile/controllers/shared/generic_autocomplete_controller.ts
- static/to_compile/embed/assistant.ts
- static/to_compile/embed/carte.ts
- static/to_compile/js/browser_check.ts
- static/to_compile/js/carte.ts
- static/to_compile/js/iframe.ts
- static/to_compile/js/iframe_functions.ts
- static/to_compile/js/parcel.d.ts
- static/to_compile/js/solution_map.ts
- static/to_compile/qfdmd.ts
- static/to_compile/tests/choose_action_controller.test.ts
- static/to_compile/tests/iframe_functions.test.ts
Cf problèmes rencontrés lors de l'ouverture de fichiers sur le poste de Nico
**🗺️ contexte**: outils internes
**💡 quoi**: lancement de prettier en CI et en local
**🎯 pourquoi**: pour éviter les disparités entre nos postes
- on execute `prettier --check` plutôt que fix dans le CI, fix n'échoue pas sur un exit code arrêtant la CI, et donc un formattage pété n'interrompt pas la CI 
- en local, on ajoute prettier aux pre commit hooks, ce qui évitera les disparités entre postes
- lancement du pre-commit sur tous les fichiers
À noter : je ne formatte pas au save, c'est un choix, je n'aime pas trop avoir le contenu de mes fichiers qui bouge. 
Il faut partir du principe qu'on utilise pas tous VSCode avec des settings identiques 😇 
> ✨ Amélioration de Prettier

- qfdmo/admin/acteur.py
Carte Notion : [Django Admin : il ne devrait pas être possible de créer un acteur sans Nom](https://www.notion.so/accelerateur-transition-ecologique-ademe/Django-Admin-il-ne-devrait-pas-tre-possible-de-cr-er-un-acteur-sans-Nom-20e6523d57d780458637c2cb5e0fab11?source=copy_link)
**💡 quoi**: Le nom est obligatoire à la création d'un RevisionActeur dans Django admin, optionnel à la mise à jour
**🎯 pourquoi**: Lors de la création d'une révision via Django Admin, une instance de Acteur est créée, celle-ci nécessite un `nom`. dans le cas d'une modification de RévisonActeur, on peu vouloir suppriemer la surdéfinition du nom pour qu l'cteur prenne le nom de Acteur Source et non de sa correction
**🤔 comment**: Création d'un ModelForm custom, ajout d'un clean sur le nom …
> Le champs 'nom' est obligatoire lors de la création d'un acteur via Django Admin

- .git-blame-ignore-revs
Tout est dans le titre ! 
Suite #1734
> 🙈 Ajouter le formattage massif de prettier au fichier d'exclusion du git blame

- templates/components/produit/heading.html
- templates/qfdmd/produit_page.html
La preview wagtail est down à cause d'une erreur de templating
> 🙈 Correction d'une erreur sur la preview Wagtail

- qfdmd/templatetags/qfdmd_tags.py
- static/to_compile/controllers/assistant/blink.ts
- static/to_compile/styles/qfdmd.css
- templates/components/logo/_base.html
- templates/components/logo/homepage.html
- templates/components/patchwork/_item.html
- templates/components/patchwork/patchwork.html
Cf https://www.notion.so/accelerateur-transition-ecologique-ademe/AST-2-Ajouter-toutes-les-ic-nes-de-toutes-les-REP-sur-la-page-d-accueil-1996523d57d780258c4ad80c49ec9656?source=copy_link
**🗺️ contexte**: assistant v2
**💡 quoi**: refonte de la grille d'objets en page d'accueil pour y inclure toutes les rep
**🤔 comment**: réécriture du css grid utilisé pour la construire
> 🧩 Refonte de la grille de produits en page d'accueil

- e2e_tests/django-admin.spec.ts
> Hotfix - désactivation temporaire d'un test e2e

- core/admin.py
- data/admin.py
- qfdmo/admin/acteur.py
Suppression du filtre queryset des vues acteurs, qui gene Christian
> Suppression du filtre queryset des vues acteurs

- .github/workflows/review.yml
Fonctionnalité qu'on avait perdu : permettre le deploiement à partir d'une PR
**🗺️ contexte**: CI/CD
**💡 quoi**: deploiement d'une PR en preprod
**🎯 pourquoi**: permettre de tester
**🤔 comment**: ajout des étape dans review.yml
> Réactiver le déploiement sur les PR

- scripts/infrastructure/purge_db_logs.sh
Suite au déploiement de 2 bases de données par environnement, il faut adapter le script de nettoyage des logs
**💡 quoi**: 
Le script est modifié pour nettoyer les logs sur `webapp` et `warehouse`
Avoir une taille de disque faible
> Nettoyage des logs sur 2 bases de données

- data/models/changes/acteur_delete_as_parent.py
- unit_tests/data/models/changes/test_acteur_delete_as_parent.py
Mattermost : [le parent doublon devrait déjà être supprimé](https://mattermost.incubateur.net/betagouv/pl/aoshwy3wa7nniqowzix46w84bo)
**🗺️ contexte**: Airflow - Clustering
**💡 quoi**: Suppression du parent non effective
**🎯 pourquoi**: quand le parent à des enfants "inactif" ou "supprimé"
**🤔 comment**:
- Dans le cas où le parent à supprimer existe toujours : 
- si il a des enfants actif -> on raise la même erreur
- si il a des enfants inactif -> on met à jour le statut du parent à "inactif"
- si il a des enfants supprimer -> on met à jour le statut du parent à "supprimé"
> [Clustering] Parfois le parent à supprimer existe toujours

- bin/post_deploy
**🗺️ contexte**: Déploiement - infra
**💡 quoi**: recréer le server et schema distant de `warehouse` vers `webapp` après avoir passé les migrations
**🎯 pourquoi**: Sinon, les nouvelles colonnes ne sont pas prises en compte
**🤔 comment**: lancer `setup_dbt_schemas` après les migration lors du déploiement
> recreation du server/schema distant après chaque évolution de la DB

- infrastructure/environments/preprod/database/.terraform.lock.hcl
- infrastructure/environments/preprod/database/terragrunt.hcl
Suite de la séparation des DB
**🗺️ contexte**: Infra Terragrunt
**💡 quoi**: Utilisation d'instance DB-PLAY2-NANO en preprod
**🎯 pourquoi**: Moins cher, moins de limit de quotas
**🤔 comment**: Mise à jour de la config
> Utilisation d'instance DB-PLAY2-NANO en preprod

- infrastructure/modules/database/main.tf
Corrige le nom d'une variable qui n'existait pas dans la configuration.
**💡 quoi**: 
> Infra database : correction nom de variable

- dags/sources/config/db_mapping.json
Tout est dans le titre :)
**🗺️ contexte**: Airflow Source CITEO
**💡 quoi**: Nouvelle sous cat
**🎯 pourquoi**: La consigne !!!
**🤔 comment**: Ajout du mapping des consignes
> Ajout du mapping CITEO vers emballage reemployable

- dags/clone/dags/clone_ae_etablissement.py
- dags/clone/dags/clone_ae_unite_legale.py
Tout est dans le titre :)
**🗺️ contexte**: Airflow clone Annuaire-entreprise
**💡 quoi**: Modification des endpoints
> Annuaire-Entreprise a modifié ses endpoint

- qfdmd/models.py
- qfdmd/templatetags/qfdmd_tags.py
Régression dans ma dernière PR
**🗺️ contexte**: Wagtail / produits v2
**💡 quoi**: corriger l'appel d'une fonction qui a été renommée
**🎯 pourquoi**: pour résoudre une 500
**🤔 comment**: on appelle la bonne fonction 
> Corriger un problème d'erreur lors de la visualisation d'une page Wagtail

- Makefile
- bin/post_deploy
Simplification et complétion des commandes make
**🗺️ contexte**: Makefile
**💡 quoi**: Commande make
**🎯 pourquoi**: simplification
**🤔 comment**: ajout et complétion de commande Make
> Adaptation du Makefile pour la gestion des 2 bases de données

- infrastructure/environments/preprod/container/terragrunt.hcl
- infrastructure/modules/container/airflow-scheduler.tf
- infrastructure/modules/container/airflow-webserver.tf
- infrastructure/modules/container/variables.tf
Ajustements pour Airflow en preprod sur Scaleway :
- augmente le CPU
- renomme une variable d'environnement
> Ajustements Airflow preprod

- e2e_tests/assistant.spec.ts
- e2e_tests/helpers.ts
- templates/qfdmo/carte/results.html
> Finalisation fix tests e2e

- data/models/suggestion.py
Correction de typo
**💡 quoi**: typo
> Petite typo lors de l'ingestion de service à domicile

- core/settings.py
- pyproject.toml
- qfdmo/admin/acteur.py
- uv.lock
Intégration de Djangoql
**🗺️ contexte**: Django admin
**💡 quoi**: Rendre flexible la recherche des acteurs
**🎯 pourquoi**: simplifier la recherche pour Christian
**🤔 comment**: intégration du pluggin [Djangoql](https://github.com/ivelum/djangoql)
> Rechercher avancé des acteurs dans Django admin

- core/settings.py
- e2e_tests/assistant.spec.ts
- playwright.config.ts
- templates/analytics/posthog_data_attributes.html
- templates/qfdmd/base.html
Les tests e2e sont toujours en carafe, tentative de correction de ceux-ci
**🗺️ contexte**: tests e2e 
**💡 quoi**: ajout de timeout pour forcer le peuplement du du sessionstorage
- desactivation de la debug toolbar dans les tests e2e 
- utilisation de délais manuels pour tenter de faire passer les tests 
- 
> Correction des test e2e
